version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api123#@!
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: api
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Porta pra usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local