import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "SP";

export class PopulateCityWithStateSPPart21640630044054
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Iperó', '${state.id}'),
          ('${uuidV4()}', 'Ipeúna', '${state.id}'),
          ('${uuidV4()}', 'Ipiguá', '${state.id}'),
          ('${uuidV4()}', 'Iporanga', '${state.id}'),
          ('${uuidV4()}', 'Ipuã', '${state.id}'),
          ('${uuidV4()}', 'Iracemápolis', '${state.id}'),
          ('${uuidV4()}', 'Irapuã', '${state.id}'),
          ('${uuidV4()}', 'Irapuru', '${state.id}'),
          ('${uuidV4()}', 'Itaberá', '${state.id}'),
          ('${uuidV4()}', 'Itaí', '${state.id}'),
          ('${uuidV4()}', 'Itajobi', '${state.id}'),
          ('${uuidV4()}', 'Itaju', '${state.id}'),
          ('${uuidV4()}', 'Itanhaém', '${state.id}'),
          ('${uuidV4()}', 'Itaóca', '${state.id}'),
          ('${uuidV4()}', 'Itapecerica da Serra', '${state.id}'),
          ('${uuidV4()}', 'Itapetininga', '${state.id}'),
          ('${uuidV4()}', 'Itapeva', '${state.id}'),
          ('${uuidV4()}', 'Itapevi', '${state.id}'),
          ('${uuidV4()}', 'Itapira', '${state.id}'),
          ('${uuidV4()}', 'Itapirapuã Paulista', '${state.id}'),
          ('${uuidV4()}', 'Itápolis', '${state.id}'),
          ('${uuidV4()}', 'Itaporanga', '${state.id}'),
          ('${uuidV4()}', 'Itapuí', '${state.id}'),
          ('${uuidV4()}', 'Itapura', '${state.id}'),
          ('${uuidV4()}', 'Itaquaquecetuba', '${state.id}'),
          ('${uuidV4()}', 'Itararé', '${state.id}'),
          ('${uuidV4()}', 'Itariri', '${state.id}'),
          ('${uuidV4()}', 'Itatiba', '${state.id}'),
          ('${uuidV4()}', 'Itatinga', '${state.id}'),
          ('${uuidV4()}', 'Itirapina', '${state.id}'),
          ('${uuidV4()}', 'Itirapuã', '${state.id}'),
          ('${uuidV4()}', 'Itobi', '${state.id}'),
          ('${uuidV4()}', 'Itu', '${state.id}'),
          ('${uuidV4()}', 'Itupeva', '${state.id}'),
          ('${uuidV4()}', 'Ituverava', '${state.id}'),
          ('${uuidV4()}', 'Jaborandi', '${state.id}'),
          ('${uuidV4()}', 'Jaboticabal', '${state.id}'),
          ('${uuidV4()}', 'Jacareí', '${state.id}'),
          ('${uuidV4()}', 'Jaci', '${state.id}'),
          ('${uuidV4()}', 'Jacupiranga', '${state.id}'),
          ('${uuidV4()}', 'Jaguariúna', '${state.id}'),
          ('${uuidV4()}', 'Jales', '${state.id}'),
          ('${uuidV4()}', 'Jambeiro', '${state.id}'),
          ('${uuidV4()}', 'Jandira', '${state.id}'),
          ('${uuidV4()}', 'Jardinópolis', '${state.id}'),
          ('${uuidV4()}', 'Jarinu', '${state.id}'),
          ('${uuidV4()}', 'Jaú', '${state.id}'),
          ('${uuidV4()}', 'Jeriquara', '${state.id}'),
          ('${uuidV4()}', 'Joanópolis', '${state.id}'),
          ('${uuidV4()}', 'João Ramalho', '${state.id}'),
          ('${uuidV4()}', 'José Bonifácio', '${state.id}'),
          ('${uuidV4()}', 'Júlio Mesquita', '${state.id}'),
          ('${uuidV4()}', 'Jumirim', '${state.id}'),
          ('${uuidV4()}', 'Jundiaí', '${state.id}'),
          ('${uuidV4()}', 'Junqueirópolis', '${state.id}'),
          ('${uuidV4()}', 'Juquiá', '${state.id}'),
          ('${uuidV4()}', 'Juquitiba', '${state.id}'),
          ('${uuidV4()}', 'Lagoinha', '${state.id}'),
          ('${uuidV4()}', 'Laranjal Paulista', '${state.id}'),
          ('${uuidV4()}', 'Lavínia', '${state.id}'),
          ('${uuidV4()}', 'Lavrinhas', '${state.id}'),
          ('${uuidV4()}', 'Leme', '${state.id}'),
          ('${uuidV4()}', 'Lençóis Paulista', '${state.id}'),
          ('${uuidV4()}', 'Limeira', '${state.id}'),
          ('${uuidV4()}', 'Lindóia', '${state.id}'),
          ('${uuidV4()}', 'Lins', '${state.id}'),
          ('${uuidV4()}', 'Lorena', '${state.id}'),
          ('${uuidV4()}', 'Lourdes', '${state.id}'),
          ('${uuidV4()}', 'Louveira', '${state.id}'),
          ('${uuidV4()}', 'Lucélia', '${state.id}'),
          ('${uuidV4()}', 'Lucianópolis', '${state.id}'),
          ('${uuidV4()}', 'Luís Antônio', '${state.id}'),
          ('${uuidV4()}', 'Luiziânia', '${state.id}'),
          ('${uuidV4()}', 'Lupércio', '${state.id}'),
          ('${uuidV4()}', 'Lutécia', '${state.id}'),
          ('${uuidV4()}', 'Macatuba', '${state.id}'),
          ('${uuidV4()}', 'Macaubal', '${state.id}'),
          ('${uuidV4()}', 'Macedônia', '${state.id}'),
          ('${uuidV4()}', 'Magda', '${state.id}'),
          ('${uuidV4()}', 'Mairinque', '${state.id}'),
          ('${uuidV4()}', 'Mairiporã', '${state.id}'),
          ('${uuidV4()}', 'Manduri', '${state.id}'),
          ('${uuidV4()}', 'Marabá Paulista', '${state.id}'),
          ('${uuidV4()}', 'Maracaí', '${state.id}'),
          ('${uuidV4()}', 'Marapoama', '${state.id}'),
          ('${uuidV4()}', 'Mariápolis', '${state.id}'),
          ('${uuidV4()}', 'Marília', '${state.id}'),
          ('${uuidV4()}', 'Marinópolis', '${state.id}'),
          ('${uuidV4()}', 'Martinópolis', '${state.id}'),
          ('${uuidV4()}', 'Matão', '${state.id}'),
          ('${uuidV4()}', 'Mauá', '${state.id}'),
          ('${uuidV4()}', 'Mendonça', '${state.id}'),
          ('${uuidV4()}', 'Meridiano', '${state.id}'),
          ('${uuidV4()}', 'Mesópolis', '${state.id}'),
          ('${uuidV4()}', 'Miguelópolis', '${state.id}'),
          ('${uuidV4()}', 'Mineiros do Tietê', '${state.id}'),
          ('${uuidV4()}', 'Mira Estrela', '${state.id}'),
          ('${uuidV4()}', 'Miracatu', '${state.id}'),
          ('${uuidV4()}', 'Mirandópolis', '${state.id}'),
          ('${uuidV4()}', 'Mirante do Paranapanema', '${state.id}'),
          ('${uuidV4()}', 'Mirassol', '${state.id}'),
          ('${uuidV4()}', 'Mirassolândia', '${state.id}'),
          ('${uuidV4()}', 'Mococa', '${state.id}'),
          ('${uuidV4()}', 'Mogi das Cruzes', '${state.id}'),
          ('${uuidV4()}', 'Mogi Guaçu', '${state.id}'),
          ('${uuidV4()}', 'Moji Mirim', '${state.id}'),
          ('${uuidV4()}', 'Mombuca', '${state.id}'),
          ('${uuidV4()}', 'Monções', '${state.id}'),
          ('${uuidV4()}', 'Mongaguá', '${state.id}'),
          ('${uuidV4()}', 'Monte Alegre do Sul', '${state.id}'),
          ('${uuidV4()}', 'Monte Alto', '${state.id}'),
          ('${uuidV4()}', 'Monte Aprazível', '${state.id}'),
          ('${uuidV4()}', 'Monte Azul Paulista', '${state.id}'),
          ('${uuidV4()}', 'Monte Castelo', '${state.id}'),
          ('${uuidV4()}', 'Monte Mor', '${state.id}'),
          ('${uuidV4()}', 'Monteiro Lobato', '${state.id}'),
          ('${uuidV4()}', 'Morro Agudo', '${state.id}'),
          ('${uuidV4()}', 'Morungaba', '${state.id}'),
          ('${uuidV4()}', 'Motuca', '${state.id}'),
          ('${uuidV4()}', 'Murutinga do Sul', '${state.id}'),
          ('${uuidV4()}', 'Nantes', '${state.id}'),
          ('${uuidV4()}', 'Narandiba', '${state.id}'),
          ('${uuidV4()}', 'Natividade da Serra', '${state.id}'),
          ('${uuidV4()}', 'Nazaré Paulista', '${state.id}'),
          ('${uuidV4()}', 'Neves Paulista', '${state.id}'),
          ('${uuidV4()}', 'Nhandeara', '${state.id}'),
          ('${uuidV4()}', 'Nipoã', '${state.id}'),
          ('${uuidV4()}', 'Nova Aliança', '${state.id}'),
          ('${uuidV4()}', 'Nova Campina', '${state.id}'),
          ('${uuidV4()}', 'Nova Canaã Paulista', '${state.id}'),
          ('${uuidV4()}', 'Nova Castilho', '${state.id}'),
          ('${uuidV4()}', 'Nova Europa', '${state.id}'),
          ('${uuidV4()}', 'Nova Granada', '${state.id}'),
          ('${uuidV4()}', 'Nova Guataporanga', '${state.id}'),
          ('${uuidV4()}', 'Nova Independência', '${state.id}'),
          ('${uuidV4()}', 'Nova Luzitânia', '${state.id}'),
          ('${uuidV4()}', 'Nova Odessa', '${state.id}'),
          ('${uuidV4()}', 'Novais', '${state.id}'),
          ('${uuidV4()}', 'Novo Horizonte', '${state.id}'),
          ('${uuidV4()}', 'Nuporanga', '${state.id}'),
          ('${uuidV4()}', 'Ocauçu', '${state.id}'),
          ('${uuidV4()}', 'Óleo', '${state.id}'),
          ('${uuidV4()}', 'Olímpia', '${state.id}'),
          ('${uuidV4()}', 'Onda Verde', '${state.id}'),
          ('${uuidV4()}', 'Oriente', '${state.id}'),
          ('${uuidV4()}', 'Orindiúva', '${state.id}'),
          ('${uuidV4()}', 'Orlândia', '${state.id}'),
          ('${uuidV4()}', 'Osasco', '${state.id}'),
          ('${uuidV4()}', 'Oscar Bressane', '${state.id}'),
          ('${uuidV4()}', 'Osvaldo Cruz', '${state.id}'),
          ('${uuidV4()}', 'Ourinhos', '${state.id}'),
          ('${uuidV4()}', 'Ouro Verde', '${state.id}'),
          ('${uuidV4()}', 'Ouroeste', '${state.id}'),
          ('${uuidV4()}', 'Pacaembu', '${state.id}'),
          ('${uuidV4()}', 'Palestina', '${state.id}'),
          ('${uuidV4()}', 'Palmares Paulista', '${state.id}'),
          ('${uuidV4()}', 'Palmeira d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Palmital', '${state.id}'),
          ('${uuidV4()}', 'Panorama', '${state.id}'),
          ('${uuidV4()}', 'Paraguaçu Paulista', '${state.id}'),
          ('${uuidV4()}', 'Paraibuna', '${state.id}'),
          ('${uuidV4()}', 'Paraíso', '${state.id}'),
          ('${uuidV4()}', 'Paranapanema', '${state.id}'),
          ('${uuidV4()}', 'Paranapuã', '${state.id}'),
          ('${uuidV4()}', 'Parapuã', '${state.id}'),
          ('${uuidV4()}', 'Pardinho', '${state.id}'),
          ('${uuidV4()}', 'Pariquera-Açu', '${state.id}'),
          ('${uuidV4()}', 'Parisi', '${state.id}'),
          ('${uuidV4()}', 'Patrocínio Paulista', '${state.id}'),
          ('${uuidV4()}', 'Paulicéia', '${state.id}'),
          ('${uuidV4()}', 'Paulínia', '${state.id}'),
          ('${uuidV4()}', 'Paulistânia', '${state.id}'),
          ('${uuidV4()}', 'Paulo de Faria', '${state.id}'),
          ('${uuidV4()}', 'Pederneiras', '${state.id}'),
          ('${uuidV4()}', 'Pedra Bela', '${state.id}'),
          ('${uuidV4()}', 'Pedranópolis', '${state.id}'),
          ('${uuidV4()}', 'Pedregulho', '${state.id}'),
          ('${uuidV4()}', 'Pedreira', '${state.id}'),
          ('${uuidV4()}', 'Pedrinhas Paulista', '${state.id}'),
          ('${uuidV4()}', 'Pedro de Toledo', '${state.id}'),
          ('${uuidV4()}', 'Penápolis', '${state.id}'),
          ('${uuidV4()}', 'Pereira Barreto', '${state.id}'),
          ('${uuidV4()}', 'Pereiras', '${state.id}'),
          ('${uuidV4()}', 'Peruíbe', '${state.id}'),
          ('${uuidV4()}', 'Piacatu', '${state.id}'),
          ('${uuidV4()}', 'Piedade', '${state.id}'),
          ('${uuidV4()}', 'Pilar do Sul', '${state.id}'),
          ('${uuidV4()}', 'Pindamonhangaba', '${state.id}'),
          ('${uuidV4()}', 'Pindorama', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
