import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "RS";

export class PopulateCityWithStateRS1640609550813
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Aceguá', '${state.id}'),
          ('${uuidV4()}', 'Água Santa', '${state.id}'),
          ('${uuidV4()}', 'Agudo', '${state.id}'),
          ('${uuidV4()}', 'Ajuricaba', '${state.id}'),
          ('${uuidV4()}', 'Alecrim', '${state.id}'),
          ('${uuidV4()}', 'Alegrete', '${state.id}'),
          ('${uuidV4()}', 'Alegria', '${state.id}'),
          ('${uuidV4()}', 'Almirante Tamandaré do Sul', '${state.id}'),
          ('${uuidV4()}', 'Alpestre', '${state.id}'),
          ('${uuidV4()}', 'Alto Alegre', '${state.id}'),
          ('${uuidV4()}', 'Alto Feliz', '${state.id}'),
          ('${uuidV4()}', 'Alvorada', '${state.id}'),
          ('${uuidV4()}', 'Amaral Ferrador', '${state.id}'),
          ('${uuidV4()}', 'Ametista do Sul', '${state.id}'),
          ('${uuidV4()}', 'André da Rocha', '${state.id}'),
          ('${uuidV4()}', 'Anta Gorda', '${state.id}'),
          ('${uuidV4()}', 'Antônio Prado', '${state.id}'),
          ('${uuidV4()}', 'Arambaré', '${state.id}'),
          ('${uuidV4()}', 'Araricá', '${state.id}'),
          ('${uuidV4()}', 'Aratiba', '${state.id}'),
          ('${uuidV4()}', 'Arroio do Meio', '${state.id}'),
          ('${uuidV4()}', 'Arroio do Padre', '${state.id}'),
          ('${uuidV4()}', 'Arroio do Sal', '${state.id}'),
          ('${uuidV4()}', 'Arroio do Tigre', '${state.id}'),
          ('${uuidV4()}', 'Arroio dos Ratos', '${state.id}'),
          ('${uuidV4()}', 'Arroio Grande', '${state.id}'),
          ('${uuidV4()}', 'Arvorezinha', '${state.id}'),
          ('${uuidV4()}', 'Augusto Pestana', '${state.id}'),
          ('${uuidV4()}', 'Áurea', '${state.id}'),
          ('${uuidV4()}', 'Bagé', '${state.id}'),
          ('${uuidV4()}', 'Balneário Pinhal', '${state.id}'),
          ('${uuidV4()}', 'Barão', '${state.id}'),
          ('${uuidV4()}', 'Barão de Cotegipe', '${state.id}'),
          ('${uuidV4()}', 'Barão do Triunfo', '${state.id}'),
          ('${uuidV4()}', 'Barra do Guarita', '${state.id}'),
          ('${uuidV4()}', 'Barra do Quaraí', '${state.id}'),
          ('${uuidV4()}', 'Barra do Ribeiro', '${state.id}'),
          ('${uuidV4()}', 'Barra do Rio Azul', '${state.id}'),
          ('${uuidV4()}', 'Barra Funda', '${state.id}'),
          ('${uuidV4()}', 'Barracão', '${state.id}'),
          ('${uuidV4()}', 'Barros Cassal', '${state.id}'),
          ('${uuidV4()}', 'Benjamin Constant do Sul', '${state.id}'),
          ('${uuidV4()}', 'Bento Gonçalves', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista das Missões', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista do Buricá', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista do Cadeado', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista do Incra', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista do Sul', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus', '${state.id}'),
          ('${uuidV4()}', 'Bom Princípio', '${state.id}'),
          ('${uuidV4()}', 'Bom Progresso', '${state.id}'),
          ('${uuidV4()}', 'Bom Retiro do Sul', '${state.id}'),
          ('${uuidV4()}', 'Boqueirão do Leão', '${state.id}'),
          ('${uuidV4()}', 'Bossoroca', '${state.id}'),
          ('${uuidV4()}', 'Bozano', '${state.id}'),
          ('${uuidV4()}', 'Braga', '${state.id}'),
          ('${uuidV4()}', 'Brochier', '${state.id}'),
          ('${uuidV4()}', 'Butiá', '${state.id}'),
          ('${uuidV4()}', 'Caçapava do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cacequi', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cachoeirinha', '${state.id}'),
          ('${uuidV4()}', 'Cacique Doble', '${state.id}'),
          ('${uuidV4()}', 'Caibaté', '${state.id}'),
          ('${uuidV4()}', 'Caiçara', '${state.id}'),
          ('${uuidV4()}', 'Camaquã', '${state.id}'),
          ('${uuidV4()}', 'Camargo', '${state.id}'),
          ('${uuidV4()}', 'Cambará do Sul', '${state.id}'),
          ('${uuidV4()}', 'Campestre da Serra', '${state.id}'),
          ('${uuidV4()}', 'Campina das Missões', '${state.id}'),
          ('${uuidV4()}', 'Campinas do Sul', '${state.id}'),
          ('${uuidV4()}', 'Campo Bom', '${state.id}'),
          ('${uuidV4()}', 'Campo Novo', '${state.id}'),
          ('${uuidV4()}', 'Campos Borges', '${state.id}'),
          ('${uuidV4()}', 'Candelária', '${state.id}'),
          ('${uuidV4()}', 'Cândido Godói', '${state.id}'),
          ('${uuidV4()}', 'Candiota', '${state.id}'),
          ('${uuidV4()}', 'Canela', '${state.id}'),
          ('${uuidV4()}', 'Canguçu', '${state.id}'),
          ('${uuidV4()}', 'Canoas', '${state.id}'),
          ('${uuidV4()}', 'Canudos do Vale', '${state.id}'),
          ('${uuidV4()}', 'Capão Bonito do Sul', '${state.id}'),
          ('${uuidV4()}', 'Capão da Canoa', '${state.id}'),
          ('${uuidV4()}', 'Capão do Cipó', '${state.id}'),
          ('${uuidV4()}', 'Capão do Leão', '${state.id}'),
          ('${uuidV4()}', 'Capela de Santana', '${state.id}'),
          ('${uuidV4()}', 'Capitão', '${state.id}'),
          ('${uuidV4()}', 'Capivari do Sul', '${state.id}'),
          ('${uuidV4()}', 'Caraá', '${state.id}'),
          ('${uuidV4()}', 'Carazinho', '${state.id}'),
          ('${uuidV4()}', 'Carlos Barbosa', '${state.id}'),
          ('${uuidV4()}', 'Carlos Gomes', '${state.id}'),
          ('${uuidV4()}', 'Casca', '${state.id}'),
          ('${uuidV4()}', 'Caseiros', '${state.id}'),
          ('${uuidV4()}', 'Catuípe', '${state.id}'),
          ('${uuidV4()}', 'Caxias do Sul', '${state.id}'),
          ('${uuidV4()}', 'Centenário', '${state.id}'),
          ('${uuidV4()}', 'Cerrito', '${state.id}'),
          ('${uuidV4()}', 'Cerro Branco', '${state.id}'),
          ('${uuidV4()}', 'Cerro Grande', '${state.id}'),
          ('${uuidV4()}', 'Cerro Grande do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cerro Largo', '${state.id}'),
          ('${uuidV4()}', 'Chapada', '${state.id}'),
          ('${uuidV4()}', 'Charqueadas', '${state.id}'),
          ('${uuidV4()}', 'Charrua', '${state.id}'),
          ('${uuidV4()}', 'Chiapeta', '${state.id}'),
          ('${uuidV4()}', 'Chuí', '${state.id}'),
          ('${uuidV4()}', 'Chuvisca', '${state.id}'),
          ('${uuidV4()}', 'Cidreira', '${state.id}'),
          ('${uuidV4()}', 'Ciríaco', '${state.id}'),
          ('${uuidV4()}', 'Colinas', '${state.id}'),
          ('${uuidV4()}', 'Colorado', '${state.id}'),
          ('${uuidV4()}', 'Condor', '${state.id}'),
          ('${uuidV4()}', 'Constantina', '${state.id}'),
          ('${uuidV4()}', 'Coqueiro Baixo', '${state.id}'),
          ('${uuidV4()}', 'Coqueiros do Sul', '${state.id}'),
          ('${uuidV4()}', 'Coronel Barros', '${state.id}'),
          ('${uuidV4()}', 'Coronel Bicaco', '${state.id}'),
          ('${uuidV4()}', 'Coronel Pilar', '${state.id}'),
          ('${uuidV4()}', 'Cotiporã', '${state.id}'),
          ('${uuidV4()}', 'Coxilha', '${state.id}'),
          ('${uuidV4()}', 'Crissiumal', '${state.id}'),
          ('${uuidV4()}', 'Cristal', '${state.id}'),
          ('${uuidV4()}', 'Cristal do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cruz Alta', '${state.id}'),
          ('${uuidV4()}', 'Cruzaltense', '${state.id}'),
          ('${uuidV4()}', 'Cruzeiro do Sul', '${state.id}'),
          ('${uuidV4()}', 'David Canabarro', '${state.id}'),
          ('${uuidV4()}', 'Derrubadas', '${state.id}'),
          ('${uuidV4()}', 'Dezesseis de Novembro', '${state.id}'),
          ('${uuidV4()}', 'Dilermando de Aguiar', '${state.id}'),
          ('${uuidV4()}', 'Dois Irmãos', '${state.id}'),
          ('${uuidV4()}', 'Dois Irmãos das Missões', '${state.id}'),
          ('${uuidV4()}', 'Dois Lajeados', '${state.id}'),
          ('${uuidV4()}', 'Dom Feliciano', '${state.id}'),
          ('${uuidV4()}', 'Dom Pedrito', '${state.id}'),
          ('${uuidV4()}', 'Dom Pedro de Alcântara', '${state.id}'),
          ('${uuidV4()}', 'Dona Francisca', '${state.id}'),
          ('${uuidV4()}', 'Doutor Maurício Cardoso', '${state.id}'),
          ('${uuidV4()}', 'Doutor Ricardo', '${state.id}'),
          ('${uuidV4()}', 'Eldorado do Sul', '${state.id}'),
          ('${uuidV4()}', 'Encantado', '${state.id}'),
          ('${uuidV4()}', 'Encruzilhada do Sul', '${state.id}'),
          ('${uuidV4()}', 'Engenho Velho', '${state.id}'),
          ('${uuidV4()}', 'Entre Rios do Sul', '${state.id}'),
          ('${uuidV4()}', 'Entre-Ijuís', '${state.id}'),
          ('${uuidV4()}', 'Erebango', '${state.id}'),
          ('${uuidV4()}', 'Erechim', '${state.id}'),
          ('${uuidV4()}', 'Ernestina', '${state.id}'),
          ('${uuidV4()}', 'Erval Grande', '${state.id}'),
          ('${uuidV4()}', 'Erval Seco', '${state.id}'),
          ('${uuidV4()}', 'Esmeralda', '${state.id}'),
          ('${uuidV4()}', 'Esperança do Sul', '${state.id}'),
          ('${uuidV4()}', 'Espumoso', '${state.id}'),
          ('${uuidV4()}', 'Estação', '${state.id}'),
          ('${uuidV4()}', 'Estância Velha', '${state.id}'),
          ('${uuidV4()}', 'Esteio', '${state.id}'),
          ('${uuidV4()}', 'Estrela', '${state.id}'),
          ('${uuidV4()}', 'Estrela Velha', '${state.id}'),
          ('${uuidV4()}', 'Eugênio de Castro', '${state.id}'),
          ('${uuidV4()}', 'Fagundes Varela', '${state.id}'),
          ('${uuidV4()}', 'Farroupilha', '${state.id}'),
          ('${uuidV4()}', 'Faxinal do Soturno', '${state.id}'),
          ('${uuidV4()}', 'Faxinalzinho', '${state.id}'),
          ('${uuidV4()}', 'Fazenda Vilanova', '${state.id}'),
          ('${uuidV4()}', 'Feliz', '${state.id}'),
          ('${uuidV4()}', 'Flores da Cunha', '${state.id}'),
          ('${uuidV4()}', 'Floriano Peixoto', '${state.id}'),
          ('${uuidV4()}', 'Fontoura Xavier', '${state.id}'),
          ('${uuidV4()}', 'Formigueiro', '${state.id}'),
          ('${uuidV4()}', 'Forquetinha', '${state.id}'),
          ('${uuidV4()}', 'Fortaleza dos Valos', '${state.id}'),
          ('${uuidV4()}', 'Frederico Westphalen', '${state.id}'),
          ('${uuidV4()}', 'Garibaldi', '${state.id}'),
          ('${uuidV4()}', 'Garruchos', '${state.id}'),
          ('${uuidV4()}', 'Gaurama', '${state.id}'),
          ('${uuidV4()}', 'General Câmara', '${state.id}'),
          ('${uuidV4()}', 'Gentil', '${state.id}'),
          ('${uuidV4()}', 'Getúlio Vargas', '${state.id}'),
          ('${uuidV4()}', 'Giruá', '${state.id}'),
          ('${uuidV4()}', 'Glorinha', '${state.id}'),
          ('${uuidV4()}', 'Gramado', '${state.id}'),
          ('${uuidV4()}', 'Gramado dos Loureiros', '${state.id}'),
          ('${uuidV4()}', 'Gramado Xavier', '${state.id}'),
          ('${uuidV4()}', 'Gravataí', '${state.id}'),
          ('${uuidV4()}', 'Guabiju', '${state.id}'),
          ('${uuidV4()}', 'Guaíba', '${state.id}'),
          ('${uuidV4()}', 'Guaporé', '${state.id}'),
          ('${uuidV4()}', 'Guarani das Missões', '${state.id}'),
          ('${uuidV4()}', 'Harmonia', '${state.id}'),
          ('${uuidV4()}', 'Herval', '${state.id}'),
          ('${uuidV4()}', 'Herveiras', '${state.id}'),
          ('${uuidV4()}', 'Horizontina', '${state.id}'),
          ('${uuidV4()}', 'Hulha Negra', '${state.id}'),
          ('${uuidV4()}', 'Humaitá', '${state.id}'),
          ('${uuidV4()}', 'Ibarama', '${state.id}'),
          ('${uuidV4()}', 'Ibiaçá', '${state.id}'),
          ('${uuidV4()}', 'Ibiraiaras', '${state.id}'),
          ('${uuidV4()}', 'Ibirapuitã', '${state.id}'),
          ('${uuidV4()}', 'Ibirubá', '${state.id}'),
          ('${uuidV4()}', 'Igrejinha', '${state.id}'),
          ('${uuidV4()}', 'Ijuí', '${state.id}'),
          ('${uuidV4()}', 'Ilópolis', '${state.id}'),
          ('${uuidV4()}', 'Imbé', '${state.id}'),
          ('${uuidV4()}', 'Imigrante', '${state.id}'),
          ('${uuidV4()}', 'Independência', '${state.id}'),
          ('${uuidV4()}', 'Inhacorá', '${state.id}'),
          ('${uuidV4()}', 'Ipê', '${state.id}'),
          ('${uuidV4()}', 'Ipiranga do Sul', '${state.id}'),
          ('${uuidV4()}', 'Iraí', '${state.id}'),
          ('${uuidV4()}', 'Itaara', '${state.id}'),
          ('${uuidV4()}', 'Itacurubi', '${state.id}'),
          ('${uuidV4()}', 'Itapuca', '${state.id}'),
          ('${uuidV4()}', 'Itaqui', '${state.id}'),
          ('${uuidV4()}', 'Itati', '${state.id}'),
          ('${uuidV4()}', 'Itatiba do Sul', '${state.id}'),
          ('${uuidV4()}', 'Ivorá', '${state.id}'),
          ('${uuidV4()}', 'Ivoti', '${state.id}'),
          ('${uuidV4()}', 'Jaboticaba', '${state.id}'),
          ('${uuidV4()}', 'Jacuizinho', '${state.id}'),
          ('${uuidV4()}', 'Jacutinga', '${state.id}'),
          ('${uuidV4()}', 'Jaguarão', '${state.id}'),
          ('${uuidV4()}', 'Jaguari', '${state.id}'),
          ('${uuidV4()}', 'Jaquirana', '${state.id}'),
          ('${uuidV4()}', 'Jari', '${state.id}'),
          ('${uuidV4()}', 'Jóia', '${state.id}'),
          ('${uuidV4()}', 'Júlio de Castilhos', '${state.id}'),
          ('${uuidV4()}', 'Lagoa Bonita do Sul', '${state.id}'),
          ('${uuidV4()}', 'Lagoa dos Três Cantos', '${state.id}'),
          ('${uuidV4()}', 'Lagoa Vermelha', '${state.id}'),
          ('${uuidV4()}', 'Lagoão', '${state.id}'),
          ('${uuidV4()}', 'Lajeado', '${state.id}'),
          ('${uuidV4()}', 'Lajeado do Bugre', '${state.id}'),
          ('${uuidV4()}', 'Lavras do Sul', '${state.id}'),
          ('${uuidV4()}', 'Liberato Salzano', '${state.id}'),
          ('${uuidV4()}', 'Lindolfo Collor', '${state.id}'),
          ('${uuidV4()}', 'Linha Nova', '${state.id}'),
          ('${uuidV4()}', 'Maçambara', '${state.id}'),
          ('${uuidV4()}', 'Machadinho', '${state.id}'),
          ('${uuidV4()}', 'Mampituba', '${state.id}'),
          ('${uuidV4()}', 'Manoel Viana', '${state.id}'),
          ('${uuidV4()}', 'Maquiné', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
