import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "SC";

export class PopulateCityWithStateSC1640609583202
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Abdon Batista', '${state.id}'),
          ('${uuidV4()}', 'Abelardo Luz', '${state.id}'),
          ('${uuidV4()}', 'Agrolândia', '${state.id}'),
          ('${uuidV4()}', 'Agronômica', '${state.id}'),
          ('${uuidV4()}', 'Água Doce', '${state.id}'),
          ('${uuidV4()}', 'Águas de Chapecó', '${state.id}'),
          ('${uuidV4()}', 'Águas Frias', '${state.id}'),
          ('${uuidV4()}', 'Águas Mornas', '${state.id}'),
          ('${uuidV4()}', 'Alfredo Wagner', '${state.id}'),
          ('${uuidV4()}', 'Alto Bela Vista', '${state.id}'),
          ('${uuidV4()}', 'Anchieta', '${state.id}'),
          ('${uuidV4()}', 'Angelina', '${state.id}'),
          ('${uuidV4()}', 'Anita Garibaldi', '${state.id}'),
          ('${uuidV4()}', 'Anitápolis', '${state.id}'),
          ('${uuidV4()}', 'Antônio Carlos', '${state.id}'),
          ('${uuidV4()}', 'Apiúna', '${state.id}'),
          ('${uuidV4()}', 'Arabutã', '${state.id}'),
          ('${uuidV4()}', 'Araquari', '${state.id}'),
          ('${uuidV4()}', 'Araranguá', '${state.id}'),
          ('${uuidV4()}', 'Armazém', '${state.id}'),
          ('${uuidV4()}', 'Arroio Trinta', '${state.id}'),
          ('${uuidV4()}', 'Arvoredo', '${state.id}'),
          ('${uuidV4()}', 'Ascurra', '${state.id}'),
          ('${uuidV4()}', 'Atalanta', '${state.id}'),
          ('${uuidV4()}', 'Aurora', '${state.id}'),
          ('${uuidV4()}', 'Balneário Arroio do Silva', '${state.id}'),
          ('${uuidV4()}', 'Balneário Barra do Sul', '${state.id}'),
          ('${uuidV4()}', 'Balneário Camboriú', '${state.id}'),
          ('${uuidV4()}', 'Balneário Gaivota', '${state.id}'),
          ('${uuidV4()}', 'Bandeirante', '${state.id}'),
          ('${uuidV4()}', 'Barra Bonita', '${state.id}'),
          ('${uuidV4()}', 'Barra Velha', '${state.id}'),
          ('${uuidV4()}', 'Bela Vista do Toldo', '${state.id}'),
          ('${uuidV4()}', 'Belmonte', '${state.id}'),
          ('${uuidV4()}', 'Benedito Novo', '${state.id}'),
          ('${uuidV4()}', 'Biguaçu', '${state.id}'),
          ('${uuidV4()}', 'Blumenau', '${state.id}'),
          ('${uuidV4()}', 'Bocaina do Sul', '${state.id}'),
          ('${uuidV4()}', 'Bom Jardim da Serra', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Bom Retiro', '${state.id}'),
          ('${uuidV4()}', 'Bombinhas', '${state.id}'),
          ('${uuidV4()}', 'Botuverá', '${state.id}'),
          ('${uuidV4()}', 'Braço do Norte', '${state.id}'),
          ('${uuidV4()}', 'Braço do Trombudo', '${state.id}'),
          ('${uuidV4()}', 'Brunópolis', '${state.id}'),
          ('${uuidV4()}', 'Brusque', '${state.id}'),
          ('${uuidV4()}', 'Caçador', '${state.id}'),
          ('${uuidV4()}', 'Caibi', '${state.id}'),
          ('${uuidV4()}', 'Calmon', '${state.id}'),
          ('${uuidV4()}', 'Camboriú', '${state.id}'),
          ('${uuidV4()}', 'Campo Alegre', '${state.id}'),
          ('${uuidV4()}', 'Campo Belo do Sul', '${state.id}'),
          ('${uuidV4()}', 'Campo Erê', '${state.id}'),
          ('${uuidV4()}', 'Campos Novos', '${state.id}'),
          ('${uuidV4()}', 'Canelinha', '${state.id}'),
          ('${uuidV4()}', 'Canoinhas', '${state.id}'),
          ('${uuidV4()}', 'Capão Alto', '${state.id}'),
          ('${uuidV4()}', 'Capinzal', '${state.id}'),
          ('${uuidV4()}', 'Capivari de Baixo', '${state.id}'),
          ('${uuidV4()}', 'Catanduvas', '${state.id}'),
          ('${uuidV4()}', 'Caxambu do Sul', '${state.id}'),
          ('${uuidV4()}', 'Celso Ramos', '${state.id}'),
          ('${uuidV4()}', 'Cerro Negro', '${state.id}'),
          ('${uuidV4()}', 'Chapadão do Lageado', '${state.id}'),
          ('${uuidV4()}', 'Chapecó', '${state.id}'),
          ('${uuidV4()}', 'Cocal do Sul', '${state.id}'),
          ('${uuidV4()}', 'Concórdia', '${state.id}'),
          ('${uuidV4()}', 'Cordilheira Alta', '${state.id}'),
          ('${uuidV4()}', 'Coronel Freitas', '${state.id}'),
          ('${uuidV4()}', 'Coronel Martins', '${state.id}'),
          ('${uuidV4()}', 'Correia Pinto', '${state.id}'),
          ('${uuidV4()}', 'Corupá', '${state.id}'),
          ('${uuidV4()}', 'Criciúma', '${state.id}'),
          ('${uuidV4()}', 'Cunha Porã', '${state.id}'),
          ('${uuidV4()}', 'Cunhataí', '${state.id}'),
          ('${uuidV4()}', 'Curitibanos', '${state.id}'),
          ('${uuidV4()}', 'Descanso', '${state.id}'),
          ('${uuidV4()}', 'Dionísio Cerqueira', '${state.id}'),
          ('${uuidV4()}', 'Dona Emma', '${state.id}'),
          ('${uuidV4()}', 'Doutor Pedrinho', '${state.id}'),
          ('${uuidV4()}', 'Entre Rios', '${state.id}'),
          ('${uuidV4()}', 'Ermo', '${state.id}'),
          ('${uuidV4()}', 'Erval Velho', '${state.id}'),
          ('${uuidV4()}', 'Faxinal dos Guedes', '${state.id}'),
          ('${uuidV4()}', 'Flor do Sertão', '${state.id}'),
          ('${uuidV4()}', 'Florianópolis', '${state.id}'),
          ('${uuidV4()}', 'Formosa do Sul', '${state.id}'),
          ('${uuidV4()}', 'Forquilhinha', '${state.id}'),
          ('${uuidV4()}', 'Fraiburgo', '${state.id}'),
          ('${uuidV4()}', 'Frei Rogério', '${state.id}'),
          ('${uuidV4()}', 'Galvão', '${state.id}'),
          ('${uuidV4()}', 'Garopaba', '${state.id}'),
          ('${uuidV4()}', 'Garuva', '${state.id}'),
          ('${uuidV4()}', 'Gaspar', '${state.id}'),
          ('${uuidV4()}', 'Governador Celso Ramos', '${state.id}'),
          ('${uuidV4()}', 'Grão Pará', '${state.id}'),
          ('${uuidV4()}', 'Gravatal', '${state.id}'),
          ('${uuidV4()}', 'Guabiruba', '${state.id}'),
          ('${uuidV4()}', 'Guaraciaba', '${state.id}'),
          ('${uuidV4()}', 'Guaramirim', '${state.id}'),
          ('${uuidV4()}', 'Guarujá do Sul', '${state.id}'),
          ('${uuidV4()}', 'Guatambú', '${state.id}'),
          ('${uuidV4()}', 'Herval d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Ibiam', '${state.id}'),
          ('${uuidV4()}', 'Ibicaré', '${state.id}'),
          ('${uuidV4()}', 'Ibirama', '${state.id}'),
          ('${uuidV4()}', 'Içara', '${state.id}'),
          ('${uuidV4()}', 'Ilhota', '${state.id}'),
          ('${uuidV4()}', 'Imaruí', '${state.id}'),
          ('${uuidV4()}', 'Imbituba', '${state.id}'),
          ('${uuidV4()}', 'Imbuia', '${state.id}'),
          ('${uuidV4()}', 'Indaial', '${state.id}'),
          ('${uuidV4()}', 'Iomerê', '${state.id}'),
          ('${uuidV4()}', 'Ipira', '${state.id}'),
          ('${uuidV4()}', 'Iporã do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Ipuaçu', '${state.id}'),
          ('${uuidV4()}', 'Ipumirim', '${state.id}'),
          ('${uuidV4()}', 'Iraceminha', '${state.id}'),
          ('${uuidV4()}', 'Irani', '${state.id}'),
          ('${uuidV4()}', 'Irati', '${state.id}'),
          ('${uuidV4()}', 'Irineópolis', '${state.id}'),
          ('${uuidV4()}', 'Itá', '${state.id}'),
          ('${uuidV4()}', 'Itaiópolis', '${state.id}'),
          ('${uuidV4()}', 'Itajaí', '${state.id}'),
          ('${uuidV4()}', 'Itapema', '${state.id}'),
          ('${uuidV4()}', 'Itapiranga', '${state.id}'),
          ('${uuidV4()}', 'Itapoá', '${state.id}'),
          ('${uuidV4()}', 'Ituporanga', '${state.id}'),
          ('${uuidV4()}', 'Jaborá', '${state.id}'),
          ('${uuidV4()}', 'Jacinto Machado', '${state.id}'),
          ('${uuidV4()}', 'Jaguaruna', '${state.id}'),
          ('${uuidV4()}', 'Jaraguá do Sul', '${state.id}'),
          ('${uuidV4()}', 'Jardinópolis', '${state.id}'),
          ('${uuidV4()}', 'Joaçaba', '${state.id}'),
          ('${uuidV4()}', 'Joinville', '${state.id}'),
          ('${uuidV4()}', 'José Boiteux', '${state.id}'),
          ('${uuidV4()}', 'Jupiá', '${state.id}'),
          ('${uuidV4()}', 'Lacerdópolis', '${state.id}'),
          ('${uuidV4()}', 'Lages', '${state.id}'),
          ('${uuidV4()}', 'Laguna', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
