import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "SP";

export class PopulateCityWithStateSPPart31640630189773
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Pinhalzinho', '${state.id}'),
          ('${uuidV4()}', 'Piquerobi', '${state.id}'),
          ('${uuidV4()}', 'Piquete', '${state.id}'),
          ('${uuidV4()}', 'Piracaia', '${state.id}'),
          ('${uuidV4()}', 'Piracicaba', '${state.id}'),
          ('${uuidV4()}', 'Piraju', '${state.id}'),
          ('${uuidV4()}', 'Pirajuí', '${state.id}'),
          ('${uuidV4()}', 'Pirangi', '${state.id}'),
          ('${uuidV4()}', 'Pirapora do Bom Jesus', '${state.id}'),
          ('${uuidV4()}', 'Pirapozinho', '${state.id}'),
          ('${uuidV4()}', 'Pirassununga', '${state.id}'),
          ('${uuidV4()}', 'Piratininga', '${state.id}'),
          ('${uuidV4()}', 'Pitangueiras', '${state.id}'),
          ('${uuidV4()}', 'Planalto', '${state.id}'),
          ('${uuidV4()}', 'Platina', '${state.id}'),
          ('${uuidV4()}', 'Poá', '${state.id}'),
          ('${uuidV4()}', 'Poloni', '${state.id}'),
          ('${uuidV4()}', 'Pompéia', '${state.id}'),
          ('${uuidV4()}', 'Pongaí', '${state.id}'),
          ('${uuidV4()}', 'Pontal', '${state.id}'),
          ('${uuidV4()}', 'Pontalinda', '${state.id}'),
          ('${uuidV4()}', 'Pontes Gestal', '${state.id}'),
          ('${uuidV4()}', 'Populina', '${state.id}'),
          ('${uuidV4()}', 'Porangaba', '${state.id}'),
          ('${uuidV4()}', 'Porto Feliz', '${state.id}'),
          ('${uuidV4()}', 'Porto Ferreira', '${state.id}'),
          ('${uuidV4()}', 'Potim', '${state.id}'),
          ('${uuidV4()}', 'Potirendaba', '${state.id}'),
          ('${uuidV4()}', 'Pracinha', '${state.id}'),
          ('${uuidV4()}', 'Pradópolis', '${state.id}'),
          ('${uuidV4()}', 'Praia Grande', '${state.id}'),
          ('${uuidV4()}', 'Pratânia', '${state.id}'),
          ('${uuidV4()}', 'Presidente Alves', '${state.id}'),
          ('${uuidV4()}', 'Presidente Bernardes', '${state.id}'),
          ('${uuidV4()}', 'Presidente Epitácio', '${state.id}'),
          ('${uuidV4()}', 'Presidente Prudente', '${state.id}'),
          ('${uuidV4()}', 'Presidente Venceslau', '${state.id}'),
          ('${uuidV4()}', 'Promissão', '${state.id}'),
          ('${uuidV4()}', 'Quadra', '${state.id}'),
          ('${uuidV4()}', 'Quatá', '${state.id}'),
          ('${uuidV4()}', 'Queiroz', '${state.id}'),
          ('${uuidV4()}', 'Queluz', '${state.id}'),
          ('${uuidV4()}', 'Quintana', '${state.id}'),
          ('${uuidV4()}', 'Rafard', '${state.id}'),
          ('${uuidV4()}', 'Rancharia', '${state.id}'),
          ('${uuidV4()}', 'Redenção da Serra', '${state.id}'),
          ('${uuidV4()}', 'Regente Feijó', '${state.id}'),
          ('${uuidV4()}', 'Reginópolis', '${state.id}'),
          ('${uuidV4()}', 'Registro', '${state.id}'),
          ('${uuidV4()}', 'Restinga', '${state.id}'),
          ('${uuidV4()}', 'Ribeira', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Bonito', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Branco', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Corrente', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão do Sul', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão dos Índios', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Grande', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Pires', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Preto', '${state.id}'),
          ('${uuidV4()}', 'Rifaina', '${state.id}'),
          ('${uuidV4()}', 'Rincão', '${state.id}'),
          ('${uuidV4()}', 'Rinópolis', '${state.id}'),
          ('${uuidV4()}', 'Rio Claro', '${state.id}'),
          ('${uuidV4()}', 'Rio das Pedras', '${state.id}'),
          ('${uuidV4()}', 'Rio Grande da Serra', '${state.id}'),
          ('${uuidV4()}', 'Riolândia', '${state.id}'),
          ('${uuidV4()}', 'Riversul', '${state.id}'),
          ('${uuidV4()}', 'Rosana', '${state.id}'),
          ('${uuidV4()}', 'Roseira', '${state.id}'),
          ('${uuidV4()}', 'Rubiácea', '${state.id}'),
          ('${uuidV4()}', 'Rubinéia', '${state.id}'),
          ('${uuidV4()}', 'Sabino', '${state.id}'),
          ('${uuidV4()}', 'Sagres', '${state.id}'),
          ('${uuidV4()}', 'Sales', '${state.id}'),
          ('${uuidV4()}', 'Sales Oliveira', '${state.id}'),
          ('${uuidV4()}', 'Salesópolis', '${state.id}'),
          ('${uuidV4()}', 'Salmourão', '${state.id}'),
          ('${uuidV4()}', 'Saltinho', '${state.id}'),
          ('${uuidV4()}', 'Salto', '${state.id}'),
          ('${uuidV4()}', 'Salto de Pirapora', '${state.id}'),
          ('${uuidV4()}', 'Salto Grande', '${state.id}'),
          ('${uuidV4()}', 'Sandovalina', '${state.id}'),
          ('${uuidV4()}', 'Santa Adélia', '${state.id}'),
          ('${uuidV4()}', 'Santa Albertina', '${state.id}'),
          ('${uuidV4()}', 'Santa Bárbara d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Santa Branca', '${state.id}'),
          ('${uuidV4()}', 'Santa Clara d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz da Conceição', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz da Esperança', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz das Palmeiras', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz do Rio Pardo', '${state.id}'),
          ('${uuidV4()}', 'Santa Ernestina', '${state.id}'),
          ('${uuidV4()}', 'Santa Fé do Sul', '${state.id}'),
          ('${uuidV4()}', 'Santa Gertrudes', '${state.id}'),
          ('${uuidV4()}', 'Santa Isabel', '${state.id}'),
          ('${uuidV4()}', 'Santa Lúcia', '${state.id}'),
          ('${uuidV4()}', 'Santa Maria da Serra', '${state.id}'),
          ('${uuidV4()}', 'Santa Mercedes', '${state.id}'),
          ('${uuidV4()}', 'Santa Rita d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Santa Rita do Passa Quatro', '${state.id}'),
          ('${uuidV4()}', 'Santa Rosa de Viterbo', '${state.id}'),
          ('${uuidV4()}', 'Santa Salete', '${state.id}'),
          ('${uuidV4()}', 'Santana da Ponte Pensa', '${state.id}'),
          ('${uuidV4()}', 'Santana de Parnaíba', '${state.id}'),
          ('${uuidV4()}', 'Santo Anastácio', '${state.id}'),
          ('${uuidV4()}', 'Santo André', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio da Alegria', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio de Posse', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Aracanguá', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Jardim', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Pinhal', '${state.id}'),
          ('${uuidV4()}', 'Santo Expedito', '${state.id}'),
          ('${uuidV4()}', 'Santópolis do Aguapeí', '${state.id}'),
          ('${uuidV4()}', 'Santos', '${state.id}'),
          ('${uuidV4()}', 'São Bento do Sapucaí', '${state.id}'),
          ('${uuidV4()}', 'São Bernardo do Campo', '${state.id}'),
          ('${uuidV4()}', 'São Caetano do Sul', '${state.id}'),
          ('${uuidV4()}', 'São Carlos', '${state.id}'),
          ('${uuidV4()}', 'São Francisco', '${state.id}'),
          ('${uuidV4()}', 'São João da Boa Vista', '${state.id}'),
          ('${uuidV4()}', 'São João das Duas Pontes', '${state.id}'),
          ('${uuidV4()}', 'São João de Iracema', '${state.id}'),
          ('${uuidV4()}', 'São João do Pau d´Alho', '${state.id}'),
          ('${uuidV4()}', 'São Joaquim da Barra', '${state.id}'),
          ('${uuidV4()}', 'São José da Bela Vista', '${state.id}'),
          ('${uuidV4()}', 'São José do Barreiro', '${state.id}'),
          ('${uuidV4()}', 'São José do Rio Pardo', '${state.id}'),
          ('${uuidV4()}', 'São José do Rio Preto', '${state.id}'),
          ('${uuidV4()}', 'São José dos Campos', '${state.id}'),
          ('${uuidV4()}', 'São Lourenço da Serra', '${state.id}'),
          ('${uuidV4()}', 'São Luís do Paraitinga', '${state.id}'),
          ('${uuidV4()}', 'São Manuel', '${state.id}'),
          ('${uuidV4()}', 'São Miguel Arcanjo', '${state.id}'),
          ('${uuidV4()}', 'São Paulo', '${state.id}'),
          ('${uuidV4()}', 'São Pedro', '${state.id}'),
          ('${uuidV4()}', 'São Pedro do Turvo', '${state.id}'),
          ('${uuidV4()}', 'São Roque', '${state.id}'),
          ('${uuidV4()}', 'São Sebastião', '${state.id}'),
          ('${uuidV4()}', 'São Sebastião da Grama', '${state.id}'),
          ('${uuidV4()}', 'São Simão', '${state.id}'),
          ('${uuidV4()}', 'São Vicente', '${state.id}'),
          ('${uuidV4()}', 'Sarapuí', '${state.id}'),
          ('${uuidV4()}', 'Sarutaiá', '${state.id}'),
          ('${uuidV4()}', 'Sebastianópolis do Sul', '${state.id}'),
          ('${uuidV4()}', 'Serra Azul', '${state.id}'),
          ('${uuidV4()}', 'Serra Negra', '${state.id}'),
          ('${uuidV4()}', 'Serrana', '${state.id}'),
          ('${uuidV4()}', 'Sertãozinho', '${state.id}'),
          ('${uuidV4()}', 'Sete Barras', '${state.id}'),
          ('${uuidV4()}', 'Severínia', '${state.id}'),
          ('${uuidV4()}', 'Silveiras', '${state.id}'),
          ('${uuidV4()}', 'Socorro', '${state.id}'),
          ('${uuidV4()}', 'Sorocaba', '${state.id}'),
          ('${uuidV4()}', 'Sud Mennucci', '${state.id}'),
          ('${uuidV4()}', 'Sumaré', '${state.id}'),
          ('${uuidV4()}', 'Suzanápolis', '${state.id}'),
          ('${uuidV4()}', 'Suzano', '${state.id}'),
          ('${uuidV4()}', 'Tabapuã', '${state.id}'),
          ('${uuidV4()}', 'Tabatinga', '${state.id}'),
          ('${uuidV4()}', 'Taboão da Serra', '${state.id}'),
          ('${uuidV4()}', 'Taciba', '${state.id}'),
          ('${uuidV4()}', 'Taguaí', '${state.id}'),
          ('${uuidV4()}', 'Taiaçu', '${state.id}'),
          ('${uuidV4()}', 'Taiúva', '${state.id}'),
          ('${uuidV4()}', 'Tambaú', '${state.id}'),
          ('${uuidV4()}', 'Tanabi', '${state.id}'),
          ('${uuidV4()}', 'Tapiraí', '${state.id}'),
          ('${uuidV4()}', 'Tapiratiba', '${state.id}'),
          ('${uuidV4()}', 'Taquaral', '${state.id}'),
          ('${uuidV4()}', 'Taquaritinga', '${state.id}'),
          ('${uuidV4()}', 'Taquarituba', '${state.id}'),
          ('${uuidV4()}', 'Taquarivaí', '${state.id}'),
          ('${uuidV4()}', 'Tarabai', '${state.id}'),
          ('${uuidV4()}', 'Tarumã', '${state.id}'),
          ('${uuidV4()}', 'Tatuí', '${state.id}'),
          ('${uuidV4()}', 'Taubaté', '${state.id}'),
          ('${uuidV4()}', 'Tejupá', '${state.id}'),
          ('${uuidV4()}', 'Teodoro Sampaio', '${state.id}'),
          ('${uuidV4()}', 'Terra Roxa', '${state.id}'),
          ('${uuidV4()}', 'Tietê', '${state.id}'),
          ('${uuidV4()}', 'Timburi', '${state.id}'),
          ('${uuidV4()}', 'Torre de Pedra', '${state.id}'),
          ('${uuidV4()}', 'Torrinha', '${state.id}'),
          ('${uuidV4()}', 'Trabiju', '${state.id}'),
          ('${uuidV4()}', 'Tremembé', '${state.id}'),
          ('${uuidV4()}', 'Três Fronteiras', '${state.id}'),
          ('${uuidV4()}', 'Tuiuti', '${state.id}'),
          ('${uuidV4()}', 'Tupã', '${state.id}'),
          ('${uuidV4()}', 'Tupi Paulista', '${state.id}'),
          ('${uuidV4()}', 'Turiúba', '${state.id}'),
          ('${uuidV4()}', 'Turmalina', '${state.id}'),
          ('${uuidV4()}', 'Ubarana', '${state.id}'),
          ('${uuidV4()}', 'Ubatuba', '${state.id}'),
          ('${uuidV4()}', 'Ubirajara', '${state.id}'),
          ('${uuidV4()}', 'Uchoa', '${state.id}'),
          ('${uuidV4()}', 'União Paulista', '${state.id}'),
          ('${uuidV4()}', 'Urânia', '${state.id}'),
          ('${uuidV4()}', 'Uru', '${state.id}'),
          ('${uuidV4()}', 'Urupês', '${state.id}'),
          ('${uuidV4()}', 'Valentim Gentil', '${state.id}'),
          ('${uuidV4()}', 'Valinhos', '${state.id}'),
          ('${uuidV4()}', 'Valparaíso', '${state.id}'),
          ('${uuidV4()}', 'Vargem', '${state.id}'),
          ('${uuidV4()}', 'Vargem Grande do Sul', '${state.id}'),
          ('${uuidV4()}', 'Vargem Grande Paulista', '${state.id}'),
          ('${uuidV4()}', 'Várzea Paulista', '${state.id}'),
          ('${uuidV4()}', 'Vera Cruz', '${state.id}'),
          ('${uuidV4()}', 'Vinhedo', '${state.id}'),
          ('${uuidV4()}', 'Viradouro', '${state.id}'),
          ('${uuidV4()}', 'Vista Alegre do Alto', '${state.id}'),
          ('${uuidV4()}', 'Vitória Brasil', '${state.id}'),
          ('${uuidV4()}', 'Votorantim', '${state.id}'),
          ('${uuidV4()}', 'Votuporanga', '${state.id}'),
          ('${uuidV4()}', 'Zacarias', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
