import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "PE";

export class PopulateCityWithStatePE1640609513403
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Abreu e Lima', '${state.id}'),
          ('${uuidV4()}', 'Afogados da Ingazeira', '${state.id}'),
          ('${uuidV4()}', 'Afrânio', '${state.id}'),
          ('${uuidV4()}', 'Agrestina', '${state.id}'),
          ('${uuidV4()}', 'Água Preta', '${state.id}'),
          ('${uuidV4()}', 'Águas Belas', '${state.id}'),
          ('${uuidV4()}', 'Alagoinha', '${state.id}'),
          ('${uuidV4()}', 'Aliança', '${state.id}'),
          ('${uuidV4()}', 'Altinho', '${state.id}'),
          ('${uuidV4()}', 'Amaraji', '${state.id}'),
          ('${uuidV4()}', 'Angelim', '${state.id}'),
          ('${uuidV4()}', 'Araçoiaba', '${state.id}'),
          ('${uuidV4()}', 'Araripina', '${state.id}'),
          ('${uuidV4()}', 'Arcoverde', '${state.id}'),
          ('${uuidV4()}', 'Barra de Guabiraba', '${state.id}'),
          ('${uuidV4()}', 'Barreiros', '${state.id}'),
          ('${uuidV4()}', 'Belém de Maria', '${state.id}'),
          ('${uuidV4()}', 'Belém de São Francisco', '${state.id}'),
          ('${uuidV4()}', 'Belo Jardim', '${state.id}'),
          ('${uuidV4()}', 'Betânia', '${state.id}'),
          ('${uuidV4()}', 'Bezerros', '${state.id}'),
          ('${uuidV4()}', 'Bodocó', '${state.id}'),
          ('${uuidV4()}', 'Bom Conselho', '${state.id}'),
          ('${uuidV4()}', 'Bom Jardim', '${state.id}'),
          ('${uuidV4()}', 'Bonito', '${state.id}'),
          ('${uuidV4()}', 'Brejão', '${state.id}'),
          ('${uuidV4()}', 'Brejinho', '${state.id}'),
          ('${uuidV4()}', 'Brejo da Madre de Deus', '${state.id}'),
          ('${uuidV4()}', 'Buenos Aires', '${state.id}'),
          ('${uuidV4()}', 'Buíque', '${state.id}'),
          ('${uuidV4()}', 'Cabo de Santo Agostinho', '${state.id}'),
          ('${uuidV4()}', 'Cabrobó', '${state.id}'),
          ('${uuidV4()}', 'Cachoeirinha', '${state.id}'),
          ('${uuidV4()}', 'Caetés', '${state.id}'),
          ('${uuidV4()}', 'Calçado', '${state.id}'),
          ('${uuidV4()}', 'Calumbi', '${state.id}'),
          ('${uuidV4()}', 'Camaragibe', '${state.id}'),
          ('${uuidV4()}', 'Camocim de São Félix', '${state.id}'),
          ('${uuidV4()}', 'Camutanga', '${state.id}'),
          ('${uuidV4()}', 'Canhotinho', '${state.id}'),
          ('${uuidV4()}', 'Capoeiras', '${state.id}'),
          ('${uuidV4()}', 'Carnaíba', '${state.id}'),
          ('${uuidV4()}', 'Carnaubeira da Penha', '${state.id}'),
          ('${uuidV4()}', 'Carpina', '${state.id}'),
          ('${uuidV4()}', 'Caruaru', '${state.id}'),
          ('${uuidV4()}', 'Casinhas', '${state.id}'),
          ('${uuidV4()}', 'Catende', '${state.id}'),
          ('${uuidV4()}', 'Cedro', '${state.id}'),
          ('${uuidV4()}', 'Chã de Alegria', '${state.id}'),
          ('${uuidV4()}', 'Chã Grande', '${state.id}'),
          ('${uuidV4()}', 'Condado', '${state.id}'),
          ('${uuidV4()}', 'Correntes', '${state.id}'),
          ('${uuidV4()}', 'Cortês', '${state.id}'),
          ('${uuidV4()}', 'Cumaru', '${state.id}'),
          ('${uuidV4()}', 'Cupira', '${state.id}'),
          ('${uuidV4()}', 'Custódia', '${state.id}'),
          ('${uuidV4()}', 'Dormentes', '${state.id}'),
          ('${uuidV4()}', 'Escada', '${state.id}'),
          ('${uuidV4()}', 'Exu', '${state.id}'),
          ('${uuidV4()}', 'Feira Nova', '${state.id}'),
          ('${uuidV4()}', 'Fernando de Noronha', '${state.id}'),
          ('${uuidV4()}', 'Ferreiros', '${state.id}'),
          ('${uuidV4()}', 'Flores', '${state.id}'),
          ('${uuidV4()}', 'Floresta', '${state.id}'),
          ('${uuidV4()}', 'Frei Miguelinho', '${state.id}'),
          ('${uuidV4()}', 'Gameleira', '${state.id}'),
          ('${uuidV4()}', 'Garanhuns', '${state.id}'),
          ('${uuidV4()}', 'Glória do Goitá', '${state.id}'),
          ('${uuidV4()}', 'Goiana', '${state.id}'),
          ('${uuidV4()}', 'Granito', '${state.id}'),
          ('${uuidV4()}', 'Gravatá', '${state.id}'),
          ('${uuidV4()}', 'Iati', '${state.id}'),
          ('${uuidV4()}', 'Ibimirim', '${state.id}'),
          ('${uuidV4()}', 'Ibirajuba', '${state.id}'),
          ('${uuidV4()}', 'Igarassu', '${state.id}'),
          ('${uuidV4()}', 'Iguaraci', '${state.id}'),
          ('${uuidV4()}', 'Ilha de Itamaracá', '${state.id}'),
          ('${uuidV4()}', 'Inajá', '${state.id}'),
          ('${uuidV4()}', 'Ingazeira', '${state.id}'),
          ('${uuidV4()}', 'Ipojuca', '${state.id}'),
          ('${uuidV4()}', 'Ipubi', '${state.id}'),
          ('${uuidV4()}', 'Itacuruba', '${state.id}'),
          ('${uuidV4()}', 'Itaíba', '${state.id}'),
          ('${uuidV4()}', 'Itambé', '${state.id}'),
          ('${uuidV4()}', 'Itapetim', '${state.id}'),
          ('${uuidV4()}', 'Itapissuma', '${state.id}'),
          ('${uuidV4()}', 'Itaquitinga', '${state.id}'),
          ('${uuidV4()}', 'Jaboatão dos Guararapes', '${state.id}'),
          ('${uuidV4()}', 'Jaqueira', '${state.id}'),
          ('${uuidV4()}', 'Jataúba', '${state.id}'),
          ('${uuidV4()}', 'Jatobá', '${state.id}'),
          ('${uuidV4()}', 'João Alfredo', '${state.id}'),
          ('${uuidV4()}', 'Joaquim Nabuco', '${state.id}'),
          ('${uuidV4()}', 'Jucati', '${state.id}'),
          ('${uuidV4()}', 'Jupi', '${state.id}'),
          ('${uuidV4()}', 'Jurema', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Carro', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Itaenga', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Ouro', '${state.id}'),
          ('${uuidV4()}', 'Lagoa dos Gatos', '${state.id}'),
          ('${uuidV4()}', 'Lagoa Grande', '${state.id}'),
          ('${uuidV4()}', 'Lajedo', '${state.id}'),
          ('${uuidV4()}', 'Limoeiro', '${state.id}'),
          ('${uuidV4()}', 'Macaparana', '${state.id}'),
          ('${uuidV4()}', 'Machados', '${state.id}'),
          ('${uuidV4()}', 'Manari', '${state.id}'),
          ('${uuidV4()}', 'Maraial', '${state.id}'),
          ('${uuidV4()}', 'Mirandiba', '${state.id}'),
          ('${uuidV4()}', 'Moreilândia', '${state.id}'),
          ('${uuidV4()}', 'Moreno', '${state.id}'),
          ('${uuidV4()}', 'Nazaré da Mata', '${state.id}'),
          ('${uuidV4()}', 'Olinda', '${state.id}'),
          ('${uuidV4()}', 'Orobó', '${state.id}'),
          ('${uuidV4()}', 'Orocó', '${state.id}'),
          ('${uuidV4()}', 'Ouricuri', '${state.id}'),
          ('${uuidV4()}', 'Palmares', '${state.id}'),
          ('${uuidV4()}', 'Palmeirina', '${state.id}'),
          ('${uuidV4()}', 'Panelas', '${state.id}'),
          ('${uuidV4()}', 'Paranatama', '${state.id}'),
          ('${uuidV4()}', 'Parnamirim', '${state.id}'),
          ('${uuidV4()}', 'Passira', '${state.id}'),
          ('${uuidV4()}', 'Paudalho', '${state.id}'),
          ('${uuidV4()}', 'Paulista', '${state.id}'),
          ('${uuidV4()}', 'Pedra', '${state.id}'),
          ('${uuidV4()}', 'Pesqueira', '${state.id}'),
          ('${uuidV4()}', 'Petrolândia', '${state.id}'),
          ('${uuidV4()}', 'Petrolina', '${state.id}'),
          ('${uuidV4()}', 'Poção', '${state.id}'),
          ('${uuidV4()}', 'Pombos', '${state.id}'),
          ('${uuidV4()}', 'Primavera', '${state.id}'),
          ('${uuidV4()}', 'Quipapá', '${state.id}'),
          ('${uuidV4()}', 'Quixaba', '${state.id}'),
          ('${uuidV4()}', 'Recife', '${state.id}'),
          ('${uuidV4()}', 'Riacho das Almas', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão', '${state.id}'),
          ('${uuidV4()}', 'Rio Formoso', '${state.id}'),
          ('${uuidV4()}', 'Sairé', '${state.id}'),
          ('${uuidV4()}', 'Salgadinho', '${state.id}'),
          ('${uuidV4()}', 'Salgueiro', '${state.id}'),
          ('${uuidV4()}', 'Saloá', '${state.id}'),
          ('${uuidV4()}', 'Sanharó', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz da Baixa Verde', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz do Capibaribe', '${state.id}'),
          ('${uuidV4()}', 'Santa Filomena', '${state.id}'),
          ('${uuidV4()}', 'Santa Maria da Boa Vista', '${state.id}'),
          ('${uuidV4()}', 'Santa Maria do Cambucá', '${state.id}'),
          ('${uuidV4()}', 'Santa Terezinha', '${state.id}'),
          ('${uuidV4()}', 'São Benedito do Sul', '${state.id}'),
          ('${uuidV4()}', 'São Bento do Una', '${state.id}'),
          ('${uuidV4()}', 'São Caitano', '${state.id}'),
          ('${uuidV4()}', 'São João', '${state.id}'),
          ('${uuidV4()}', 'São Joaquim do Monte', '${state.id}'),
          ('${uuidV4()}', 'São José da Coroa Grande', '${state.id}'),
          ('${uuidV4()}', 'São José do Belmonte', '${state.id}'),
          ('${uuidV4()}', 'São José do Egito', '${state.id}'),
          ('${uuidV4()}', 'São Lourenço da Mata', '${state.id}'),
          ('${uuidV4()}', 'São Vicente Ferrer', '${state.id}'),
          ('${uuidV4()}', 'Serra Talhada', '${state.id}'),
          ('${uuidV4()}', 'Serrita', '${state.id}'),
          ('${uuidV4()}', 'Sertânia', '${state.id}'),
          ('${uuidV4()}', 'Sirinhaém', '${state.id}'),
          ('${uuidV4()}', 'Solidão', '${state.id}'),
          ('${uuidV4()}', 'Surubim', '${state.id}'),
          ('${uuidV4()}', 'Tabira', '${state.id}'),
          ('${uuidV4()}', 'Tacaimbó', '${state.id}'),
          ('${uuidV4()}', 'Tacaratu', '${state.id}'),
          ('${uuidV4()}', 'Tamandaré', '${state.id}'),
          ('${uuidV4()}', 'Taquaritinga do Norte', '${state.id}'),
          ('${uuidV4()}', 'Terezinha', '${state.id}'),
          ('${uuidV4()}', 'Terra Nova', '${state.id}'),
          ('${uuidV4()}', 'Timbaúba', '${state.id}'),
          ('${uuidV4()}', 'Toritama', '${state.id}'),
          ('${uuidV4()}', 'Tracunhaém', '${state.id}'),
          ('${uuidV4()}', 'Trindade', '${state.id}'),
          ('${uuidV4()}', 'Triunfo', '${state.id}'),
          ('${uuidV4()}', 'Tupanatinga', '${state.id}'),
          ('${uuidV4()}', 'Tuparetama', '${state.id}'),
          ('${uuidV4()}', 'Venturosa', '${state.id}'),
          ('${uuidV4()}', 'Verdejante', '${state.id}'),
          ('${uuidV4()}', 'Vertente do Lério', '${state.id}'),
          ('${uuidV4()}', 'Vertentes', '${state.id}'),
          ('${uuidV4()}', 'Vicência', '${state.id}'),
          ('${uuidV4()}', 'Vitória de Santo Antão', '${state.id}'),
          ('${uuidV4()}', 'Xexéu', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
