import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "PB";

export class PopulateCityWithStatePB1640609502091
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Água Branca', '${state.id}'),
          ('${uuidV4()}', 'Aguiar', '${state.id}'),
          ('${uuidV4()}', 'Alagoa Grande', '${state.id}'),
          ('${uuidV4()}', 'Alagoa Nova', '${state.id}'),
          ('${uuidV4()}', 'Alagoinha', '${state.id}'),
          ('${uuidV4()}', 'Alcantil', '${state.id}'),
          ('${uuidV4()}', 'Algodão de Jandaíra', '${state.id}'),
          ('${uuidV4()}', 'Alhandra', '${state.id}'),
          ('${uuidV4()}', 'Amparo', '${state.id}'),
          ('${uuidV4()}', 'Aparecida', '${state.id}'),
          ('${uuidV4()}', 'Araçagi', '${state.id}'),
          ('${uuidV4()}', 'Arara', '${state.id}'),
          ('${uuidV4()}', 'Araruna', '${state.id}'),
          ('${uuidV4()}', 'Areia', '${state.id}'),
          ('${uuidV4()}', 'Areia de Baraúnas', '${state.id}'),
          ('${uuidV4()}', 'Areial', '${state.id}'),
          ('${uuidV4()}', 'Aroeiras', '${state.id}'),
          ('${uuidV4()}', 'Assunção', '${state.id}'),
          ('${uuidV4()}', 'Baía da Traição', '${state.id}'),
          ('${uuidV4()}', 'Bananeiras', '${state.id}'),
          ('${uuidV4()}', 'Baraúna', '${state.id}'),
          ('${uuidV4()}', 'Barra de Santa Rosa', '${state.id}'),
          ('${uuidV4()}', 'Barra de Santana', '${state.id}'),
          ('${uuidV4()}', 'Barra de São Miguel', '${state.id}'),
          ('${uuidV4()}', 'Bayeux', '${state.id}'),
          ('${uuidV4()}', 'Belém', '${state.id}'),
          ('${uuidV4()}', 'Belém do Brejo do Cruz', '${state.id}'),
          ('${uuidV4()}', 'Bernardino Batista', '${state.id}'),
          ('${uuidV4()}', 'Boa Ventura', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus', '${state.id}'),
          ('${uuidV4()}', 'Bom Sucesso', '${state.id}'),
          ('${uuidV4()}', 'Bonito de Santa Fé', '${state.id}'),
          ('${uuidV4()}', 'Boqueirão', '${state.id}'),
          ('${uuidV4()}', 'Borborema', '${state.id}'),
          ('${uuidV4()}', 'Brejo do Cruz', '${state.id}'),
          ('${uuidV4()}', 'Brejo dos Santos', '${state.id}'),
          ('${uuidV4()}', 'Caaporã', '${state.id}'),
          ('${uuidV4()}', 'Cabaceiras', '${state.id}'),
          ('${uuidV4()}', 'Cabedelo', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira dos Índios', '${state.id}'),
          ('${uuidV4()}', 'Cacimba de Areia', '${state.id}'),
          ('${uuidV4()}', 'Cacimba de Dentro', '${state.id}'),
          ('${uuidV4()}', 'Cacimbas', '${state.id}'),
          ('${uuidV4()}', 'Caiçara', '${state.id}'),
          ('${uuidV4()}', 'Cajazeiras', '${state.id}'),
          ('${uuidV4()}', 'Cajazeirinhas', '${state.id}'),
          ('${uuidV4()}', 'Caldas Brandão', '${state.id}'),
          ('${uuidV4()}', 'Camalaú', '${state.id}'),
          ('${uuidV4()}', 'Campina Grande', '${state.id}'),
          ('${uuidV4()}', 'Campo de Santana', '${state.id}'),
          ('${uuidV4()}', 'Capim', '${state.id}'),
          ('${uuidV4()}', 'Caraúbas', '${state.id}'),
          ('${uuidV4()}', 'Carrapateira', '${state.id}'),
          ('${uuidV4()}', 'Casserengue', '${state.id}'),
          ('${uuidV4()}', 'Catingueira', '${state.id}'),
          ('${uuidV4()}', 'Catolé do Rocha', '${state.id}'),
          ('${uuidV4()}', 'Caturité', '${state.id}'),
          ('${uuidV4()}', 'Conceição', '${state.id}'),
          ('${uuidV4()}', 'Condado', '${state.id}'),
          ('${uuidV4()}', 'Conde', '${state.id}'),
          ('${uuidV4()}', 'Congo', '${state.id}'),
          ('${uuidV4()}', 'Coremas', '${state.id}'),
          ('${uuidV4()}', 'Coxixola', '${state.id}'),
          ('${uuidV4()}', 'Cruz do Espírito Santo', '${state.id}'),
          ('${uuidV4()}', 'Cubati', '${state.id}'),
          ('${uuidV4()}', 'Cuité', '${state.id}'),
          ('${uuidV4()}', 'Cuité de Mamanguape', '${state.id}'),
          ('${uuidV4()}', 'Cuitegi', '${state.id}'),
          ('${uuidV4()}', 'Curral de Cima', '${state.id}'),
          ('${uuidV4()}', 'Curral Velho', '${state.id}'),
          ('${uuidV4()}', 'Damião', '${state.id}'),
          ('${uuidV4()}', 'Desterro', '${state.id}'),
          ('${uuidV4()}', 'Diamante', '${state.id}'),
          ('${uuidV4()}', 'Dona Inês', '${state.id}'),
          ('${uuidV4()}', 'Duas Estradas', '${state.id}'),
          ('${uuidV4()}', 'Emas', '${state.id}'),
          ('${uuidV4()}', 'Esperança', '${state.id}'),
          ('${uuidV4()}', 'Fagundes', '${state.id}'),
          ('${uuidV4()}', 'Frei Martinho', '${state.id}'),
          ('${uuidV4()}', 'Gado Bravo', '${state.id}'),
          ('${uuidV4()}', 'Guarabira', '${state.id}'),
          ('${uuidV4()}', 'Gurinhém', '${state.id}'),
          ('${uuidV4()}', 'Gurjão', '${state.id}'),
          ('${uuidV4()}', 'Ibiara', '${state.id}'),
          ('${uuidV4()}', 'Igaracy', '${state.id}'),
          ('${uuidV4()}', 'Imaculada', '${state.id}'),
          ('${uuidV4()}', 'Ingá', '${state.id}'),
          ('${uuidV4()}', 'Itabaiana', '${state.id}'),
          ('${uuidV4()}', 'Itaporanga', '${state.id}'),
          ('${uuidV4()}', 'Itapororoca', '${state.id}'),
          ('${uuidV4()}', 'Itatuba', '${state.id}'),
          ('${uuidV4()}', 'Jacaraú', '${state.id}'),
          ('${uuidV4()}', 'Jericó', '${state.id}'),
          ('${uuidV4()}', 'João Pessoa', '${state.id}'),
          ('${uuidV4()}', 'Juarez Távora', '${state.id}'),
          ('${uuidV4()}', 'Juazeirinho', '${state.id}'),
          ('${uuidV4()}', 'Junco do Seridó', '${state.id}'),
          ('${uuidV4()}', 'Juripiranga', '${state.id}'),
          ('${uuidV4()}', 'Juru', '${state.id}'),
          ('${uuidV4()}', 'Lagoa', '${state.id}'),
          ('${uuidV4()}', 'Lagoa de Dentro', '${state.id}'),
          ('${uuidV4()}', 'Lagoa Seca', '${state.id}'),
          ('${uuidV4()}', 'Lastro', '${state.id}'),
          ('${uuidV4()}', 'Livramento', '${state.id}'),
          ('${uuidV4()}', 'Logradouro', '${state.id}'),
          ('${uuidV4()}', 'Lucena', '${state.id}'),
          ('${uuidV4()}', 'Mãe d´Água', '${state.id}'),
          ('${uuidV4()}', 'Malta', '${state.id}'),
          ('${uuidV4()}', 'Mamanguape', '${state.id}'),
          ('${uuidV4()}', 'Manaíra', '${state.id}'),
          ('${uuidV4()}', 'Marcação', '${state.id}'),
          ('${uuidV4()}', 'Mari', '${state.id}'),
          ('${uuidV4()}', 'Marizópolis', '${state.id}'),
          ('${uuidV4()}', 'Massaranduba', '${state.id}'),
          ('${uuidV4()}', 'Mataraca', '${state.id}'),
          ('${uuidV4()}', 'Matinhas', '${state.id}'),
          ('${uuidV4()}', 'Mato Grosso', '${state.id}'),
          ('${uuidV4()}', 'Maturéia', '${state.id}'),
          ('${uuidV4()}', 'Mogeiro', '${state.id}'),
          ('${uuidV4()}', 'Montadas', '${state.id}'),
          ('${uuidV4()}', 'Monte Horebe', '${state.id}'),
          ('${uuidV4()}', 'Monteiro', '${state.id}'),
          ('${uuidV4()}', 'Mulungu', '${state.id}'),
          ('${uuidV4()}', 'Natuba', '${state.id}'),
          ('${uuidV4()}', 'Nazarezinho', '${state.id}'),
          ('${uuidV4()}', 'Nova Floresta', '${state.id}'),
          ('${uuidV4()}', 'Nova Olinda', '${state.id}'),
          ('${uuidV4()}', 'Nova Palmeira', '${state.id}'),
          ('${uuidV4()}', 'Olho d´Água', '${state.id}'),
          ('${uuidV4()}', 'Olivedos', '${state.id}'),
          ('${uuidV4()}', 'Ouro Velho', '${state.id}'),
          ('${uuidV4()}', 'Parari', '${state.id}'),
          ('${uuidV4()}', 'Passagem', '${state.id}'),
          ('${uuidV4()}', 'Patos', '${state.id}'),
          ('${uuidV4()}', 'Paulista', '${state.id}'),
          ('${uuidV4()}', 'Pedra Branca', '${state.id}'),
          ('${uuidV4()}', 'Pedra Lavrada', '${state.id}'),
          ('${uuidV4()}', 'Pedras de Fogo', '${state.id}'),
          ('${uuidV4()}', 'Pedro Régis', '${state.id}'),
          ('${uuidV4()}', 'Piancó', '${state.id}'),
          ('${uuidV4()}', 'Picuí', '${state.id}'),
          ('${uuidV4()}', 'Pilar', '${state.id}'),
          ('${uuidV4()}', 'Pilões', '${state.id}'),
          ('${uuidV4()}', 'Pilõezinhos', '${state.id}'),
          ('${uuidV4()}', 'Pirpirituba', '${state.id}'),
          ('${uuidV4()}', 'Pitimbu', '${state.id}'),
          ('${uuidV4()}', 'Pocinhos', '${state.id}'),
          ('${uuidV4()}', 'Poço Dantas', '${state.id}'),
          ('${uuidV4()}', 'Poço de José de Moura', '${state.id}'),
          ('${uuidV4()}', 'Pombal', '${state.id}'),
          ('${uuidV4()}', 'Prata', '${state.id}'),
          ('${uuidV4()}', 'Princesa Isabel', '${state.id}'),
          ('${uuidV4()}', 'Puxinanã', '${state.id}'),
          ('${uuidV4()}', 'Queimadas', '${state.id}'),
          ('${uuidV4()}', 'Quixabá', '${state.id}'),
          ('${uuidV4()}', 'Remígio', '${state.id}'),
          ('${uuidV4()}', 'Riachão', '${state.id}'),
          ('${uuidV4()}', 'Riachão do Bacamarte', '${state.id}'),
          ('${uuidV4()}', 'Riachão do Poço', '${state.id}'),
          ('${uuidV4()}', 'Riacho de Santo Antônio', '${state.id}'),
          ('${uuidV4()}', 'Riacho dos Cavalos', '${state.id}'),
          ('${uuidV4()}', 'Rio Tinto', '${state.id}'),
          ('${uuidV4()}', 'Salgadinho', '${state.id}'),
          ('${uuidV4()}', 'Salgado de São Félix', '${state.id}'),
          ('${uuidV4()}', 'Santa Cecília', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz', '${state.id}'),
          ('${uuidV4()}', 'Santa Helena', '${state.id}'),
          ('${uuidV4()}', 'Santa Inês', '${state.id}'),
          ('${uuidV4()}', 'Santa Luzia', '${state.id}'),
          ('${uuidV4()}', 'Santa Rita', '${state.id}'),
          ('${uuidV4()}', 'Santa Teresinha', '${state.id}'),
          ('${uuidV4()}', 'Santana de Mangueira', '${state.id}'),
          ('${uuidV4()}', 'Santana dos Garrotes', '${state.id}'),
          ('${uuidV4()}', 'Santarém', '${state.id}'),
          ('${uuidV4()}', 'Santo André', '${state.id}'),
          ('${uuidV4()}', 'São Bentinho', '${state.id}'),
          ('${uuidV4()}', 'São Bento', '${state.id}'),
          ('${uuidV4()}', 'São Domingos de Pombal', '${state.id}'),
          ('${uuidV4()}', 'São Domingos do Cariri', '${state.id}'),
          ('${uuidV4()}', 'São Francisco', '${state.id}'),
          ('${uuidV4()}', 'São João do Cariri', '${state.id}'),
          ('${uuidV4()}', 'São João do Rio do Peixe', '${state.id}'),
          ('${uuidV4()}', 'São João do Tigre', '${state.id}'),
          ('${uuidV4()}', 'São José da Lagoa Tapada', '${state.id}'),
          ('${uuidV4()}', 'São José de Caiana', '${state.id}'),
          ('${uuidV4()}', 'São José de Espinharas', '${state.id}'),
          ('${uuidV4()}', 'São José de Piranhas', '${state.id}'),
          ('${uuidV4()}', 'São José de Princesa', '${state.id}'),
          ('${uuidV4()}', 'São José do Bonfim', '${state.id}'),
          ('${uuidV4()}', 'São José do Brejo do Cruz', '${state.id}'),
          ('${uuidV4()}', 'São José do Sabugi', '${state.id}'),
          ('${uuidV4()}', 'São José dos Cordeiros', '${state.id}'),
          ('${uuidV4()}', 'São José dos Ramos', '${state.id}'),
          ('${uuidV4()}', 'São Mamede', '${state.id}'),
          ('${uuidV4()}', 'São Miguel de Taipu', '${state.id}'),
          ('${uuidV4()}', 'São Sebastião de Lagoa de Roça', '${state.id}'),
          ('${uuidV4()}', 'São Sebastião do Umbuzeiro', '${state.id}'),
          ('${uuidV4()}', 'Sapé', '${state.id}'),
          ('${uuidV4()}', 'Seridó', '${state.id}'),
          ('${uuidV4()}', 'Serra Branca', '${state.id}'),
          ('${uuidV4()}', 'Serra da Raiz', '${state.id}'),
          ('${uuidV4()}', 'Serra Grande', '${state.id}'),
          ('${uuidV4()}', 'Serra Redonda', '${state.id}'),
          ('${uuidV4()}', 'Serraria', '${state.id}'),
          ('${uuidV4()}', 'Sertãozinho', '${state.id}'),
          ('${uuidV4()}', 'Sobrado', '${state.id}'),
          ('${uuidV4()}', 'Solânea', '${state.id}'),
          ('${uuidV4()}', 'Soledade', '${state.id}'),
          ('${uuidV4()}', 'Sossêgo', '${state.id}'),
          ('${uuidV4()}', 'Sousa', '${state.id}'),
          ('${uuidV4()}', 'Sumé', '${state.id}'),
          ('${uuidV4()}', 'Taperoá', '${state.id}'),
          ('${uuidV4()}', 'Tavares', '${state.id}'),
          ('${uuidV4()}', 'Teixeira', '${state.id}'),
          ('${uuidV4()}', 'Tenório', '${state.id}'),
          ('${uuidV4()}', 'Triunfo', '${state.id}'),
          ('${uuidV4()}', 'Uiraúna', '${state.id}'),
          ('${uuidV4()}', 'Umbuzeiro', '${state.id}'),
          ('${uuidV4()}', 'Várzea', '${state.id}'),
          ('${uuidV4()}', 'Vieirópolis', '${state.id}'),
          ('${uuidV4()}', 'Vista Serrana', '${state.id}'),
          ('${uuidV4()}', 'Zabelê', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
