import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "PA";

export class PopulateCityWithStatePA1640609470553
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Abaetetuba', '${state.id}'),
          ('${uuidV4()}', 'Abel Figueiredo', '${state.id}'),
          ('${uuidV4()}', 'Acará', '${state.id}'),
          ('${uuidV4()}', 'Afuá', '${state.id}'),
          ('${uuidV4()}', 'Água Azul do Norte', '${state.id}'),
          ('${uuidV4()}', 'Alenquer', '${state.id}'),
          ('${uuidV4()}', 'Almeirim', '${state.id}'),
          ('${uuidV4()}', 'Altamira', '${state.id}'),
          ('${uuidV4()}', 'Anajás', '${state.id}'),
          ('${uuidV4()}', 'Ananindeua', '${state.id}'),
          ('${uuidV4()}', 'Anapu', '${state.id}'),
          ('${uuidV4()}', 'Augusto Corrêa', '${state.id}'),
          ('${uuidV4()}', 'Aurora do Pará', '${state.id}'),
          ('${uuidV4()}', 'Aveiro', '${state.id}'),
          ('${uuidV4()}', 'Bagre', '${state.id}'),
          ('${uuidV4()}', 'Baião', '${state.id}'),
          ('${uuidV4()}', 'Bannach', '${state.id}'),
          ('${uuidV4()}', 'Barcarena', '${state.id}'),
          ('${uuidV4()}', 'Belém', '${state.id}'),
          ('${uuidV4()}', 'Belterra', '${state.id}'),
          ('${uuidV4()}', 'Benevides', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Bonito', '${state.id}'),
          ('${uuidV4()}', 'Bragança', '${state.id}'),
          ('${uuidV4()}', 'Brasil Novo', '${state.id}'),
          ('${uuidV4()}', 'Brejo Grande do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Breu Branco', '${state.id}'),
          ('${uuidV4()}', 'Breves', '${state.id}'),
          ('${uuidV4()}', 'Bujaru', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira do Arari', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira do Piriá', '${state.id}'),
          ('${uuidV4()}', 'Cametá', '${state.id}'),
          ('${uuidV4()}', 'Canaã dos Carajás', '${state.id}'),
          ('${uuidV4()}', 'Capanema', '${state.id}'),
          ('${uuidV4()}', 'Capitão Poço', '${state.id}'),
          ('${uuidV4()}', 'Castanhal', '${state.id}'),
          ('${uuidV4()}', 'Chaves', '${state.id}'),
          ('${uuidV4()}', 'Colares', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Concórdia do Pará', '${state.id}'),
          ('${uuidV4()}', 'Cumaru do Norte', '${state.id}'),
          ('${uuidV4()}', 'Curionópolis', '${state.id}'),
          ('${uuidV4()}', 'Curralinho', '${state.id}'),
          ('${uuidV4()}', 'Curuá', '${state.id}'),
          ('${uuidV4()}', 'Curuçá', '${state.id}'),
          ('${uuidV4()}', 'Dom Eliseu', '${state.id}'),
          ('${uuidV4()}', 'Eldorado dos Carajás', '${state.id}'),
          ('${uuidV4()}', 'Faro', '${state.id}'),
          ('${uuidV4()}', 'Floresta do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Garrafão do Norte', '${state.id}'),
          ('${uuidV4()}', 'Goianésia do Pará', '${state.id}'),
          ('${uuidV4()}', 'Gurupá', '${state.id}'),
          ('${uuidV4()}', 'Igarapé-Açu', '${state.id}'),
          ('${uuidV4()}', 'Igarapé-Miri', '${state.id}'),
          ('${uuidV4()}', 'Inhangapi', '${state.id}'),
          ('${uuidV4()}', 'Ipixuna do Pará', '${state.id}'),
          ('${uuidV4()}', 'Irituia', '${state.id}'),
          ('${uuidV4()}', 'Itaituba', '${state.id}'),
          ('${uuidV4()}', 'Itupiranga', '${state.id}'),
          ('${uuidV4()}', 'Jacareacanga', '${state.id}'),
          ('${uuidV4()}', 'Jacundá', '${state.id}'),
          ('${uuidV4()}', 'Juruti', '${state.id}'),
          ('${uuidV4()}', 'Limoeiro do Ajuru', '${state.id}'),
          ('${uuidV4()}', 'Mãe do Rio', '${state.id}'),
          ('${uuidV4()}', 'Magalhães Barata', '${state.id}'),
          ('${uuidV4()}', 'Marabá', '${state.id}'),
          ('${uuidV4()}', 'Maracanã', '${state.id}'),
          ('${uuidV4()}', 'Marapanim', '${state.id}'),
          ('${uuidV4()}', 'Marituba', '${state.id}'),
          ('${uuidV4()}', 'Medicilândia', '${state.id}'),
          ('${uuidV4()}', 'Melgaço', '${state.id}'),
          ('${uuidV4()}', 'Mocajuba', '${state.id}'),
          ('${uuidV4()}', 'Moju', '${state.id}'),
          ('${uuidV4()}', 'Monte Alegre', '${state.id}'),
          ('${uuidV4()}', 'Muaná', '${state.id}'),
          ('${uuidV4()}', 'Nova Esperança do Piriá', '${state.id}'),
          ('${uuidV4()}', 'Nova Ipixuna', '${state.id}'),
          ('${uuidV4()}', 'Nova Timboteua', '${state.id}'),
          ('${uuidV4()}', 'Novo Progresso', '${state.id}'),
          ('${uuidV4()}', 'Novo Repartimento', '${state.id}'),
          ('${uuidV4()}', 'Óbidos', '${state.id}'),
          ('${uuidV4()}', 'Oeiras do Pará', '${state.id}'),
          ('${uuidV4()}', 'Oriximiná', '${state.id}'),
          ('${uuidV4()}', 'Ourém', '${state.id}'),
          ('${uuidV4()}', 'Ourilândia do Norte', '${state.id}'),
          ('${uuidV4()}', 'Pacajá', '${state.id}'),
          ('${uuidV4()}', 'Palestina do Pará', '${state.id}'),
          ('${uuidV4()}', 'Paragominas', '${state.id}'),
          ('${uuidV4()}', 'Parauapebas', '${state.id}'),
          ('${uuidV4()}', 'Pau d´Arco', '${state.id}'),
          ('${uuidV4()}', 'Peixe-Boi', '${state.id}'),
          ('${uuidV4()}', 'Piçarra', '${state.id}'),
          ('${uuidV4()}', 'Placas', '${state.id}'),
          ('${uuidV4()}', 'Ponta de Pedras', '${state.id}'),
          ('${uuidV4()}', 'Portel', '${state.id}'),
          ('${uuidV4()}', 'Porto de Moz', '${state.id}'),
          ('${uuidV4()}', 'Prainha', '${state.id}'),
          ('${uuidV4()}', 'Primavera', '${state.id}'),
          ('${uuidV4()}', 'Quatipuru', '${state.id}'),
          ('${uuidV4()}', 'Redenção', '${state.id}'),
          ('${uuidV4()}', 'Rio Maria', '${state.id}'),
          ('${uuidV4()}', 'Rondon do Pará', '${state.id}'),
          ('${uuidV4()}', 'Rurópolis', '${state.id}'),
          ('${uuidV4()}', 'Salinópolis', '${state.id}'),
          ('${uuidV4()}', 'Salvaterra', '${state.id}'),
          ('${uuidV4()}', 'Santa Bárbara do Pará', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz do Arari', '${state.id}'),
          ('${uuidV4()}', 'Santa Isabel do Pará', '${state.id}'),
          ('${uuidV4()}', 'Santa Luzia do Pará', '${state.id}'),
          ('${uuidV4()}', 'Santa Maria das Barreiras', '${state.id}'),
          ('${uuidV4()}', 'Santa Maria do Pará', '${state.id}'),
          ('${uuidV4()}', 'Santana do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Santarém', '${state.id}'),
          ('${uuidV4()}', 'Santarém Novo', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Tauá', '${state.id}'),
          ('${uuidV4()}', 'São Caetano de Odivelas', '${state.id}'),
          ('${uuidV4()}', 'São Domingos do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'São Domingos do Capim', '${state.id}'),
          ('${uuidV4()}', 'São Félix do Xingu', '${state.id}'),
          ('${uuidV4()}', 'São Francisco do Pará', '${state.id}'),
          ('${uuidV4()}', 'São Geraldo do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'São João da Ponta', '${state.id}'),
          ('${uuidV4()}', 'São João de Pirabas', '${state.id}'),
          ('${uuidV4()}', 'São João do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'São Miguel do Guamá', '${state.id}'),
          ('${uuidV4()}', 'São Sebastião da Boa Vista', '${state.id}'),
          ('${uuidV4()}', 'Sapucaia', '${state.id}'),
          ('${uuidV4()}', 'Senador José Porfírio', '${state.id}'),
          ('${uuidV4()}', 'Soure', '${state.id}'),
          ('${uuidV4()}', 'Tailândia', '${state.id}'),
          ('${uuidV4()}', 'Terra Alta', '${state.id}'),
          ('${uuidV4()}', 'Terra Santa', '${state.id}'),
          ('${uuidV4()}', 'Tomé-Açu', '${state.id}'),
          ('${uuidV4()}', 'Tracuateua', '${state.id}'),
          ('${uuidV4()}', 'Trairão', '${state.id}'),
          ('${uuidV4()}', 'Tucumã', '${state.id}'),
          ('${uuidV4()}', 'Tucuruí', '${state.id}'),
          ('${uuidV4()}', 'Ulianópolis', '${state.id}'),
          ('${uuidV4()}', 'Uruará', '${state.id}'),
          ('${uuidV4()}', 'Vigia', '${state.id}'),
          ('${uuidV4()}', 'Viseu', '${state.id}'),
          ('${uuidV4()}', 'Vitória do Xingu', '${state.id}'),
          ('${uuidV4()}', 'Xinguara', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
