import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "MG";

export class PopulateCityWithStateMG1640609462079
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Abadia dos Dourados', '${state.id}'),
          ('${uuidV4()}', 'Abaeté', '${state.id}'),
          ('${uuidV4()}', 'Abre Campo', '${state.id}'),
          ('${uuidV4()}', 'Acaiaca', '${state.id}'),
          ('${uuidV4()}', 'Açucena', '${state.id}'),
          ('${uuidV4()}', 'Água Boa', '${state.id}'),
          ('${uuidV4()}', 'Água Comprida', '${state.id}'),
          ('${uuidV4()}', 'Aguanil', '${state.id}'),
          ('${uuidV4()}', 'Águas Formosas', '${state.id}'),
          ('${uuidV4()}', 'Águas Vermelhas', '${state.id}'),
          ('${uuidV4()}', 'Aimorés', '${state.id}'),
          ('${uuidV4()}', 'Aiuruoca', '${state.id}'),
          ('${uuidV4()}', 'Alagoa', '${state.id}'),
          ('${uuidV4()}', 'Albertina', '${state.id}'),
          ('${uuidV4()}', 'Além Paraíba', '${state.id}'),
          ('${uuidV4()}', 'Alfenas', '${state.id}'),
          ('${uuidV4()}', 'Alfredo Vasconcelos', '${state.id}'),
          ('${uuidV4()}', 'Almenara', '${state.id}'),
          ('${uuidV4()}', 'Alpercata', '${state.id}'),
          ('${uuidV4()}', 'Alpinópolis', '${state.id}'),
          ('${uuidV4()}', 'Alterosa', '${state.id}'),
          ('${uuidV4()}', 'Alto Caparaó', '${state.id}'),
          ('${uuidV4()}', 'Alto Jequitibá', '${state.id}'),
          ('${uuidV4()}', 'Alto Rio Doce', '${state.id}'),
          ('${uuidV4()}', 'Alvarenga', '${state.id}'),
          ('${uuidV4()}', 'Alvinópolis', '${state.id}'),
          ('${uuidV4()}', 'Alvorada de Minas', '${state.id}'),
          ('${uuidV4()}', 'Amparo do Serra', '${state.id}'),
          ('${uuidV4()}', 'Andradas', '${state.id}'),
          ('${uuidV4()}', 'Andrelândia', '${state.id}'),
          ('${uuidV4()}', 'Angelândia', '${state.id}'),
          ('${uuidV4()}', 'Antônio Carlos', '${state.id}'),
          ('${uuidV4()}', 'Antônio Dias', '${state.id}'),
          ('${uuidV4()}', 'Antônio Prado de Minas', '${state.id}'),
          ('${uuidV4()}', 'Araçaí', '${state.id}'),
          ('${uuidV4()}', 'Aracitaba', '${state.id}'),
          ('${uuidV4()}', 'Araçuaí', '${state.id}'),
          ('${uuidV4()}', 'Araguari', '${state.id}'),
          ('${uuidV4()}', 'Arantina', '${state.id}'),
          ('${uuidV4()}', 'Araponga', '${state.id}'),
          ('${uuidV4()}', 'Araporã', '${state.id}'),
          ('${uuidV4()}', 'Arapuá', '${state.id}'),
          ('${uuidV4()}', 'Araújos', '${state.id}'),
          ('${uuidV4()}', 'Araxá', '${state.id}'),
          ('${uuidV4()}', 'Arceburgo', '${state.id}'),
          ('${uuidV4()}', 'Arcos', '${state.id}'),
          ('${uuidV4()}', 'Areado', '${state.id}'),
          ('${uuidV4()}', 'Argirita', '${state.id}'),
          ('${uuidV4()}', 'Aricanduva', '${state.id}'),
          ('${uuidV4()}', 'Arinos', '${state.id}'),
          ('${uuidV4()}', 'Astolfo Dutra', '${state.id}'),
          ('${uuidV4()}', 'Ataléia', '${state.id}'),
          ('${uuidV4()}', 'Augusto de Lima', '${state.id}'),
          ('${uuidV4()}', 'Baependi', '${state.id}'),
          ('${uuidV4()}', 'Baldim', '${state.id}'),
          ('${uuidV4()}', 'Bambuí', '${state.id}'),
          ('${uuidV4()}', 'Bandeira', '${state.id}'),
          ('${uuidV4()}', 'Bandeira do Sul', '${state.id}'),
          ('${uuidV4()}', 'Barão de Cocais', '${state.id}'),
          ('${uuidV4()}', 'Barão de Monte Alto', '${state.id}'),
          ('${uuidV4()}', 'Barbacena', '${state.id}'),
          ('${uuidV4()}', 'Barra Longa', '${state.id}'),
          ('${uuidV4()}', 'Barroso', '${state.id}'),
          ('${uuidV4()}', 'Bela Vista de Minas', '${state.id}'),
          ('${uuidV4()}', 'Belmiro Braga', '${state.id}'),
          ('${uuidV4()}', 'Belo Horizonte', '${state.id}'),
          ('${uuidV4()}', 'Belo Oriente', '${state.id}'),
          ('${uuidV4()}', 'Belo Vale', '${state.id}'),
          ('${uuidV4()}', 'Berilo', '${state.id}'),
          ('${uuidV4()}', 'Berizal', '${state.id}'),
          ('${uuidV4()}', 'Bertópolis', '${state.id}'),
          ('${uuidV4()}', 'Betim', '${state.id}'),
          ('${uuidV4()}', 'Bias Fortes', '${state.id}'),
          ('${uuidV4()}', 'Bicas', '${state.id}'),
          ('${uuidV4()}', 'Biquinhas', '${state.id}'),
          ('${uuidV4()}', 'Boa Esperança', '${state.id}'),
          ('${uuidV4()}', 'Bocaina de Minas', '${state.id}'),
          ('${uuidV4()}', 'Bocaiúva', '${state.id}'),
          ('${uuidV4()}', 'Bom Despacho', '${state.id}'),
          ('${uuidV4()}', 'Bom Jardim de Minas', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus da Penha', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus do Amparo', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus do Galho', '${state.id}'),
          ('${uuidV4()}', 'Bom Repouso', '${state.id}'),
          ('${uuidV4()}', 'Bom Sucesso', '${state.id}'),
          ('${uuidV4()}', 'Bonfim', '${state.id}'),
          ('${uuidV4()}', 'Bonfinópolis de Minas', '${state.id}'),
          ('${uuidV4()}', 'Bonito de Minas', '${state.id}'),
          ('${uuidV4()}', 'Borda da Mata', '${state.id}'),
          ('${uuidV4()}', 'Botelhos', '${state.id}'),
          ('${uuidV4()}', 'Botumirim', '${state.id}'),
          ('${uuidV4()}', 'Brás Pires', '${state.id}'),
          ('${uuidV4()}', 'Brasilândia de Minas', '${state.id}'),
          ('${uuidV4()}', 'Brasília de Minas', '${state.id}'),
          ('${uuidV4()}', 'Brasópolis', '${state.id}'),
          ('${uuidV4()}', 'Braúnas', '${state.id}'),
          ('${uuidV4()}', 'Brumadinho', '${state.id}'),
          ('${uuidV4()}', 'Bueno Brandão', '${state.id}'),
          ('${uuidV4()}', 'Buenópolis', '${state.id}'),
          ('${uuidV4()}', 'Bugre', '${state.id}'),
          ('${uuidV4()}', 'Buritis', '${state.id}'),
          ('${uuidV4()}', 'Buritizeiro', '${state.id}'),
          ('${uuidV4()}', 'Cabeceira Grande', '${state.id}'),
          ('${uuidV4()}', 'Cabo Verde', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira da Prata', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira de Minas', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira de Pajeú', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira Dourada', '${state.id}'),
          ('${uuidV4()}', 'Caetanópolis', '${state.id}'),
          ('${uuidV4()}', 'Caeté', '${state.id}'),
          ('${uuidV4()}', 'Caiana', '${state.id}'),
          ('${uuidV4()}', 'Cajuri', '${state.id}'),
          ('${uuidV4()}', 'Caldas', '${state.id}'),
          ('${uuidV4()}', 'Camacho', '${state.id}'),
          ('${uuidV4()}', 'Camanducaia', '${state.id}'),
          ('${uuidV4()}', 'Cambuí', '${state.id}'),
          ('${uuidV4()}', 'Cambuquira', '${state.id}'),
          ('${uuidV4()}', 'Campanário', '${state.id}'),
          ('${uuidV4()}', 'Campanha', '${state.id}'),
          ('${uuidV4()}', 'Campestre', '${state.id}'),
          ('${uuidV4()}', 'Campina Verde', '${state.id}'),
          ('${uuidV4()}', 'Campo Azul', '${state.id}'),
          ('${uuidV4()}', 'Campo Belo', '${state.id}'),
          ('${uuidV4()}', 'Campo do Meio', '${state.id}'),
          ('${uuidV4()}', 'Campo Florido', '${state.id}'),
          ('${uuidV4()}', 'Campos Altos', '${state.id}'),
          ('${uuidV4()}', 'Campos Gerais', '${state.id}'),
          ('${uuidV4()}', 'Cana Verde', '${state.id}'),
          ('${uuidV4()}', 'Canaã', '${state.id}'),
          ('${uuidV4()}', 'Canápolis', '${state.id}'),
          ('${uuidV4()}', 'Candeias', '${state.id}'),
          ('${uuidV4()}', 'Cantagalo', '${state.id}'),
          ('${uuidV4()}', 'Caparaó', '${state.id}'),
          ('${uuidV4()}', 'Capela Nova', '${state.id}'),
          ('${uuidV4()}', 'Capelinha', '${state.id}'),
          ('${uuidV4()}', 'Capetinga', '${state.id}'),
          ('${uuidV4()}', 'Capim Branco', '${state.id}'),
          ('${uuidV4()}', 'Capinópolis', '${state.id}'),
          ('${uuidV4()}', 'Capitão Andrade', '${state.id}'),
          ('${uuidV4()}', 'Capitão Enéas', '${state.id}'),
          ('${uuidV4()}', 'Capitólio', '${state.id}'),
          ('${uuidV4()}', 'Caputira', '${state.id}'),
          ('${uuidV4()}', 'Caraí', '${state.id}'),
          ('${uuidV4()}', 'Caranaíba', '${state.id}'),
          ('${uuidV4()}', 'Carandaí', '${state.id}'),
          ('${uuidV4()}', 'Carangola', '${state.id}'),
          ('${uuidV4()}', 'Caratinga', '${state.id}'),
          ('${uuidV4()}', 'Carbonita', '${state.id}'),
          ('${uuidV4()}', 'Careaçu', '${state.id}'),
          ('${uuidV4()}', 'Carlos Chagas', '${state.id}'),
          ('${uuidV4()}', 'Carmésia', '${state.id}'),
          ('${uuidV4()}', 'Carmo da Cachoeira', '${state.id}'),
          ('${uuidV4()}', 'Carmo da Mata', '${state.id}'),
          ('${uuidV4()}', 'Carmo de Minas', '${state.id}'),
          ('${uuidV4()}', 'Carmo do Cajuru', '${state.id}'),
          ('${uuidV4()}', 'Carmo do Paranaíba', '${state.id}'),
          ('${uuidV4()}', 'Carmo do Rio Claro', '${state.id}'),
          ('${uuidV4()}', 'Carmópolis de Minas', '${state.id}'),
          ('${uuidV4()}', 'Carneirinho', '${state.id}'),
          ('${uuidV4()}', 'Carrancas', '${state.id}'),
          ('${uuidV4()}', 'Carvalhópolis', '${state.id}'),
          ('${uuidV4()}', 'Carvalhos', '${state.id}'),
          ('${uuidV4()}', 'Casa Grande', '${state.id}'),
          ('${uuidV4()}', 'Cascalho Rico', '${state.id}'),
          ('${uuidV4()}', 'Cássia', '${state.id}'),
          ('${uuidV4()}', 'Cataguases', '${state.id}'),
          ('${uuidV4()}', 'Catas Altas', '${state.id}'),
          ('${uuidV4()}', 'Catas Altas da Noruega', '${state.id}'),
          ('${uuidV4()}', 'Catuji', '${state.id}'),
          ('${uuidV4()}', 'Catuti', '${state.id}'),
          ('${uuidV4()}', 'Caxambu', '${state.id}'),
          ('${uuidV4()}', 'Cedro do Abaeté', '${state.id}'),
          ('${uuidV4()}', 'Central de Minas', '${state.id}'),
          ('${uuidV4()}', 'Centralina', '${state.id}'),
          ('${uuidV4()}', 'Chácara', '${state.id}'),
          ('${uuidV4()}', 'Chalé', '${state.id}'),
          ('${uuidV4()}', 'Chapada do Norte', '${state.id}'),
          ('${uuidV4()}', 'Chapada Gaúcha', '${state.id}'),
          ('${uuidV4()}', 'Chiador', '${state.id}'),
          ('${uuidV4()}', 'Cipotânea', '${state.id}'),
          ('${uuidV4()}', 'Claraval', '${state.id}'),
          ('${uuidV4()}', 'Claro dos Poções', '${state.id}'),
          ('${uuidV4()}', 'Cláudio', '${state.id}'),
          ('${uuidV4()}', 'Coimbra', '${state.id}'),
          ('${uuidV4()}', 'Coluna', '${state.id}'),
          ('${uuidV4()}', 'Comendador Gomes', '${state.id}'),
          ('${uuidV4()}', 'Comercinho', '${state.id}'),
          ('${uuidV4()}', 'Conceição da Aparecida', '${state.id}'),
          ('${uuidV4()}', 'Conceição da Barra de Minas', '${state.id}'),
          ('${uuidV4()}', 'Conceição das Alagoas', '${state.id}'),
          ('${uuidV4()}', 'Conceição das Pedras', '${state.id}'),
          ('${uuidV4()}', 'Conceição de Ipanema', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Mato Dentro', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Pará', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Rio Verde', '${state.id}'),
          ('${uuidV4()}', 'Conceição dos Ouros', '${state.id}'),
          ('${uuidV4()}', 'Cônego Marinho', '${state.id}'),
          ('${uuidV4()}', 'Confins', '${state.id}'),
          ('${uuidV4()}', 'Congonhal', '${state.id}'),
          ('${uuidV4()}', 'Congonhas', '${state.id}'),
          ('${uuidV4()}', 'Congonhas do Norte', '${state.id}'),
          ('${uuidV4()}', 'Conquista', '${state.id}'),
          ('${uuidV4()}', 'Conselheiro Lafaiete', '${state.id}'),
          ('${uuidV4()}', 'Conselheiro Pena', '${state.id}'),
          ('${uuidV4()}', 'Consolação', '${state.id}'),
          ('${uuidV4()}', 'Contagem', '${state.id}'),
          ('${uuidV4()}', 'Coqueiral', '${state.id}'),
          ('${uuidV4()}', 'Coração de Jesus', '${state.id}'),
          ('${uuidV4()}', 'Cordisburgo', '${state.id}'),
          ('${uuidV4()}', 'Cordislândia', '${state.id}'),
          ('${uuidV4()}', 'Corinto', '${state.id}'),
          ('${uuidV4()}', 'Coroaci', '${state.id}'),
          ('${uuidV4()}', 'Coromandel', '${state.id}'),
          ('${uuidV4()}', 'Coronel Fabriciano', '${state.id}'),
          ('${uuidV4()}', 'Coronel Murta', '${state.id}'),
          ('${uuidV4()}', 'Coronel Pacheco', '${state.id}'),
          ('${uuidV4()}', 'Coronel Xavier Chaves', '${state.id}'),
          ('${uuidV4()}', 'Córrego Danta', '${state.id}'),
          ('${uuidV4()}', 'Córrego do Bom Jesus', '${state.id}'),
          ('${uuidV4()}', 'Córrego Fundo', '${state.id}'),
          ('${uuidV4()}', 'Córrego Novo', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
