import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "TO";

export class PopulateCityWithStateTO1640609600435
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Abreulândia', '${state.id}'),
          ('${uuidV4()}', 'Aguiarnópolis', '${state.id}'),
          ('${uuidV4()}', 'Aliança do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Almas', '${state.id}'),
          ('${uuidV4()}', 'Alvorada', '${state.id}'),
          ('${uuidV4()}', 'Ananás', '${state.id}'),
          ('${uuidV4()}', 'Angico', '${state.id}'),
          ('${uuidV4()}', 'Aparecida do Rio Negro', '${state.id}'),
          ('${uuidV4()}', 'Aragominas', '${state.id}'),
          ('${uuidV4()}', 'Araguacema', '${state.id}'),
          ('${uuidV4()}', 'Araguaçu', '${state.id}'),
          ('${uuidV4()}', 'Araguaína', '${state.id}'),
          ('${uuidV4()}', 'Araguanã', '${state.id}'),
          ('${uuidV4()}', 'Araguatins', '${state.id}'),
          ('${uuidV4()}', 'Arapoema', '${state.id}'),
          ('${uuidV4()}', 'Arraias', '${state.id}'),
          ('${uuidV4()}', 'Augustinópolis', '${state.id}'),
          ('${uuidV4()}', 'Aurora do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Axixá do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Babaçulândia', '${state.id}'),
          ('${uuidV4()}', 'Bandeirantes do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Barra do Ouro', '${state.id}'),
          ('${uuidV4()}', 'Barrolândia', '${state.id}'),
          ('${uuidV4()}', 'Bernardo Sayão', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Brasilândia do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Brejinho de Nazaré', '${state.id}'),
          ('${uuidV4()}', 'Buriti do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Cachoeirinha', '${state.id}'),
          ('${uuidV4()}', 'Campos Lindos', '${state.id}'),
          ('${uuidV4()}', 'Cariri do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Carmolândia', '${state.id}'),
          ('${uuidV4()}', 'Carrasco Bonito', '${state.id}'),
          ('${uuidV4()}', 'Caseara', '${state.id}'),
          ('${uuidV4()}', 'Centenário', '${state.id}'),
          ('${uuidV4()}', 'Chapada da Natividade', '${state.id}'),
          ('${uuidV4()}', 'Chapada de Areia', '${state.id}'),
          ('${uuidV4()}', 'Colinas do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Colméia', '${state.id}'),
          ('${uuidV4()}', 'Combinado', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Couto de Magalhães', '${state.id}'),
          ('${uuidV4()}', 'Cristalândia', '${state.id}'),
          ('${uuidV4()}', 'Crixás do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Darcinópolis', '${state.id}'),
          ('${uuidV4()}', 'Dianópolis', '${state.id}'),
          ('${uuidV4()}', 'Divinópolis do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Dois Irmãos do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Dueré', '${state.id}'),
          ('${uuidV4()}', 'Esperantina', '${state.id}'),
          ('${uuidV4()}', 'Fátima', '${state.id}'),
          ('${uuidV4()}', 'Figueirópolis', '${state.id}'),
          ('${uuidV4()}', 'Filadélfia', '${state.id}'),
          ('${uuidV4()}', 'Formoso do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Fortaleza do Tabocão', '${state.id}'),
          ('${uuidV4()}', 'Goianorte', '${state.id}'),
          ('${uuidV4()}', 'Goiatins', '${state.id}'),
          ('${uuidV4()}', 'Guaraí', '${state.id}'),
          ('${uuidV4()}', 'Gurupi', '${state.id}'),
          ('${uuidV4()}', 'Ipueiras', '${state.id}'),
          ('${uuidV4()}', 'Itacajá', '${state.id}'),
          ('${uuidV4()}', 'Itaguatins', '${state.id}'),
          ('${uuidV4()}', 'Itapiratins', '${state.id}'),
          ('${uuidV4()}', 'Itaporã do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Jaú do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Juarina', '${state.id}'),
          ('${uuidV4()}', 'Lagoa da Confusão', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Lajeado', '${state.id}'),
          ('${uuidV4()}', 'Lavandeira', '${state.id}'),
          ('${uuidV4()}', 'Lizarda', '${state.id}'),
          ('${uuidV4()}', 'Luzinópolis', '${state.id}'),
          ('${uuidV4()}', 'Marianópolis do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Mateiros', '${state.id}'),
          ('${uuidV4()}', 'Maurilândia do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Miracema do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Miranorte', '${state.id}'),
          ('${uuidV4()}', 'Monte do Carmo', '${state.id}'),
          ('${uuidV4()}', 'Monte Santo do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Muricilândia', '${state.id}'),
          ('${uuidV4()}', 'Natividade', '${state.id}'),
          ('${uuidV4()}', 'Nazaré', '${state.id}'),
          ('${uuidV4()}', 'Nova Olinda', '${state.id}'),
          ('${uuidV4()}', 'Nova Rosalândia', '${state.id}'),
          ('${uuidV4()}', 'Novo Acordo', '${state.id}'),
          ('${uuidV4()}', 'Novo Alegre', '${state.id}'),
          ('${uuidV4()}', 'Novo Jardim', '${state.id}'),
          ('${uuidV4()}', 'Oliveira de Fátima', '${state.id}'),
          ('${uuidV4()}', 'Palmas', '${state.id}'),
          ('${uuidV4()}', 'Palmeirante', '${state.id}'),
          ('${uuidV4()}', 'Palmeiras do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Palmeirópolis', '${state.id}'),
          ('${uuidV4()}', 'Paraíso do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Paranã', '${state.id}'),
          ('${uuidV4()}', 'Pau d´Arco', '${state.id}'),
          ('${uuidV4()}', 'Pedro Afonso', '${state.id}'),
          ('${uuidV4()}', 'Peixe', '${state.id}'),
          ('${uuidV4()}', 'Pequizeiro', '${state.id}'),
          ('${uuidV4()}', 'Pindorama do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Piraquê', '${state.id}'),
          ('${uuidV4()}', 'Pium', '${state.id}'),
          ('${uuidV4()}', 'Ponte Alta do Bom Jesus', '${state.id}'),
          ('${uuidV4()}', 'Ponte Alta do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Porto Alegre do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Porto Nacional', '${state.id}'),
          ('${uuidV4()}', 'Praia Norte', '${state.id}'),
          ('${uuidV4()}', 'Presidente Kennedy', '${state.id}'),
          ('${uuidV4()}', 'Pugmil', '${state.id}'),
          ('${uuidV4()}', 'Recursolândia', '${state.id}'),
          ('${uuidV4()}', 'Riachinho', '${state.id}'),
          ('${uuidV4()}', 'Rio da Conceição', '${state.id}'),
          ('${uuidV4()}', 'Rio dos Bois', '${state.id}'),
          ('${uuidV4()}', 'Rio Sono', '${state.id}'),
          ('${uuidV4()}', 'Sampaio', '${state.id}'),
          ('${uuidV4()}', 'Sandolândia', '${state.id}'),
          ('${uuidV4()}', 'Santa Fé do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Santa Maria do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Santa Rita do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Santa Rosa do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Santa Tereza do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Santa Terezinha do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'São Bento do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'São Félix do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'São Miguel do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'São Salvador do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'São Sebastião do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'São Valério da Natividade', '${state.id}'),
          ('${uuidV4()}', 'Silvanópolis', '${state.id}'),
          ('${uuidV4()}', 'Sítio Novo do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Sucupira', '${state.id}'),
          ('${uuidV4()}', 'Taguatinga', '${state.id}'),
          ('${uuidV4()}', 'Taipas do Tocantins', '${state.id}'),
          ('${uuidV4()}', 'Talismã', '${state.id}'),
          ('${uuidV4()}', 'Tocantínia', '${state.id}'),
          ('${uuidV4()}', 'Tocantinópolis', '${state.id}'),
          ('${uuidV4()}', 'Tupirama', '${state.id}'),
          ('${uuidV4()}', 'Tupiratins', '${state.id}'),
          ('${uuidV4()}', 'Wanderlândia', '${state.id}'),
          ('${uuidV4()}', 'Xambioá', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
