import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "PI";

export class PopulateCityWithStatePI1640609525012
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Acauã', '${state.id}'),
          ('${uuidV4()}', 'Agricolândia', '${state.id}'),
          ('${uuidV4()}', 'Água Branca', '${state.id}'),
          ('${uuidV4()}', 'Alagoinha do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Alegrete do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Alto Longá', '${state.id}'),
          ('${uuidV4()}', 'Altos', '${state.id}'),
          ('${uuidV4()}', 'Alvorada do Gurguéia', '${state.id}'),
          ('${uuidV4()}', 'Amarante', '${state.id}'),
          ('${uuidV4()}', 'Angical do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Anísio de Abreu', '${state.id}'),
          ('${uuidV4()}', 'Antônio Almeida', '${state.id}'),
          ('${uuidV4()}', 'Aroazes', '${state.id}'),
          ('${uuidV4()}', 'Aroeiras do Itaim', '${state.id}'),
          ('${uuidV4()}', 'Arraial', '${state.id}'),
          ('${uuidV4()}', 'Assunção do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Avelino Lopes', '${state.id}'),
          ('${uuidV4()}', 'Baixa Grande do Ribeiro', '${state.id}'),
          ('${uuidV4()}', 'Barra d´Alcântara', '${state.id}'),
          ('${uuidV4()}', 'Barras', '${state.id}'),
          ('${uuidV4()}', 'Barreiras do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Barro Duro', '${state.id}'),
          ('${uuidV4()}', 'Batalha', '${state.id}'),
          ('${uuidV4()}', 'Bela Vista do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Belém do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Beneditinos', '${state.id}'),
          ('${uuidV4()}', 'Bertolínia', '${state.id}'),
          ('${uuidV4()}', 'Betânia do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Boa Hora', '${state.id}'),
          ('${uuidV4()}', 'Bocaina', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus', '${state.id}'),
          ('${uuidV4()}', 'Bom Princípio do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Bonfim do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Boqueirão do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Brasileira', '${state.id}'),
          ('${uuidV4()}', 'Brejo do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Buriti dos Lopes', '${state.id}'),
          ('${uuidV4()}', 'Buriti dos Montes', '${state.id}'),
          ('${uuidV4()}', 'Cabeceiras do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Cajazeiras do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Cajueiro da Praia', '${state.id}'),
          ('${uuidV4()}', 'Caldeirão Grande do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Campinas do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Campo Alegre do Fidalgo', '${state.id}'),
          ('${uuidV4()}', 'Campo Grande do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Campo Largo do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Campo Maior', '${state.id}'),
          ('${uuidV4()}', 'Canavieira', '${state.id}'),
          ('${uuidV4()}', 'Canto do Buriti', '${state.id}'),
          ('${uuidV4()}', 'Capitão de Campos', '${state.id}'),
          ('${uuidV4()}', 'Capitão Gervásio Oliveira', '${state.id}'),
          ('${uuidV4()}', 'Caracol', '${state.id}'),
          ('${uuidV4()}', 'Caraúbas do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Caridade do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Castelo do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Caxingó', '${state.id}'),
          ('${uuidV4()}', 'Cocal', '${state.id}'),
          ('${uuidV4()}', 'Cocal de Telha', '${state.id}'),
          ('${uuidV4()}', 'Cocal dos Alves', '${state.id}'),
          ('${uuidV4()}', 'Coivaras', '${state.id}'),
          ('${uuidV4()}', 'Colônia do Gurguéia', '${state.id}'),
          ('${uuidV4()}', 'Colônia do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Canindé', '${state.id}'),
          ('${uuidV4()}', 'Coronel José Dias', '${state.id}'),
          ('${uuidV4()}', 'Corrente', '${state.id}'),
          ('${uuidV4()}', 'Cristalândia do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Cristino Castro', '${state.id}'),
          ('${uuidV4()}', 'Curimatá', '${state.id}'),
          ('${uuidV4()}', 'Currais', '${state.id}'),
          ('${uuidV4()}', 'Curral Novo do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Curralinhos', '${state.id}'),
          ('${uuidV4()}', 'Demerval Lobão', '${state.id}'),
          ('${uuidV4()}', 'Dirceu Arcoverde', '${state.id}'),
          ('${uuidV4()}', 'Dom Expedito Lopes', '${state.id}'),
          ('${uuidV4()}', 'Dom Inocêncio', '${state.id}'),
          ('${uuidV4()}', 'Domingos Mourão', '${state.id}'),
          ('${uuidV4()}', 'Elesbão Veloso', '${state.id}'),
          ('${uuidV4()}', 'Eliseu Martins', '${state.id}'),
          ('${uuidV4()}', 'Esperantina', '${state.id}'),
          ('${uuidV4()}', 'Fartura do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Flores do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Floresta do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Floriano', '${state.id}'),
          ('${uuidV4()}', 'Francinópolis', '${state.id}'),
          ('${uuidV4()}', 'Francisco Ayres', '${state.id}'),
          ('${uuidV4()}', 'Francisco Macedo', '${state.id}'),
          ('${uuidV4()}', 'Francisco Santos', '${state.id}'),
          ('${uuidV4()}', 'Fronteiras', '${state.id}'),
          ('${uuidV4()}', 'Geminiano', '${state.id}'),
          ('${uuidV4()}', 'Gilbués', '${state.id}'),
          ('${uuidV4()}', 'Guadalupe', '${state.id}'),
          ('${uuidV4()}', 'Guaribas', '${state.id}'),
          ('${uuidV4()}', 'Hugo Napoleão', '${state.id}'),
          ('${uuidV4()}', 'Ilha Grande', '${state.id}'),
          ('${uuidV4()}', 'Inhuma', '${state.id}'),
          ('${uuidV4()}', 'Ipiranga do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Isaías Coelho', '${state.id}'),
          ('${uuidV4()}', 'Itainópolis', '${state.id}'),
          ('${uuidV4()}', 'Itaueira', '${state.id}'),
          ('${uuidV4()}', 'Jacobina do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Jaicós', '${state.id}'),
          ('${uuidV4()}', 'Jardim do Mulato', '${state.id}'),
          ('${uuidV4()}', 'Jatobá do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Jerumenha', '${state.id}'),
          ('${uuidV4()}', 'João Costa', '${state.id}'),
          ('${uuidV4()}', 'Joaquim Pires', '${state.id}'),
          ('${uuidV4()}', 'Joca Marques', '${state.id}'),
          ('${uuidV4()}', 'José de Freitas', '${state.id}'),
          ('${uuidV4()}', 'Juazeiro do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Júlio Borges', '${state.id}'),
          ('${uuidV4()}', 'Jurema', '${state.id}'),
          ('${uuidV4()}', 'Lagoa Alegre', '${state.id}'),
          ('${uuidV4()}', 'Lagoa de São Francisco', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Barro do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Sítio', '${state.id}'),
          ('${uuidV4()}', 'Lagoinha do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Landri Sales', '${state.id}'),
          ('${uuidV4()}', 'Luís Correia', '${state.id}'),
          ('${uuidV4()}', 'Luzilândia', '${state.id}'),
          ('${uuidV4()}', 'Madeiro', '${state.id}'),
          ('${uuidV4()}', 'Manoel Emídio', '${state.id}'),
          ('${uuidV4()}', 'Marcolândia', '${state.id}'),
          ('${uuidV4()}', 'Marcos Parente', '${state.id}'),
          ('${uuidV4()}', 'Massapê do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Matias Olímpio', '${state.id}'),
          ('${uuidV4()}', 'Miguel Alves', '${state.id}'),
          ('${uuidV4()}', 'Miguel Leão', '${state.id}'),
          ('${uuidV4()}', 'Milton Brandão', '${state.id}'),
          ('${uuidV4()}', 'Monsenhor Gil', '${state.id}'),
          ('${uuidV4()}', 'Monsenhor Hipólito', '${state.id}'),
          ('${uuidV4()}', 'Monte Alegre do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Morro Cabeça no Tempo', '${state.id}'),
          ('${uuidV4()}', 'Morro do Chapéu do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Murici dos Portelas', '${state.id}'),
          ('${uuidV4()}', 'Nazaré do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Nossa Senhora de Nazaré', '${state.id}'),
          ('${uuidV4()}', 'Nossa Senhora dos Remédios', '${state.id}'),
          ('${uuidV4()}', 'Nova Santa Rita', '${state.id}'),
          ('${uuidV4()}', 'Novo Oriente do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Novo Santo Antônio', '${state.id}'),
          ('${uuidV4()}', 'Oeiras', '${state.id}'),
          ('${uuidV4()}', 'Olho d´Água do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Padre Marcos', '${state.id}'),
          ('${uuidV4()}', 'Paes Landim', '${state.id}'),
          ('${uuidV4()}', 'Pajeú do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Palmeira do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Palmeirais', '${state.id}'),
          ('${uuidV4()}', 'Paquetá', '${state.id}'),
          ('${uuidV4()}', 'Parnaguá', '${state.id}'),
          ('${uuidV4()}', 'Parnaíba', '${state.id}'),
          ('${uuidV4()}', 'Passagem Franca do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Patos do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Pau d´Arco do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Paulistana', '${state.id}'),
          ('${uuidV4()}', 'Pavussu', '${state.id}'),
          ('${uuidV4()}', 'Pedro II', '${state.id}'),
          ('${uuidV4()}', 'Pedro Laurentino', '${state.id}'),
          ('${uuidV4()}', 'Picos', '${state.id}'),
          ('${uuidV4()}', 'Pimenteiras', '${state.id}'),
          ('${uuidV4()}', 'Pio IX', '${state.id}'),
          ('${uuidV4()}', 'Piracuruca', '${state.id}'),
          ('${uuidV4()}', 'Piripiri', '${state.id}'),
          ('${uuidV4()}', 'Porto', '${state.id}'),
          ('${uuidV4()}', 'Porto Alegre do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Prata do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Queimada Nova', '${state.id}'),
          ('${uuidV4()}', 'Redenção do Gurguéia', '${state.id}'),
          ('${uuidV4()}', 'Regeneração', '${state.id}'),
          ('${uuidV4()}', 'Riacho Frio', '${state.id}'),
          ('${uuidV4()}', 'Ribeira do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Ribeiro Gonçalves', '${state.id}'),
          ('${uuidV4()}', 'Rio Grande do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz dos Milagres', '${state.id}'),
          ('${uuidV4()}', 'Santa Filomena', '${state.id}'),
          ('${uuidV4()}', 'Santa Luz', '${state.id}'),
          ('${uuidV4()}', 'Santa Rosa do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Santana do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio de Lisboa', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio dos Milagres', '${state.id}'),
          ('${uuidV4()}', 'Santo Inácio do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Braz do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Félix do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Francisco de Assis do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Francisco do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Gonçalo do Gurguéia', '${state.id}'),
          ('${uuidV4()}', 'São Gonçalo do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São João da Canabrava', '${state.id}'),
          ('${uuidV4()}', 'São João da Fronteira', '${state.id}'),
          ('${uuidV4()}', 'São João da Serra', '${state.id}'),
          ('${uuidV4()}', 'São João da Varjota', '${state.id}'),
          ('${uuidV4()}', 'São João do Arraial', '${state.id}'),
          ('${uuidV4()}', 'São João do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São José do Divino', '${state.id}'),
          ('${uuidV4()}', 'São José do Peixe', '${state.id}'),
          ('${uuidV4()}', 'São José do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Julião', '${state.id}'),
          ('${uuidV4()}', 'São Lourenço do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Luis do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Miguel da Baixa Grande', '${state.id}'),
          ('${uuidV4()}', 'São Miguel do Fidalgo', '${state.id}'),
          ('${uuidV4()}', 'São Miguel do Tapuio', '${state.id}'),
          ('${uuidV4()}', 'São Pedro do Piauí', '${state.id}'),
          ('${uuidV4()}', 'São Raimundo Nonato', '${state.id}'),
          ('${uuidV4()}', 'Sebastião Barros', '${state.id}'),
          ('${uuidV4()}', 'Sebastião Leal', '${state.id}'),
          ('${uuidV4()}', 'Sigefredo Pacheco', '${state.id}'),
          ('${uuidV4()}', 'Simões', '${state.id}'),
          ('${uuidV4()}', 'Simplício Mendes', '${state.id}'),
          ('${uuidV4()}', 'Socorro do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Sussuapara', '${state.id}'),
          ('${uuidV4()}', 'Tamboril do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Tanque do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Teresina', '${state.id}'),
          ('${uuidV4()}', 'União', '${state.id}'),
          ('${uuidV4()}', 'Uruçuí', '${state.id}'),
          ('${uuidV4()}', 'Valença do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Várzea Branca', '${state.id}'),
          ('${uuidV4()}', 'Várzea Grande', '${state.id}'),
          ('${uuidV4()}', 'Vera Mendes', '${state.id}'),
          ('${uuidV4()}', 'Vila Nova do Piauí', '${state.id}'),
          ('${uuidV4()}', 'Wall Ferraz', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
