import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "MT";

export class PopulateCityWithStateMT1640609447670
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Acorizal', '${state.id}'),
          ('${uuidV4()}', 'Água Boa', '${state.id}'),
          ('${uuidV4()}', 'Alta Floresta', '${state.id}'),
          ('${uuidV4()}', 'Alto Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Alto Boa Vista', '${state.id}'),
          ('${uuidV4()}', 'Alto Garças', '${state.id}'),
          ('${uuidV4()}', 'Alto Paraguai', '${state.id}'),
          ('${uuidV4()}', 'Alto Taquari', '${state.id}'),
          ('${uuidV4()}', 'Apiacás', '${state.id}'),
          ('${uuidV4()}', 'Araguaiana', '${state.id}'),
          ('${uuidV4()}', 'Araguainha', '${state.id}'),
          ('${uuidV4()}', 'Araputanga', '${state.id}'),
          ('${uuidV4()}', 'Arenápolis', '${state.id}'),
          ('${uuidV4()}', 'Aripuanã', '${state.id}'),
          ('${uuidV4()}', 'Barão de Melgaço', '${state.id}'),
          ('${uuidV4()}', 'Barra do Bugres', '${state.id}'),
          ('${uuidV4()}', 'Barra do Garças', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Brasnorte', '${state.id}'),
          ('${uuidV4()}', 'Cáceres', '${state.id}'),
          ('${uuidV4()}', 'Campinápolis', '${state.id}'),
          ('${uuidV4()}', 'Campo Novo do Parecis', '${state.id}'),
          ('${uuidV4()}', 'Campo Verde', '${state.id}'),
          ('${uuidV4()}', 'Campos de Júlio', '${state.id}'),
          ('${uuidV4()}', 'Canabrava do Norte', '${state.id}'),
          ('${uuidV4()}', 'Canarana', '${state.id}'),
          ('${uuidV4()}', 'Carlinda', '${state.id}'),
          ('${uuidV4()}', 'Castanheira', '${state.id}'),
          ('${uuidV4()}', 'Chapada dos Guimarães', '${state.id}'),
          ('${uuidV4()}', 'Cláudia', '${state.id}'),
          ('${uuidV4()}', 'Cocalinho', '${state.id}'),
          ('${uuidV4()}', 'Colíder', '${state.id}'),
          ('${uuidV4()}', 'Colniza', '${state.id}'),
          ('${uuidV4()}', 'Comodoro', '${state.id}'),
          ('${uuidV4()}', 'Confresa', '${state.id}'),
          ('${uuidV4()}', 'Conquista d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Cotriguaçu', '${state.id}'),
          ('${uuidV4()}', 'Cuiabá', '${state.id}'),
          ('${uuidV4()}', 'Curvelândia', '${state.id}'),
          ('${uuidV4()}', 'Curvelândia', '${state.id}'),
          ('${uuidV4()}', 'Denise', '${state.id}'),
          ('${uuidV4()}', 'Diamantino', '${state.id}'),
          ('${uuidV4()}', 'Dom Aquino', '${state.id}'),
          ('${uuidV4()}', 'Feliz Natal', '${state.id}'),
          ('${uuidV4()}', 'Figueirópolis d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Gaúcha do Norte', '${state.id}'),
          ('${uuidV4()}', 'General Carneiro', '${state.id}'),
          ('${uuidV4()}', 'Glória d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Guarantã do Norte', '${state.id}'),
          ('${uuidV4()}', 'Guiratinga', '${state.id}'),
          ('${uuidV4()}', 'Indiavaí', '${state.id}'),
          ('${uuidV4()}', 'Ipiranga do Norte', '${state.id}'),
          ('${uuidV4()}', 'Itanhangá', '${state.id}'),
          ('${uuidV4()}', 'Itaúba', '${state.id}'),
          ('${uuidV4()}', 'Itiquira', '${state.id}'),
          ('${uuidV4()}', 'Jaciara', '${state.id}'),
          ('${uuidV4()}', 'Jangada', '${state.id}'),
          ('${uuidV4()}', 'Jauru', '${state.id}'),
          ('${uuidV4()}', 'Juara', '${state.id}'),
          ('${uuidV4()}', 'Juína', '${state.id}'),
          ('${uuidV4()}', 'Juruena', '${state.id}'),
          ('${uuidV4()}', 'Juscimeira', '${state.id}'),
          ('${uuidV4()}', 'Lambari d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Lucas do Rio Verde', '${state.id}'),
          ('${uuidV4()}', 'Luciára', '${state.id}'),
          ('${uuidV4()}', 'Marcelândia', '${state.id}'),
          ('${uuidV4()}', 'Matupá', '${state.id}'),
          ('${uuidV4()}', 'Mirassol d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Nobres', '${state.id}'),
          ('${uuidV4()}', 'Nortelândia', '${state.id}'),
          ('${uuidV4()}', 'Nossa Senhora do Livramento', '${state.id}'),
          ('${uuidV4()}', 'Nova Bandeirantes', '${state.id}'),
          ('${uuidV4()}', 'Nova Brasilândia', '${state.id}'),
          ('${uuidV4()}', 'Nova Canaã do Norte', '${state.id}'),
          ('${uuidV4()}', 'Nova Guarita', '${state.id}'),
          ('${uuidV4()}', 'Nova Lacerda', '${state.id}'),
          ('${uuidV4()}', 'Nova Marilândia', '${state.id}'),
          ('${uuidV4()}', 'Nova Maringá', '${state.id}'),
          ('${uuidV4()}', 'Nova Monte verde', '${state.id}'),
          ('${uuidV4()}', 'Nova Mutum', '${state.id}'),
          ('${uuidV4()}', 'Nova Olímpia', '${state.id}'),
          ('${uuidV4()}', 'Nova Santa Helena', '${state.id}'),
          ('${uuidV4()}', 'Nova Ubiratã', '${state.id}'),
          ('${uuidV4()}', 'Nova Xavantina', '${state.id}'),
          ('${uuidV4()}', 'Novo Horizonte do Norte', '${state.id}'),
          ('${uuidV4()}', 'Novo Mundo', '${state.id}'),
          ('${uuidV4()}', 'Novo Santo Antônio', '${state.id}'),
          ('${uuidV4()}', 'Novo São Joaquim', '${state.id}'),
          ('${uuidV4()}', 'Paranaíta', '${state.id}'),
          ('${uuidV4()}', 'Paranatinga', '${state.id}'),
          ('${uuidV4()}', 'Pedra Preta', '${state.id}'),
          ('${uuidV4()}', 'Peixoto de Azevedo', '${state.id}'),
          ('${uuidV4()}', 'Planalto da Serra', '${state.id}'),
          ('${uuidV4()}', 'Poconé', '${state.id}'),
          ('${uuidV4()}', 'Pontal do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'Ponte Branca', '${state.id}'),
          ('${uuidV4()}', 'Pontes e Lacerda', '${state.id}'),
          ('${uuidV4()}', 'Porto Alegre do Norte', '${state.id}'),
          ('${uuidV4()}', 'Porto dos Gaúchos', '${state.id}'),
          ('${uuidV4()}', 'Porto Esperidião', '${state.id}'),
          ('${uuidV4()}', 'Porto Estrela', '${state.id}'),
          ('${uuidV4()}', 'Poxoréo', '${state.id}'),
          ('${uuidV4()}', 'Primavera do Leste', '${state.id}'),
          ('${uuidV4()}', 'Querência', '${state.id}'),
          ('${uuidV4()}', 'Reserva do Cabaçal', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Cascalheira', '${state.id}'),
          ('${uuidV4()}', 'Ribeirãozinho', '${state.id}'),
          ('${uuidV4()}', 'Rio Branco', '${state.id}'),
          ('${uuidV4()}', 'Rondolândia', '${state.id}'),
          ('${uuidV4()}', 'Rondonópolis', '${state.id}'),
          ('${uuidV4()}', 'Rosário Oeste', '${state.id}'),
          ('${uuidV4()}', 'Salto do Céu', '${state.id}'),
          ('${uuidV4()}', 'Santa Carmem', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz do Xingu', '${state.id}'),
          ('${uuidV4()}', 'Santa Rita do Trivelato', '${state.id}'),
          ('${uuidV4()}', 'Santa Terezinha', '${state.id}'),
          ('${uuidV4()}', 'Santo Afonso', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Leste', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Leverger', '${state.id}'),
          ('${uuidV4()}', 'São Félix do Araguaia', '${state.id}'),
          ('${uuidV4()}', 'São José do Povo', '${state.id}'),
          ('${uuidV4()}', 'São José do Rio Claro', '${state.id}'),
          ('${uuidV4()}', 'São José do Xingu', '${state.id}'),
          ('${uuidV4()}', 'São José dos Quatro Marcos', '${state.id}'),
          ('${uuidV4()}', 'São Pedro da Cipa', '${state.id}'),
          ('${uuidV4()}', 'Sapezal', '${state.id}'),
          ('${uuidV4()}', 'Serra Nova Dourada', '${state.id}'),
          ('${uuidV4()}', 'Sinop', '${state.id}'),
          ('${uuidV4()}', 'Sorriso', '${state.id}'),
          ('${uuidV4()}', 'Tabaporã', '${state.id}'),
          ('${uuidV4()}', 'Tangará da Serra', '${state.id}'),
          ('${uuidV4()}', 'Tapurah', '${state.id}'),
          ('${uuidV4()}', 'Terra Nova do Norte', '${state.id}'),
          ('${uuidV4()}', 'Tesouro', '${state.id}'),
          ('${uuidV4()}', 'Torixoréu', '${state.id}'),
          ('${uuidV4()}', 'União do Sul', '${state.id}'),
          ('${uuidV4()}', 'Vale de São Domingos', '${state.id}'),
          ('${uuidV4()}', 'Várzea Grande', '${state.id}'),
          ('${uuidV4()}', 'Vera', '${state.id}'),
          ('${uuidV4()}', 'Vila Bela da Santíssima Trindade', '${state.id}'),
          ('${uuidV4()}', 'Vila Rica', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
