import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "PR";

export class PopulateCityWithStatePRPart21640629653133
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Maripá', '${state.id}'),
          ('${uuidV4()}', 'Marmeleiro', '${state.id}'),
          ('${uuidV4()}', 'Marquinho', '${state.id}'),
          ('${uuidV4()}', 'Marumbi', '${state.id}'),
          ('${uuidV4()}', 'Matelândia', '${state.id}'),
          ('${uuidV4()}', 'Matinhos', '${state.id}'),
          ('${uuidV4()}', 'Mato Rico', '${state.id}'),
          ('${uuidV4()}', 'Mauá da Serra', '${state.id}'),
          ('${uuidV4()}', 'Medianeira', '${state.id}'),
          ('${uuidV4()}', 'Mercedes', '${state.id}'),
          ('${uuidV4()}', 'Mirador', '${state.id}'),
          ('${uuidV4()}', 'Miraselva', '${state.id}'),
          ('${uuidV4()}', 'Missal', '${state.id}'),
          ('${uuidV4()}', 'Moreira Sales', '${state.id}'),
          ('${uuidV4()}', 'Morretes', '${state.id}'),
          ('${uuidV4()}', 'Munhoz de Melo', '${state.id}'),
          ('${uuidV4()}', 'Nossa Senhora das Graças', '${state.id}'),
          ('${uuidV4()}', 'Nova Aliança do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'Nova América da Colina', '${state.id}'),
          ('${uuidV4()}', 'Nova Aurora', '${state.id}'),
          ('${uuidV4()}', 'Nova Cantu', '${state.id}'),
          ('${uuidV4()}', 'Nova Esperança', '${state.id}'),
          ('${uuidV4()}', 'Nova Esperança do Sudoeste', '${state.id}'),
          ('${uuidV4()}', 'Nova Fátima', '${state.id}'),
          ('${uuidV4()}', 'Nova Laranjeiras', '${state.id}'),
          ('${uuidV4()}', 'Nova Londrina', '${state.id}'),
          ('${uuidV4()}', 'Nova Olímpia', '${state.id}'),
          ('${uuidV4()}', 'Nova Prata do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Nova Santa Bárbara', '${state.id}'),
          ('${uuidV4()}', 'Nova Santa Rosa', '${state.id}'),
          ('${uuidV4()}', 'Nova Tebas', '${state.id}'),
          ('${uuidV4()}', 'Novo Itacolomi', '${state.id}'),
          ('${uuidV4()}', 'Ortigueira', '${state.id}'),
          ('${uuidV4()}', 'Ourizona', '${state.id}'),
          ('${uuidV4()}', 'Ouro Verde do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Paiçandu', '${state.id}'),
          ('${uuidV4()}', 'Palmas', '${state.id}'),
          ('${uuidV4()}', 'Palmeira', '${state.id}'),
          ('${uuidV4()}', 'Palmital', '${state.id}'),
          ('${uuidV4()}', 'Palotina', '${state.id}'),
          ('${uuidV4()}', 'Paraíso do Norte', '${state.id}'),
          ('${uuidV4()}', 'Paranacity', '${state.id}'),
          ('${uuidV4()}', 'Paranaguá', '${state.id}'),
          ('${uuidV4()}', 'Paranapoema', '${state.id}'),
          ('${uuidV4()}', 'Paranavaí', '${state.id}'),
          ('${uuidV4()}', 'Pato Bragado', '${state.id}'),
          ('${uuidV4()}', 'Pato Branco', '${state.id}'),
          ('${uuidV4()}', 'Paula Freitas', '${state.id}'),
          ('${uuidV4()}', 'Paulo Frontin', '${state.id}'),
          ('${uuidV4()}', 'Peabiru', '${state.id}'),
          ('${uuidV4()}', 'Perobal', '${state.id}'),
          ('${uuidV4()}', 'Pérola', '${state.id}'),
          ('${uuidV4()}', 'Pérola d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Piên', '${state.id}'),
          ('${uuidV4()}', 'Pinhais', '${state.id}'),
          ('${uuidV4()}', 'Pinhal de São Bento', '${state.id}'),
          ('${uuidV4()}', 'Pinhalão', '${state.id}'),
          ('${uuidV4()}', 'Pinhão', '${state.id}'),
          ('${uuidV4()}', 'Piraí do Sul', '${state.id}'),
          ('${uuidV4()}', 'Piraquara', '${state.id}'),
          ('${uuidV4()}', 'Pitanga', '${state.id}'),
          ('${uuidV4()}', 'Pitangueiras', '${state.id}'),
          ('${uuidV4()}', 'Planaltina do Paraná', '${state.id}'),
          ('${uuidV4()}', 'Planalto', '${state.id}'),
          ('${uuidV4()}', 'Ponta Grossa', '${state.id}'),
          ('${uuidV4()}', 'Pontal do Paraná', '${state.id}'),
          ('${uuidV4()}', 'Porecatu', '${state.id}'),
          ('${uuidV4()}', 'Porto Amazonas', '${state.id}'),
          ('${uuidV4()}', 'Porto Barreiro', '${state.id}'),
          ('${uuidV4()}', 'Porto Rico', '${state.id}'),
          ('${uuidV4()}', 'Porto Vitória', '${state.id}'),
          ('${uuidV4()}', 'Prado Ferreira', '${state.id}'),
          ('${uuidV4()}', 'Pranchita', '${state.id}'),
          ('${uuidV4()}', 'Presidente Castelo Branco', '${state.id}'),
          ('${uuidV4()}', 'Primeiro de Maio', '${state.id}'),
          ('${uuidV4()}', 'Prudentópolis', '${state.id}'),
          ('${uuidV4()}', 'Quarto Centenário', '${state.id}'),
          ('${uuidV4()}', 'Quatiguá', '${state.id}'),
          ('${uuidV4()}', 'Quatro Barras', '${state.id}'),
          ('${uuidV4()}', 'Quatro Pontes', '${state.id}'),
          ('${uuidV4()}', 'Quedas do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Querência do Norte', '${state.id}'),
          ('${uuidV4()}', 'Quinta do Sol', '${state.id}'),
          ('${uuidV4()}', 'Quitandinha', '${state.id}'),
          ('${uuidV4()}', 'Ramilândia', '${state.id}'),
          ('${uuidV4()}', 'Rancho Alegre', '${state.id}'),
          ('${uuidV4()}', 'Rancho Alegre d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Realeza', '${state.id}'),
          ('${uuidV4()}', 'Rebouças', '${state.id}'),
          ('${uuidV4()}', 'Renascença', '${state.id}'),
          ('${uuidV4()}', 'Reserva', '${state.id}'),
          ('${uuidV4()}', 'Reserva do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão Claro', '${state.id}'),
          ('${uuidV4()}', 'Ribeirão do Pinhal', '${state.id}'),
          ('${uuidV4()}', 'Rio Azul', '${state.id}'),
          ('${uuidV4()}', 'Rio Bom', '${state.id}'),
          ('${uuidV4()}', 'Rio Bonito do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Rio Branco do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'Rio Branco do Sul', '${state.id}'),
          ('${uuidV4()}', 'Rio Negro', '${state.id}'),
          ('${uuidV4()}', 'Rolândia', '${state.id}'),
          ('${uuidV4()}', 'Roncador', '${state.id}'),
          ('${uuidV4()}', 'Rondon', '${state.id}'),
          ('${uuidV4()}', 'Rosário do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'Sabáudia', '${state.id}'),
          ('${uuidV4()}', 'Salgado Filho', '${state.id}'),
          ('${uuidV4()}', 'Salto do Itararé', '${state.id}'),
          ('${uuidV4()}', 'Salto do Lontra', '${state.id}'),
          ('${uuidV4()}', 'Santa Amélia', '${state.id}'),
          ('${uuidV4()}', 'Santa Cecília do Pavão', '${state.id}'),
          ('${uuidV4()}', 'Santa Cruz de Monte Castelo', '${state.id}'),
          ('${uuidV4()}', 'Santa Fé', '${state.id}'),
          ('${uuidV4()}', 'Santa Helena', '${state.id}'),
          ('${uuidV4()}', 'Santa Inês', '${state.id}'),
          ('${uuidV4()}', 'Santa Isabel do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'Santa Izabel do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Santa Lúcia', '${state.id}'),
          ('${uuidV4()}', 'Santa Maria do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Santa Mariana', '${state.id}'),
          ('${uuidV4()}', 'Santa Mônica', '${state.id}'),
          ('${uuidV4()}', 'Santa Tereza do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Santa Terezinha de Itaipu', '${state.id}'),
          ('${uuidV4()}', 'Santana do Itararé', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio da Platina', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Caiuá', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Paraíso', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio do Sudoeste', '${state.id}'),
          ('${uuidV4()}', 'Santo Inácio', '${state.id}'),
          ('${uuidV4()}', 'São Carlos do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'São Jerônimo da Serra', '${state.id}'),
          ('${uuidV4()}', 'São João', '${state.id}'),
          ('${uuidV4()}', 'São João do Caiuá', '${state.id}'),
          ('${uuidV4()}', 'São João do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'São João do Triunfo', '${state.id}'),
          ('${uuidV4()}', 'São Jorge d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'São Jorge do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'São Jorge do Patrocínio', '${state.id}'),
          ('${uuidV4()}', 'São José da Boa Vista', '${state.id}'),
          ('${uuidV4()}', 'São José das Palmeiras', '${state.id}'),
          ('${uuidV4()}', 'São José dos Pinhais', '${state.id}'),
          ('${uuidV4()}', 'São Manoel do Paraná', '${state.id}'),
          ('${uuidV4()}', 'São Mateus do Sul', '${state.id}'),
          ('${uuidV4()}', 'São Miguel do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'São Pedro do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'São Pedro do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'São Pedro do Paraná', '${state.id}'),
          ('${uuidV4()}', 'São Sebastião da Amoreira', '${state.id}'),
          ('${uuidV4()}', 'São Tomé', '${state.id}'),
          ('${uuidV4()}', 'Sapopema', '${state.id}'),
          ('${uuidV4()}', 'Sarandi', '${state.id}'),
          ('${uuidV4()}', 'Saudade do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Sengés', '${state.id}'),
          ('${uuidV4()}', 'Serranópolis do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Sertaneja', '${state.id}'),
          ('${uuidV4()}', 'Sertanópolis', '${state.id}'),
          ('${uuidV4()}', 'Siqueira Campos', '${state.id}'),
          ('${uuidV4()}', 'Sulina', '${state.id}'),
          ('${uuidV4()}', 'Tamarana', '${state.id}'),
          ('${uuidV4()}', 'Tamboara', '${state.id}'),
          ('${uuidV4()}', 'Tapejara', '${state.id}'),
          ('${uuidV4()}', 'Tapira', '${state.id}'),
          ('${uuidV4()}', 'Teixeira Soares', '${state.id}'),
          ('${uuidV4()}', 'Telêmaco Borba', '${state.id}'),
          ('${uuidV4()}', 'Terra Boa', '${state.id}'),
          ('${uuidV4()}', 'Terra Rica', '${state.id}'),
          ('${uuidV4()}', 'Terra Roxa', '${state.id}'),
          ('${uuidV4()}', 'Tibagi', '${state.id}'),
          ('${uuidV4()}', 'Tijucas do Sul', '${state.id}'),
          ('${uuidV4()}', 'Toledo', '${state.id}'),
          ('${uuidV4()}', 'Tomazina', '${state.id}'),
          ('${uuidV4()}', 'Três Barras do Paraná', '${state.id}'),
          ('${uuidV4()}', 'Tunas do Paraná', '${state.id}'),
          ('${uuidV4()}', 'Tuneiras do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Tupãssi', '${state.id}'),
          ('${uuidV4()}', 'Turvo', '${state.id}'),
          ('${uuidV4()}', 'Ubiratã', '${state.id}'),
          ('${uuidV4()}', 'Umuarama', '${state.id}'),
          ('${uuidV4()}', 'União da Vitória', '${state.id}'),
          ('${uuidV4()}', 'Uniflor', '${state.id}'),
          ('${uuidV4()}', 'Uraí', '${state.id}'),
          ('${uuidV4()}', 'Ventania', '${state.id}'),
          ('${uuidV4()}', 'Vera Cruz do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Verê', '${state.id}'),
          ('${uuidV4()}', 'Virmond', '${state.id}'),
          ('${uuidV4()}', 'Vitorino', '${state.id}'),
          ('${uuidV4()}', 'Wenceslau Braz', '${state.id}'),
          ('${uuidV4()}', 'Xambrê', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
