import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "PR";

export class PopulateCityWithStatePR1640609509706
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Abatiá', '${state.id}'),
          ('${uuidV4()}', 'Adrianópolis', '${state.id}'),
          ('${uuidV4()}', 'Agudos do Sul', '${state.id}'),
          ('${uuidV4()}', 'Almirante Tamandaré', '${state.id}'),
          ('${uuidV4()}', 'Altamira do Paraná', '${state.id}'),
          ('${uuidV4()}', 'Alto Paraíso', '${state.id}'),
          ('${uuidV4()}', 'Alto Paraná', '${state.id}'),
          ('${uuidV4()}', 'Alto Piquiri', '${state.id}'),
          ('${uuidV4()}', 'Altônia', '${state.id}'),
          ('${uuidV4()}', 'Alvorada do Sul', '${state.id}'),
          ('${uuidV4()}', 'Amaporã', '${state.id}'),
          ('${uuidV4()}', 'Ampére', '${state.id}'),
          ('${uuidV4()}', 'Anahy', '${state.id}'),
          ('${uuidV4()}', 'Andirá', '${state.id}'),
          ('${uuidV4()}', 'Ângulo', '${state.id}'),
          ('${uuidV4()}', 'Antonina', '${state.id}'),
          ('${uuidV4()}', 'Antônio Olinto', '${state.id}'),
          ('${uuidV4()}', 'Apucarana', '${state.id}'),
          ('${uuidV4()}', 'Arapongas', '${state.id}'),
          ('${uuidV4()}', 'Arapoti', '${state.id}'),
          ('${uuidV4()}', 'Arapuã', '${state.id}'),
          ('${uuidV4()}', 'Araruna', '${state.id}'),
          ('${uuidV4()}', 'Araucária', '${state.id}'),
          ('${uuidV4()}', 'Ariranha do Ivaí', '${state.id}'),
          ('${uuidV4()}', 'Assaí', '${state.id}'),
          ('${uuidV4()}', 'Assis Chateaubriand', '${state.id}'),
          ('${uuidV4()}', 'Astorga', '${state.id}'),
          ('${uuidV4()}', 'Atalaia', '${state.id}'),
          ('${uuidV4()}', 'Balsa Nova', '${state.id}'),
          ('${uuidV4()}', 'Bandeirantes', '${state.id}'),
          ('${uuidV4()}', 'Barbosa Ferraz', '${state.id}'),
          ('${uuidV4()}', 'Barra do Jacaré', '${state.id}'),
          ('${uuidV4()}', 'Barracão', '${state.id}'),
          ('${uuidV4()}', 'Bela Vista da Caroba', '${state.id}'),
          ('${uuidV4()}', 'Bela Vista do Paraíso', '${state.id}'),
          ('${uuidV4()}', 'Bituruna', '${state.id}'),
          ('${uuidV4()}', 'Boa Esperança', '${state.id}'),
          ('${uuidV4()}', 'Boa Esperança do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Boa Ventura de São Roque', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista da Aparecida', '${state.id}'),
          ('${uuidV4()}', 'Bocaiúva do Sul', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus do Sul', '${state.id}'),
          ('${uuidV4()}', 'Bom Sucesso', '${state.id}'),
          ('${uuidV4()}', 'Bom Sucesso do Sul', '${state.id}'),
          ('${uuidV4()}', 'Borrazópolis', '${state.id}'),
          ('${uuidV4()}', 'Braganey', '${state.id}'),
          ('${uuidV4()}', 'Brasilândia do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cafeara', '${state.id}'),
          ('${uuidV4()}', 'Cafelândia', '${state.id}'),
          ('${uuidV4()}', 'Cafezal do Sul', '${state.id}'),
          ('${uuidV4()}', 'Califórnia', '${state.id}'),
          ('${uuidV4()}', 'Cambará', '${state.id}'),
          ('${uuidV4()}', 'Cambé', '${state.id}'),
          ('${uuidV4()}', 'Cambira', '${state.id}'),
          ('${uuidV4()}', 'Campina da Lagoa', '${state.id}'),
          ('${uuidV4()}', 'Campina do Simão', '${state.id}'),
          ('${uuidV4()}', 'Campina Grande do Sul', '${state.id}'),
          ('${uuidV4()}', 'Campo Bonito', '${state.id}'),
          ('${uuidV4()}', 'Campo do Tenente', '${state.id}'),
          ('${uuidV4()}', 'Campo Largo', '${state.id}'),
          ('${uuidV4()}', 'Campo Magro', '${state.id}'),
          ('${uuidV4()}', 'Campo Mourão', '${state.id}'),
          ('${uuidV4()}', 'Cândido de Abreu', '${state.id}'),
          ('${uuidV4()}', 'Candói', '${state.id}'),
          ('${uuidV4()}', 'Cantagalo', '${state.id}'),
          ('${uuidV4()}', 'Capanema', '${state.id}'),
          ('${uuidV4()}', 'Capitão Leônidas Marques', '${state.id}'),
          ('${uuidV4()}', 'Carambeí', '${state.id}'),
          ('${uuidV4()}', 'Carlópolis', '${state.id}'),
          ('${uuidV4()}', 'Cascavel', '${state.id}'),
          ('${uuidV4()}', 'Castro', '${state.id}'),
          ('${uuidV4()}', 'Catanduvas', '${state.id}'),
          ('${uuidV4()}', 'Centenário do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cerro Azul', '${state.id}'),
          ('${uuidV4()}', 'Céu Azul', '${state.id}'),
          ('${uuidV4()}', 'Chopinzinho', '${state.id}'),
          ('${uuidV4()}', 'Cianorte', '${state.id}'),
          ('${uuidV4()}', 'Cidade Gaúcha', '${state.id}'),
          ('${uuidV4()}', 'Clevelândia', '${state.id}'),
          ('${uuidV4()}', 'Colombo', '${state.id}'),
          ('${uuidV4()}', 'Colorado', '${state.id}'),
          ('${uuidV4()}', 'Congonhinhas', '${state.id}'),
          ('${uuidV4()}', 'Conselheiro Mairinck', '${state.id}'),
          ('${uuidV4()}', 'Contenda', '${state.id}'),
          ('${uuidV4()}', 'Corbélia', '${state.id}'),
          ('${uuidV4()}', 'Cornélio Procópio', '${state.id}'),
          ('${uuidV4()}', 'Coronel Domingos Soares', '${state.id}'),
          ('${uuidV4()}', 'Coronel Vivida', '${state.id}'),
          ('${uuidV4()}', 'Corumbataí do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cruz Machado', '${state.id}'),
          ('${uuidV4()}', 'Cruzeiro do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Cruzeiro do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Cruzeiro do Sul', '${state.id}'),
          ('${uuidV4()}', 'Cruzmaltina', '${state.id}'),
          ('${uuidV4()}', 'Curitiba', '${state.id}'),
          ('${uuidV4()}', 'Curiúva', '${state.id}'),
          ('${uuidV4()}', 'Diamante d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Diamante do Norte', '${state.id}'),
          ('${uuidV4()}', 'Diamante do Sul', '${state.id}'),
          ('${uuidV4()}', 'Dois Vizinhos', '${state.id}'),
          ('${uuidV4()}', 'Douradina', '${state.id}'),
          ('${uuidV4()}', 'Doutor Camargo', '${state.id}'),
          ('${uuidV4()}', 'Doutor Ulysses', '${state.id}'),
          ('${uuidV4()}', 'Enéas Marques', '${state.id}'),
          ('${uuidV4()}', 'Engenheiro Beltrão', '${state.id}'),
          ('${uuidV4()}', 'Entre Rios do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Esperança Nova', '${state.id}'),
          ('${uuidV4()}', 'Espigão Alto do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Farol', '${state.id}'),
          ('${uuidV4()}', 'Faxinal', '${state.id}'),
          ('${uuidV4()}', 'Fazenda Rio Grande', '${state.id}'),
          ('${uuidV4()}', 'Fênix', '${state.id}'),
          ('${uuidV4()}', 'Fernandes Pinheiro', '${state.id}'),
          ('${uuidV4()}', 'Figueira', '${state.id}'),
          ('${uuidV4()}', 'Flor da Serra do Sul', '${state.id}'),
          ('${uuidV4()}', 'Floraí', '${state.id}'),
          ('${uuidV4()}', 'Floresta', '${state.id}'),
          ('${uuidV4()}', 'Florestópolis', '${state.id}'),
          ('${uuidV4()}', 'Flórida', '${state.id}'),
          ('${uuidV4()}', 'Formosa do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Foz do Iguaçu', '${state.id}'),
          ('${uuidV4()}', 'Foz do Jordão', '${state.id}'),
          ('${uuidV4()}', 'Francisco Alves', '${state.id}'),
          ('${uuidV4()}', 'Francisco Beltrão', '${state.id}'),
          ('${uuidV4()}', 'General Carneiro', '${state.id}'),
          ('${uuidV4()}', 'Godoy Moreira', '${state.id}'),
          ('${uuidV4()}', 'Goioerê', '${state.id}'),
          ('${uuidV4()}', 'Goioxim', '${state.id}'),
          ('${uuidV4()}', 'Grandes Rios', '${state.id}'),
          ('${uuidV4()}', 'Guaíra', '${state.id}'),
          ('${uuidV4()}', 'Guairaçá', '${state.id}'),
          ('${uuidV4()}', 'Guamiranga', '${state.id}'),
          ('${uuidV4()}', 'Guapirama', '${state.id}'),
          ('${uuidV4()}', 'Guaporema', '${state.id}'),
          ('${uuidV4()}', 'Guaraci', '${state.id}'),
          ('${uuidV4()}', 'Guaraniaçu', '${state.id}'),
          ('${uuidV4()}', 'Guarapuava', '${state.id}'),
          ('${uuidV4()}', 'Guaraqueçaba', '${state.id}'),
          ('${uuidV4()}', 'Guaratuba', '${state.id}'),
          ('${uuidV4()}', 'Honório Serpa', '${state.id}'),
          ('${uuidV4()}', 'Ibaiti', '${state.id}'),
          ('${uuidV4()}', 'Ibema', '${state.id}'),
          ('${uuidV4()}', 'Ibiporã', '${state.id}'),
          ('${uuidV4()}', 'Icaraíma', '${state.id}'),
          ('${uuidV4()}', 'Iguaraçu', '${state.id}'),
          ('${uuidV4()}', 'Iguatu', '${state.id}'),
          ('${uuidV4()}', 'Imbaú', '${state.id}'),
          ('${uuidV4()}', 'Imbituva', '${state.id}'),
          ('${uuidV4()}', 'Inácio Martins', '${state.id}'),
          ('${uuidV4()}', 'Inajá', '${state.id}'),
          ('${uuidV4()}', 'Indianópolis', '${state.id}'),
          ('${uuidV4()}', 'Ipiranga', '${state.id}'),
          ('${uuidV4()}', 'Iporã', '${state.id}'),
          ('${uuidV4()}', 'Iracema do Oeste', '${state.id}'),
          ('${uuidV4()}', 'Irati', '${state.id}'),
          ('${uuidV4()}', 'Iretama', '${state.id}'),
          ('${uuidV4()}', 'Itaguajé', '${state.id}'),
          ('${uuidV4()}', 'Itaipulândia', '${state.id}'),
          ('${uuidV4()}', 'Itambaracá', '${state.id}'),
          ('${uuidV4()}', 'Itambé', '${state.id}'),
          ('${uuidV4()}', 'Itapejara d´Oeste', '${state.id}'),
          ('${uuidV4()}', 'Itaperuçu', '${state.id}'),
          ('${uuidV4()}', 'Itaúna do Sul', '${state.id}'),
          ('${uuidV4()}', 'Ivaí', '${state.id}'),
          ('${uuidV4()}', 'Ivaiporã', '${state.id}'),
          ('${uuidV4()}', 'Ivaté', '${state.id}'),
          ('${uuidV4()}', 'Ivatuba', '${state.id}'),
          ('${uuidV4()}', 'Jaboti', '${state.id}'),
          ('${uuidV4()}', 'Jacarezinho', '${state.id}'),
          ('${uuidV4()}', 'Jaguapitã', '${state.id}'),
          ('${uuidV4()}', 'Jaguariaíva', '${state.id}'),
          ('${uuidV4()}', 'Jandaia do Sul', '${state.id}'),
          ('${uuidV4()}', 'Janiópolis', '${state.id}'),
          ('${uuidV4()}', 'Japira', '${state.id}'),
          ('${uuidV4()}', 'Japurá', '${state.id}'),
          ('${uuidV4()}', 'Jardim Alegre', '${state.id}'),
          ('${uuidV4()}', 'Jardim Olinda', '${state.id}'),
          ('${uuidV4()}', 'Jataizinho', '${state.id}'),
          ('${uuidV4()}', 'Jesuítas', '${state.id}'),
          ('${uuidV4()}', 'Joaquim Távora', '${state.id}'),
          ('${uuidV4()}', 'Jundiaí do Sul', '${state.id}'),
          ('${uuidV4()}', 'Juranda', '${state.id}'),
          ('${uuidV4()}', 'Jussara', '${state.id}'),
          ('${uuidV4()}', 'Kaloré', '${state.id}'),
          ('${uuidV4()}', 'Lapa', '${state.id}'),
          ('${uuidV4()}', 'Laranjal', '${state.id}'),
          ('${uuidV4()}', 'Laranjeiras do Sul', '${state.id}'),
          ('${uuidV4()}', 'Leópolis', '${state.id}'),
          ('${uuidV4()}', 'Lidianópolis', '${state.id}'),
          ('${uuidV4()}', 'Lindoeste', '${state.id}'),
          ('${uuidV4()}', 'Loanda', '${state.id}'),
          ('${uuidV4()}', 'Lobato', '${state.id}'),
          ('${uuidV4()}', 'Londrina', '${state.id}'),
          ('${uuidV4()}', 'Luiziana', '${state.id}'),
          ('${uuidV4()}', 'Lunardelli', '${state.id}'),
          ('${uuidV4()}', 'Lupionópolis', '${state.id}'),
          ('${uuidV4()}', 'Mallet', '${state.id}'),
          ('${uuidV4()}', 'Mamborê', '${state.id}'),
          ('${uuidV4()}', 'Mandaguaçu', '${state.id}'),
          ('${uuidV4()}', 'Mandaguari', '${state.id}'),
          ('${uuidV4()}', 'Mandirituba', '${state.id}'),
          ('${uuidV4()}', 'Manfrinópolis', '${state.id}'),
          ('${uuidV4()}', 'Mangueirinha', '${state.id}'),
          ('${uuidV4()}', 'Manoel Ribas', '${state.id}'),
          ('${uuidV4()}', 'Marechal Cândido Rondon', '${state.id}'),
          ('${uuidV4()}', 'Maria Helena', '${state.id}'),
          ('${uuidV4()}', 'Marialva', '${state.id}'),
          ('${uuidV4()}', 'Marilândia do Sul', '${state.id}'),
          ('${uuidV4()}', 'Marilena', '${state.id}'),
          ('${uuidV4()}', 'Mariluz', '${state.id}'),
          ('${uuidV4()}', 'Maringá', '${state.id}'),
          ('${uuidV4()}', 'Mariópolis', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
