import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "BA";

export class PopulateCityWithStateBA1640609401322
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Abaíra', '${state.id}'),
          ('${uuidV4()}', 'Abaré', '${state.id}'),
          ('${uuidV4()}', 'Acajutiba', '${state.id}'),
          ('${uuidV4()}', 'Adustina', '${state.id}'),
          ('${uuidV4()}', 'Água Fria', '${state.id}'),
          ('${uuidV4()}', 'Aiquara', '${state.id}'),
          ('${uuidV4()}', 'Alagoinhas', '${state.id}'),
          ('${uuidV4()}', 'Alcobaça', '${state.id}'),
          ('${uuidV4()}', 'Almadina', '${state.id}'),
          ('${uuidV4()}', 'Amargosa', '${state.id}'),
          ('${uuidV4()}', 'Amélia Rodrigues', '${state.id}'),
          ('${uuidV4()}', 'América Dourada', '${state.id}'),
          ('${uuidV4()}', 'Anagé', '${state.id}'),
          ('${uuidV4()}', 'Andaraí', '${state.id}'),
          ('${uuidV4()}', 'Andorinha', '${state.id}'),
          ('${uuidV4()}', 'Angical', '${state.id}'),
          ('${uuidV4()}', 'Anguera', '${state.id}'),
          ('${uuidV4()}', 'Antas', '${state.id}'),
          ('${uuidV4()}', 'Antônio Cardoso', '${state.id}'),
          ('${uuidV4()}', 'Antônio Gonçalves', '${state.id}'),
          ('${uuidV4()}', 'Aporá', '${state.id}'),
          ('${uuidV4()}', 'Apuarema', '${state.id}'),
          ('${uuidV4()}', 'Araças', '${state.id}'),
          ('${uuidV4()}', 'Aracatu', '${state.id}'),
          ('${uuidV4()}', 'Araci', '${state.id}'),
          ('${uuidV4()}', 'Aramari', '${state.id}'),
          ('${uuidV4()}', 'Arataca', '${state.id}'),
          ('${uuidV4()}', 'Aratuípe', '${state.id}'),
          ('${uuidV4()}', 'Aurelino Leal', '${state.id}'),
          ('${uuidV4()}', 'Baianópolis', '${state.id}'),
          ('${uuidV4()}', 'Baixa Grande', '${state.id}'),
          ('${uuidV4()}', 'Banzaê', '${state.id}'),
          ('${uuidV4()}', 'Barra', '${state.id}'),
          ('${uuidV4()}', 'Barra da Estiva', '${state.id}'),
          ('${uuidV4()}', 'Barra do Choça', '${state.id}'),
          ('${uuidV4()}', 'Barra do Mendes', '${state.id}'),
          ('${uuidV4()}', 'Barra do Rocha', '${state.id}'),
          ('${uuidV4()}', 'Barreiras', '${state.id}'),
          ('${uuidV4()}', 'Barro Alto', '${state.id}'),
          ('${uuidV4()}', 'Barro Preto (antigo Gov. Lomanto Jr.)', '${
        state.id
      }'),
          ('${uuidV4()}', 'Barrocas', '${state.id}'),
          ('${uuidV4()}', 'Belmonte', '${state.id}'),
          ('${uuidV4()}', 'Belo Campo', '${state.id}'),
          ('${uuidV4()}', 'Biritinga', '${state.id}'),
          ('${uuidV4()}', 'Boa Nova', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista do Tupim', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus da Lapa', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus da Serra', '${state.id}'),
          ('${uuidV4()}', 'Boninal', '${state.id}'),
          ('${uuidV4()}', 'Bonito', '${state.id}'),
          ('${uuidV4()}', 'Boquira', '${state.id}'),
          ('${uuidV4()}', 'Botuporã', '${state.id}'),
          ('${uuidV4()}', 'Brejões', '${state.id}'),
          ('${uuidV4()}', 'Brejolândia', '${state.id}'),
          ('${uuidV4()}', 'Brotas de Macaúbas', '${state.id}'),
          ('${uuidV4()}', 'Brumado', '${state.id}'),
          ('${uuidV4()}', 'Buerarema', '${state.id}'),
          ('${uuidV4()}', 'Buritirama', '${state.id}'),
          ('${uuidV4()}', 'Caatiba', '${state.id}'),
          ('${uuidV4()}', 'Cabaceiras do Paraguaçu', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira', '${state.id}'),
          ('${uuidV4()}', 'Caculé', '${state.id}'),
          ('${uuidV4()}', 'Caém', '${state.id}'),
          ('${uuidV4()}', 'Caetanos', '${state.id}'),
          ('${uuidV4()}', 'Caetité', '${state.id}'),
          ('${uuidV4()}', 'Cafarnaum', '${state.id}'),
          ('${uuidV4()}', 'Cairu', '${state.id}'),
          ('${uuidV4()}', 'Caldeirão Grande', '${state.id}'),
          ('${uuidV4()}', 'Camacan', '${state.id}'),
          ('${uuidV4()}', 'Camaçari', '${state.id}'),
          ('${uuidV4()}', 'Camamu', '${state.id}'),
          ('${uuidV4()}', 'Campo Alegre de Lourdes', '${state.id}'),
          ('${uuidV4()}', 'Campo Formoso', '${state.id}'),
          ('${uuidV4()}', 'Canápolis', '${state.id}'),
          ('${uuidV4()}', 'Canarana', '${state.id}'),
          ('${uuidV4()}', 'Canavieiras', '${state.id}'),
          ('${uuidV4()}', 'Candeal', '${state.id}'),
          ('${uuidV4()}', 'Candeias', '${state.id}'),
          ('${uuidV4()}', 'Candiba', '${state.id}'),
          ('${uuidV4()}', 'Cândido Sales', '${state.id}'),
          ('${uuidV4()}', 'Cansanção', '${state.id}'),
          ('${uuidV4()}', 'Canudos', '${state.id}'),
          ('${uuidV4()}', 'Capela do Alto Alegre', '${state.id}'),
          ('${uuidV4()}', 'Capim Grosso', '${state.id}'),
          ('${uuidV4()}', 'Caraíbas', '${state.id}'),
          ('${uuidV4()}', 'Caravelas', '${state.id}'),
          ('${uuidV4()}', 'Cardeal da Silva', '${state.id}'),
          ('${uuidV4()}', 'Carinhanha', '${state.id}'),
          ('${uuidV4()}', 'Casa Nova', '${state.id}'),
          ('${uuidV4()}', 'Castro Alves', '${state.id}'),
          ('${uuidV4()}', 'Catolândia', '${state.id}'),
          ('${uuidV4()}', 'Catu', '${state.id}'),
          ('${uuidV4()}', 'Caturama', '${state.id}'),
          ('${uuidV4()}', 'Central', '${state.id}'),
          ('${uuidV4()}', 'Chorrochó', '${state.id}'),
          ('${uuidV4()}', 'Cícero Dantas', '${state.id}'),
          ('${uuidV4()}', 'Cipó', '${state.id}'),
          ('${uuidV4()}', 'Coaraci', '${state.id}'),
          ('${uuidV4()}', 'Cocos', '${state.id}'),
          ('${uuidV4()}', 'Conceição da Feira', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Almeida', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Coité', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Jacuípe', '${state.id}'),
          ('${uuidV4()}', 'Conde', '${state.id}'),
          ('${uuidV4()}', 'Condeúba', '${state.id}'),
          ('${uuidV4()}', 'Contendas do Sincorá', '${state.id}'),
          ('${uuidV4()}', 'Coração de Maria', '${state.id}'),
          ('${uuidV4()}', 'Cordeiros', '${state.id}'),
          ('${uuidV4()}', 'Coribe', '${state.id}'),
          ('${uuidV4()}', 'Coronel João Sá', '${state.id}'),
          ('${uuidV4()}', 'Correntina', '${state.id}'),
          ('${uuidV4()}', 'Cotegipe', '${state.id}'),
          ('${uuidV4()}', 'Cravolândia', '${state.id}'),
          ('${uuidV4()}', 'Crisópolis', '${state.id}'),
          ('${uuidV4()}', 'Cristópolis', '${state.id}'),
          ('${uuidV4()}', 'Cruz das Almas', '${state.id}'),
          ('${uuidV4()}', 'Curaçá', '${state.id}'),
          ('${uuidV4()}', 'Dário Meira', '${state.id}'),
          ('${uuidV4()}', 'Dias d´Ávila', '${state.id}'),
          ('${uuidV4()}', 'Dom Basílio', '${state.id}'),
          ('${uuidV4()}', 'Dom Macedo Costa', '${state.id}'),
          ('${uuidV4()}', 'Elísio Medrado', '${state.id}'),
          ('${uuidV4()}', 'Encruzilhada', '${state.id}'),
          ('${uuidV4()}', 'Entre Rios', '${state.id}'),
          ('${uuidV4()}', 'Érico Cardoso', '${state.id}'),
          ('${uuidV4()}', 'Esplanada', '${state.id}'),
          ('${uuidV4()}', 'Euclides da Cunha', '${state.id}'),
          ('${uuidV4()}', 'Eunápolis', '${state.id}'),
          ('${uuidV4()}', 'Fátima', '${state.id}'),
          ('${uuidV4()}', 'Feira da Mata', '${state.id}'),
          ('${uuidV4()}', 'Feira de Santana', '${state.id}'),
          ('${uuidV4()}', 'Filadélfia', '${state.id}'),
          ('${uuidV4()}', 'Firmino Alves', '${state.id}'),
          ('${uuidV4()}', 'Floresta Azul', '${state.id}'),
          ('${uuidV4()}', 'Formosa do Rio Preto', '${state.id}'),
          ('${uuidV4()}', 'Gandu', '${state.id}'),
          ('${uuidV4()}', 'Gavião', '${state.id}'),
          ('${uuidV4()}', 'Gentio do Ouro', '${state.id}'),
          ('${uuidV4()}', 'Glória', '${state.id}'),
          ('${uuidV4()}', 'Gongogi', '${state.id}'),
          ('${uuidV4()}', 'Governador Mangabeira', '${state.id}'),
          ('${uuidV4()}', 'Guajeru', '${state.id}'),
          ('${uuidV4()}', 'Guanambi', '${state.id}'),
          ('${uuidV4()}', 'Guaratinga', '${state.id}'),
          ('${uuidV4()}', 'Heliópolis', '${state.id}'),
          ('${uuidV4()}', 'Iaçu', '${state.id}'),
          ('${uuidV4()}', 'Ibiassucê', '${state.id}'),
          ('${uuidV4()}', 'Ibicaraí', '${state.id}'),
          ('${uuidV4()}', 'Ibicoara', '${state.id}'),
          ('${uuidV4()}', 'Ibicuí', '${state.id}'),
          ('${uuidV4()}', 'Ibipeba', '${state.id}'),
          ('${uuidV4()}', 'Ibipitanga', '${state.id}'),
          ('${uuidV4()}', 'Ibiquera', '${state.id}'),
          ('${uuidV4()}', 'Ibirapitanga', '${state.id}'),
          ('${uuidV4()}', 'Ibirapuã', '${state.id}'),
          ('${uuidV4()}', 'Ibirataia', '${state.id}'),
          ('${uuidV4()}', 'Ibitiara', '${state.id}'),
          ('${uuidV4()}', 'Ibititá', '${state.id}'),
          ('${uuidV4()}', 'Ibotirama', '${state.id}'),
          ('${uuidV4()}', 'Ichu', '${state.id}'),
          ('${uuidV4()}', 'Igaporã', '${state.id}'),
          ('${uuidV4()}', 'Igrapiúna', '${state.id}'),
          ('${uuidV4()}', 'Iguaí', '${state.id}'),
          ('${uuidV4()}', 'Ilhéus', '${state.id}'),
          ('${uuidV4()}', 'Inhambupe', '${state.id}'),
          ('${uuidV4()}', 'Ipecaetá', '${state.id}'),
          ('${uuidV4()}', 'Ipiaú', '${state.id}'),
          ('${uuidV4()}', 'Ipirá', '${state.id}'),
          ('${uuidV4()}', 'Ipupiara', '${state.id}'),
          ('${uuidV4()}', 'Irajuba', '${state.id}'),
          ('${uuidV4()}', 'Iramaia', '${state.id}'),
          ('${uuidV4()}', 'Iraquara', '${state.id}'),
          ('${uuidV4()}', 'Irará', '${state.id}'),
          ('${uuidV4()}', 'Irecê', '${state.id}'),
          ('${uuidV4()}', 'Itabela', '${state.id}'),
          ('${uuidV4()}', 'Itaberaba', '${state.id}'),
          ('${uuidV4()}', 'Itabuna', '${state.id}'),
          ('${uuidV4()}', 'Itacaré', '${state.id}'),
          ('${uuidV4()}', 'Itaeté', '${state.id}'),
          ('${uuidV4()}', 'Itagi', '${state.id}'),
          ('${uuidV4()}', 'Itagibá', '${state.id}'),
          ('${uuidV4()}', 'Itagimirim', '${state.id}'),
          ('${uuidV4()}', 'Itaguaçu da Bahia', '${state.id}'),
          ('${uuidV4()}', 'Itaju do Colônia', '${state.id}'),
          ('${uuidV4()}', 'Itajuípe', '${state.id}'),
          ('${uuidV4()}', 'Itamaraju', '${state.id}'),
          ('${uuidV4()}', 'Itamari', '${state.id}'),
          ('${uuidV4()}', 'Itambé', '${state.id}'),
          ('${uuidV4()}', 'Itanagra', '${state.id}'),
          ('${uuidV4()}', 'Itanhém', '${state.id}'),
          ('${uuidV4()}', 'Itaparica', '${state.id}'),
          ('${uuidV4()}', 'Itapé', '${state.id}'),
          ('${uuidV4()}', 'Itapebi', '${state.id}'),
          ('${uuidV4()}', 'Itapetinga', '${state.id}'),
          ('${uuidV4()}', 'Itapicuru', '${state.id}'),
          ('${uuidV4()}', 'Itapitanga', '${state.id}'),
          ('${uuidV4()}', 'Itaquara', '${state.id}'),
          ('${uuidV4()}', 'Itarantim', '${state.id}'),
          ('${uuidV4()}', 'Itatim', '${state.id}'),
          ('${uuidV4()}', 'Itiruçu', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
