import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "MA";

export class PopulateCityWithStateMA1640609437313
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
        INSERT INTO
          "city" (id, name, state_id)
        VALUES
          ('${uuidV4()}', 'Açailândia', '${state.id}'),
          ('${uuidV4()}', 'Afonso Cunha', '${state.id}'),
          ('${uuidV4()}', 'Água Doce do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Alcântara', '${state.id}'),
          ('${uuidV4()}', 'Aldeias Altas', '${state.id}'),
          ('${uuidV4()}', 'Altamira do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Alto Alegre do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Alto Alegre do Pindaré', '${state.id}'),
          ('${uuidV4()}', 'Alto Parnaíba', '${state.id}'),
          ('${uuidV4()}', 'Amapá do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Amarante do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Anajatuba', '${state.id}'),
          ('${uuidV4()}', 'Anapurus', '${state.id}'),
          ('${uuidV4()}', 'Apicum-Açu', '${state.id}'),
          ('${uuidV4()}', 'Araguanã', '${state.id}'),
          ('${uuidV4()}', 'Araioses', '${state.id}'),
          ('${uuidV4()}', 'Arame', '${state.id}'),
          ('${uuidV4()}', 'Arari', '${state.id}'),
          ('${uuidV4()}', 'Axixá', '${state.id}'),
          ('${uuidV4()}', 'Bacabal', '${state.id}'),
          ('${uuidV4()}', 'Bacabeira', '${state.id}'),
          ('${uuidV4()}', 'Bacuri', '${state.id}'),
          ('${uuidV4()}', 'Bacurituba', '${state.id}'),
          ('${uuidV4()}', 'Balsas', '${state.id}'),
          ('${uuidV4()}', 'Barão de Grajaú', '${state.id}'),
          ('${uuidV4()}', 'Barra do Corda', '${state.id}'),
          ('${uuidV4()}', 'Barreirinhas', '${state.id}'),
          ('${uuidV4()}', 'Bela Vista do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Belágua', '${state.id}'),
          ('${uuidV4()}', 'Benedito Leite', '${state.id}'),
          ('${uuidV4()}', 'Bequimão', '${state.id}'),
          ('${uuidV4()}', 'Bernardo do Mearim', '${state.id}'),
          ('${uuidV4()}', 'Boa Vista do Gurupi', '${state.id}'),
          ('${uuidV4()}', 'Bom Jardim', '${state.id}'),
          ('${uuidV4()}', 'Bom Jesus das Selvas', '${state.id}'),
          ('${uuidV4()}', 'Bom Lugar', '${state.id}'),
          ('${uuidV4()}', 'Brejo', '${state.id}'),
          ('${uuidV4()}', 'Brejo de Areia', '${state.id}'),
          ('${uuidV4()}', 'Buriti', '${state.id}'),
          ('${uuidV4()}', 'Buriti Bravo', '${state.id}'),
          ('${uuidV4()}', 'Buriticupu', '${state.id}'),
          ('${uuidV4()}', 'Buritirana', '${state.id}'),
          ('${uuidV4()}', 'Cachoeira Grande', '${state.id}'),
          ('${uuidV4()}', 'Cajapió', '${state.id}'),
          ('${uuidV4()}', 'Cajari', '${state.id}'),
          ('${uuidV4()}', 'Campestre do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Cândido Mendes', '${state.id}'),
          ('${uuidV4()}', 'Cantanhede', '${state.id}'),
          ('${uuidV4()}', 'Capinzal do Norte', '${state.id}'),
          ('${uuidV4()}', 'Carolina', '${state.id}'),
          ('${uuidV4()}', 'Carutapera', '${state.id}'),
          ('${uuidV4()}', 'Caxias', '${state.id}'),
          ('${uuidV4()}', 'Cedral', '${state.id}'),
          ('${uuidV4()}', 'Central do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Centro do Guilherme', '${state.id}'),
          ('${uuidV4()}', 'Centro Novo do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Chapadinha', '${state.id}'),
          ('${uuidV4()}', 'Cidelândia', '${state.id}'),
          ('${uuidV4()}', 'Codó', '${state.id}'),
          ('${uuidV4()}', 'Coelho Neto', '${state.id}'),
          ('${uuidV4()}', 'Colinas', '${state.id}'),
          ('${uuidV4()}', 'Conceição do Lago-Açu', '${state.id}'),
          ('${uuidV4()}', 'Coroatá', '${state.id}'),
          ('${uuidV4()}', 'Cururupu', '${state.id}'),
          ('${uuidV4()}', 'Davinópolis', '${state.id}'),
          ('${uuidV4()}', 'Dom Pedro', '${state.id}'),
          ('${uuidV4()}', 'Duque Bacelar', '${state.id}'),
          ('${uuidV4()}', 'Esperantinópolis', '${state.id}'),
          ('${uuidV4()}', 'Estreito', '${state.id}'),
          ('${uuidV4()}', 'Feira Nova do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Fernando Falcão', '${state.id}'),
          ('${uuidV4()}', 'Formosa da Serra Negra', '${state.id}'),
          ('${uuidV4()}', 'Fortaleza dos Nogueiras', '${state.id}'),
          ('${uuidV4()}', 'Fortuna', '${state.id}'),
          ('${uuidV4()}', 'Godofredo Viana', '${state.id}'),
          ('${uuidV4()}', 'Gonçalves Dias', '${state.id}'),
          ('${uuidV4()}', 'Governador Archer', '${state.id}'),
          ('${uuidV4()}', 'Governador Edison Lobão', '${state.id}'),
          ('${uuidV4()}', 'Governador Eugênio Barros', '${state.id}'),
          ('${uuidV4()}', 'Governador Luiz Rocha', '${state.id}'),
          ('${uuidV4()}', 'Governador Newton Bello', '${state.id}'),
          ('${uuidV4()}', 'Governador Nunes Freire', '${state.id}'),
          ('${uuidV4()}', 'Graça Aranha', '${state.id}'),
          ('${uuidV4()}', 'Grajaú', '${state.id}'),
          ('${uuidV4()}', 'Guimarães', '${state.id}'),
          ('${uuidV4()}', 'Humberto de Campos', '${state.id}'),
          ('${uuidV4()}', 'Icatu', '${state.id}'),
          ('${uuidV4()}', 'Igarapé do Meio', '${state.id}'),
          ('${uuidV4()}', 'Igarapé Grande', '${state.id}'),
          ('${uuidV4()}', 'Imperatriz', '${state.id}'),
          ('${uuidV4()}', 'Itaipava do Grajaú', '${state.id}'),
          ('${uuidV4()}', 'Itapecuru Mirim', '${state.id}'),
          ('${uuidV4()}', 'Itinga do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Jatobá', '${state.id}'),
          ('${uuidV4()}', 'Jenipapo dos Vieiras', '${state.id}'),
          ('${uuidV4()}', 'João Lisboa', '${state.id}'),
          ('${uuidV4()}', 'Joselândia', '${state.id}'),
          ('${uuidV4()}', 'Junco do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Lago da Pedra', '${state.id}'),
          ('${uuidV4()}', 'Lago do Junco', '${state.id}'),
          ('${uuidV4()}', 'Lago dos Rodrigues', '${state.id}'),
          ('${uuidV4()}', 'Lago Verde', '${state.id}'),
          ('${uuidV4()}', 'Lagoa do Mato', '${state.id}'),
          ('${uuidV4()}', 'Lagoa Grande do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Lajeado Novo', '${state.id}'),
          ('${uuidV4()}', 'Lima Campos', '${state.id}'),
          ('${uuidV4()}', 'Loreto', '${state.id}'),
          ('${uuidV4()}', 'Luís Domingues', '${state.id}'),
          ('${uuidV4()}', 'Magalhães de Almeida', '${state.id}'),
          ('${uuidV4()}', 'Maracaçumé', '${state.id}'),
          ('${uuidV4()}', 'Marajá do Sena', '${state.id}'),
          ('${uuidV4()}', 'Maranhãozinho', '${state.id}'),
          ('${uuidV4()}', 'Mata Roma', '${state.id}'),
          ('${uuidV4()}', 'Matinha', '${state.id}'),
          ('${uuidV4()}', 'Matões', '${state.id}'),
          ('${uuidV4()}', 'Matões do Norte', '${state.id}'),
          ('${uuidV4()}', 'Milagres do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Mirador', '${state.id}'),
          ('${uuidV4()}', 'Miranda do Norte', '${state.id}'),
          ('${uuidV4()}', 'Mirinzal', '${state.id}'),
          ('${uuidV4()}', 'Monção', '${state.id}'),
          ('${uuidV4()}', 'Montes Altos', '${state.id}'),
          ('${uuidV4()}', 'Morros', '${state.id}'),
          ('${uuidV4()}', 'Nina Rodrigues', '${state.id}'),
          ('${uuidV4()}', 'Nova Colinas', '${state.id}'),
          ('${uuidV4()}', 'Nova Iorque', '${state.id}'),
          ('${uuidV4()}', 'Nova Olinda do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Olho d´Água das Cunhãs', '${state.id}'),
          ('${uuidV4()}', 'Olinda Nova do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Paço do Lumiar', '${state.id}'),
          ('${uuidV4()}', 'Palmeirândia', '${state.id}'),
          ('${uuidV4()}', 'Paraibano', '${state.id}'),
          ('${uuidV4()}', 'Parnarama', '${state.id}'),
          ('${uuidV4()}', 'Passagem Franca', '${state.id}'),
          ('${uuidV4()}', 'Pastos Bons', '${state.id}'),
          ('${uuidV4()}', 'Paulino Neves', '${state.id}'),
          ('${uuidV4()}', 'Paulo Ramos', '${state.id}'),
          ('${uuidV4()}', 'Pedreiras', '${state.id}'),
          ('${uuidV4()}', 'Pedro do Rosário', '${state.id}'),
          ('${uuidV4()}', 'Penalva', '${state.id}'),
          ('${uuidV4()}', 'Peri Mirim', '${state.id}'),
          ('${uuidV4()}', 'Peritoró', '${state.id}'),
          ('${uuidV4()}', 'Pindaré-Mirim', '${state.id}'),
          ('${uuidV4()}', 'Pinheiro', '${state.id}'),
          ('${uuidV4()}', 'Pio XII', '${state.id}'),
          ('${uuidV4()}', 'Pirapemas', '${state.id}'),
          ('${uuidV4()}', 'Poção de Pedras', '${state.id}'),
          ('${uuidV4()}', 'Porto Franco', '${state.id}'),
          ('${uuidV4()}', 'Porto Rico do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Presidente Dutra', '${state.id}'),
          ('${uuidV4()}', 'Presidente Juscelino', '${state.id}'),
          ('${uuidV4()}', 'Presidente Médici', '${state.id}'),
          ('${uuidV4()}', 'Presidente Sarney', '${state.id}'),
          ('${uuidV4()}', 'Presidente Vargas', '${state.id}'),
          ('${uuidV4()}', 'Primeira Cruz', '${state.id}'),
          ('${uuidV4()}', 'Raposa', '${state.id}'),
          ('${uuidV4()}', 'Riachão', '${state.id}'),
          ('${uuidV4()}', 'Ribamar Fiquene', '${state.id}'),
          ('${uuidV4()}', 'Rosário', '${state.id}'),
          ('${uuidV4()}', 'Sambaíba', '${state.id}'),
          ('${uuidV4()}', 'Santa Filomena do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Santa Helena', '${state.id}'),
          ('${uuidV4()}', 'Santa Inês', '${state.id}'),
          ('${uuidV4()}', 'Santa Luzia', '${state.id}'),
          ('${uuidV4()}', 'Santa Luzia do Paruá', '${state.id}'),
          ('${uuidV4()}', 'Santa Quitéria do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Santa Rita', '${state.id}'),
          ('${uuidV4()}', 'Santana do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Santo Amaro do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Santo Antônio dos Lopes', '${state.id}'),
          ('${uuidV4()}', 'São Benedito do Rio Preto', '${state.id}'),
          ('${uuidV4()}', 'São Bento', '${state.id}'),
          ('${uuidV4()}', 'São Bernardo', '${state.id}'),
          ('${uuidV4()}', 'São Domingos do Azeitão', '${state.id}'),
          ('${uuidV4()}', 'São Domingos do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'São Félix de Balsas', '${state.id}'),
          ('${uuidV4()}', 'São Francisco do Brejão', '${state.id}'),
          ('${uuidV4()}', 'São Francisco do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'São João Batista', '${state.id}'),
          ('${uuidV4()}', 'São João do Carú', '${state.id}'),
          ('${uuidV4()}', 'São João do Paraíso', '${state.id}'),
          ('${uuidV4()}', 'São João do Soter', '${state.id}'),
          ('${uuidV4()}', 'São João dos Patos', '${state.id}'),
          ('${uuidV4()}', 'São José de Ribamar', '${state.id}'),
          ('${uuidV4()}', 'São José dos Basílios', '${state.id}'),
          ('${uuidV4()}', 'São Luís', '${state.id}'),
          ('${uuidV4()}', 'São Luís Gonzaga do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'São Mateus do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'São Pedro da Água Branca', '${state.id}'),
          ('${uuidV4()}', 'São Pedro dos Crentes', '${state.id}'),
          ('${uuidV4()}', 'São Raimundo das Mangabeiras', '${state.id}'),
          ('${uuidV4()}', 'São Raimundo do Doca Bezerra', '${state.id}'),
          ('${uuidV4()}', 'São Roberto', '${state.id}'),
          ('${uuidV4()}', 'São Vicente Ferrer', '${state.id}'),
          ('${uuidV4()}', 'Satubinha', '${state.id}'),
          ('${uuidV4()}', 'Senador Alexandre Costa', '${state.id}'),
          ('${uuidV4()}', 'Senador La Rocque', '${state.id}'),
          ('${uuidV4()}', 'Serrano do Maranhão', '${state.id}'),
          ('${uuidV4()}', 'Sítio Novo', '${state.id}'),
          ('${uuidV4()}', 'Sucupira do Norte', '${state.id}'),
          ('${uuidV4()}', 'Sucupira do Riachão', '${state.id}'),
          ('${uuidV4()}', 'Tasso Fragoso', '${state.id}'),
          ('${uuidV4()}', 'Timbiras', '${state.id}'),
          ('${uuidV4()}', 'Timon', '${state.id}'),
          ('${uuidV4()}', 'Trizidela do Vale', '${state.id}'),
          ('${uuidV4()}', 'Tufilândia', '${state.id}'),
          ('${uuidV4()}', 'Tuntum', '${state.id}'),
          ('${uuidV4()}', 'Turiaçu', '${state.id}'),
          ('${uuidV4()}', 'Turilândia', '${state.id}'),
          ('${uuidV4()}', 'Tutóia', '${state.id}'),
          ('${uuidV4()}', 'Urbano Santos', '${state.id}'),
          ('${uuidV4()}', 'Vargem Grande', '${state.id}'),
          ('${uuidV4()}', 'Viana', '${state.id}'),
          ('${uuidV4()}', 'Vila Nova dos Martírios', '${state.id}'),
          ('${uuidV4()}', 'Vitória do Mearim', '${state.id}'),
          ('${uuidV4()}', 'Vitorino Freire', '${state.id}'),
          ('${uuidV4()}', 'Zé Doca', '${state.id}')
        ;
      `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
