import { MigrationInterface, QueryRunner } from "typeorm";
import { v4 as uuidV4 } from "uuid";

import { State } from "@modules/territory/infra/typeorm/entities/State";

const acronym = "MG";

export class PopulateCityWithStateMGPart41645622111923
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `
            INSERT INTO
              "city" (id, name, state_id)
            VALUES
            ('${uuidV4()}', 'Oliveira Fortes', '${state.id}'),
            ('${uuidV4()}', 'Onça de Pitangui', '${state.id}'),
            ('${uuidV4()}', 'Oratórios', '${state.id}'),
            ('${uuidV4()}', 'Vespasiano', '${state.id}'),
            ('${uuidV4()}', 'Viçosa', '${state.id}'),
            ('${uuidV4()}', 'Vieiras', '${state.id}'),
            ('${uuidV4()}', 'Virgem da Lapa', '${state.id}'),
            ('${uuidV4()}', 'Virgínia', '${state.id}'),
            ('${uuidV4()}', 'Virginópolis', '${state.id}'),
            ('${uuidV4()}', 'Virgolândia', '${state.id}'),
            ('${uuidV4()}', 'Visconde do Rio Branco', '${state.id}'),
            ('${uuidV4()}', 'Volta Grande', '${state.id}'),
            ('${uuidV4()}', 'Wenceslau Braz', '${state.id}'),
            ('${uuidV4()}', 'União de Minas', '${state.id}'),
            ('${uuidV4()}', 'Uruana de Minas', '${state.id}'),
            ('${uuidV4()}', 'Urucânia', '${state.id}'),
            ('${uuidV4()}', 'Urucuia', '${state.id}'),
            ('${uuidV4()}', 'Vargem Alegre', '${state.id}'),
            ('${uuidV4()}', 'Vargem Bonita', '${state.id}'),
            ('${uuidV4()}', 'Vargem Grande do Rio Pardo', '${state.id}'),
            ('${uuidV4()}', 'Varginha', '${state.id}'),
            ('${uuidV4()}', 'Varjão de Minas', '${state.id}'),
            ('${uuidV4()}', 'Várzea da Palma', '${state.id}'),
            ('${uuidV4()}', 'Varzelândia', '${state.id}'),
            ('${uuidV4()}', 'Vazante', '${state.id}'),
            ('${uuidV4()}', 'Verdelândia', '${state.id}'),
            ('${uuidV4()}', 'Veredinha', '${state.id}'),
            ('${uuidV4()}', 'Veríssimo', '${state.id}'),
            ('${uuidV4()}', 'Vermelho Novo', '${state.id}'),
            ('${uuidV4()}', 'Monte Alegre de Minas', '${state.id}'),
            ('${uuidV4()}', 'Monte Azul', '${state.id}'),
            ('${uuidV4()}', 'Monte Belo', '${state.id}'),
            ('${uuidV4()}', 'Monte Carmelo', '${state.id}'),
            ('${uuidV4()}', 'Monte Formoso', '${state.id}'),
            ('${uuidV4()}', 'Monte Santo de Minas', '${state.id}'),
            ('${uuidV4()}', 'Monte Sião', '${state.id}'),
            ('${uuidV4()}', 'Montes Claros', '${state.id}'),
            ('${uuidV4()}', 'Montezuma', '${state.id}'),
            ('${uuidV4()}', 'Morada Nova de Minas', '${state.id}'),
            ('${uuidV4()}', 'Morro da Garça', '${state.id}'),
            ('${uuidV4()}', 'Morro do Pilar', '${state.id}'),
            ('${uuidV4()}', 'Munhoz', '${state.id}'),
            ('${uuidV4()}', 'Muriaé', '${state.id}'),
            ('${uuidV4()}', 'Mutum', '${state.id}'),
            ('${uuidV4()}', 'Muzambinho', '${state.id}'),
            ('${uuidV4()}', 'Nacip Raydan', '${state.id}'),
            ('${uuidV4()}', 'Nanuque', '${state.id}'),
            ('${uuidV4()}', 'Naque', '${state.id}'),
            ('${uuidV4()}', 'Natalândia', '${state.id}'),
            ('${uuidV4()}', 'Natércia', '${state.id}'),
            ('${uuidV4()}', 'Nazareno', '${state.id}'),
            ('${uuidV4()}', 'Nepomuceno', '${state.id}'),
            ('${uuidV4()}', 'Ninheira', '${state.id}'),
            ('${uuidV4()}', 'Nova Belém', '${state.id}'),
            ('${uuidV4()}', 'Nova Era', '${state.id}'),
            ('${uuidV4()}', 'Nova Lima', '${state.id}'),
            ('${uuidV4()}', 'Nova Módica', '${state.id}'),
            ('${uuidV4()}', 'Nova Ponte', '${state.id}'),
            ('${uuidV4()}', 'Nova Porteirinha', '${state.id}'),
            ('${uuidV4()}', 'Nova Resende', '${state.id}'),
            ('${uuidV4()}', 'Nova Serrana', '${state.id}'),
            ('${uuidV4()}', 'Nova União', '${state.id}'),
            ('${uuidV4()}', 'Novo Cruzeiro', '${state.id}'),
            ('${uuidV4()}', 'Novo Oriente de Minas', '${state.id}'),
            ('${uuidV4()}', 'Novorizonte', '${state.id}'),
            ('${uuidV4()}', 'Olaria', '${state.id}'),
            ('${uuidV4()}', 'Sete Lagoas', '${state.id}'),
            ('${uuidV4()}', 'Setubinha', '${state.id}'),
            ('${uuidV4()}', 'Silveirânia', '${state.id}'),
            ('${uuidV4()}', 'Silvianópolis', '${state.id}'),
            ('${uuidV4()}', 'Simão Pereira', '${state.id}'),
            ('${uuidV4()}', 'Simonésia', '${state.id}'),
            ('${uuidV4()}', 'Sobrália', '${state.id}'),
            ('${uuidV4()}', 'Soledade de Minas', '${state.id}'),
            ('${uuidV4()}', 'Tabuleiro', '${state.id}'),
            ('${uuidV4()}', 'Taiobeiras', '${state.id}'),
            ('${uuidV4()}', 'Taparuba', '${state.id}'),
            ('${uuidV4()}', 'Tapira', '${state.id}'),
            ('${uuidV4()}', 'Tapiraí', '${state.id}'),
            ('${uuidV4()}', 'Taquaraçu de Minas', '${state.id}'),
            ('${uuidV4()}', 'Tarumirim', '${state.id}'),
            ('${uuidV4()}', 'Teixeiras', '${state.id}'),
            ('${uuidV4()}', 'Teófilo Otoni', '${state.id}'),
            ('${uuidV4()}', 'Timóteo', '${state.id}'),
            ('${uuidV4()}', 'Tiradentes', '${state.id}'),
            ('${uuidV4()}', 'Tiros', '${state.id}'),
            ('${uuidV4()}', 'Tocantins', '${state.id}'),
            ('${uuidV4()}', 'Tocos do Moji', '${state.id}'),
            ('${uuidV4()}', 'Toledo', '${state.id}'),
            ('${uuidV4()}', 'Tombos', '${state.id}'),
            ('${uuidV4()}', 'Três Corações', '${state.id}'),
            ('${uuidV4()}', 'Três Marias', '${state.id}'),
            ('${uuidV4()}', 'Três Pontas', '${state.id}'),
            ('${uuidV4()}', 'Tumiritinga', '${state.id}'),
            ('${uuidV4()}', 'Tupaciguara', '${state.id}'),
            ('${uuidV4()}', 'Turmalina', '${state.id}'),
            ('${uuidV4()}', 'Turvolândia', '${state.id}'),
            ('${uuidV4()}', 'Ubá', '${state.id}'),
            ('${uuidV4()}', 'Ubaí', '${state.id}'),
            ('${uuidV4()}', 'Ubaporanga', '${state.id}'),
            ('${uuidV4()}', 'Uberaba', '${state.id}'),
            ('${uuidV4()}', 'Uberlândia', '${state.id}'),
            ('${uuidV4()}', 'Umburatiba', '${state.id}'),
            ('${uuidV4()}', 'Unaí', '${state.id}'),
            ('${uuidV4()}', 'Sarzedo', '${state.id}'),
            ('${uuidV4()}', 'Sem-Peixe', '${state.id}'),
            ('${uuidV4()}', 'Senador Amaral', '${state.id}'),
            ('${uuidV4()}', 'Senador Cortes', '${state.id}'),
            ('${uuidV4()}', 'Senador Firmino', '${state.id}'),
            ('${uuidV4()}', 'Senador José Bento', '${state.id}'),
            ('${uuidV4()}', 'Senador Modestino Gonçalves', '${state.id}'),
            ('${uuidV4()}', 'Senhora de Oliveira', '${state.id}'),
            ('${uuidV4()}', 'Senhora do Porto', '${state.id}'),
            ('${uuidV4()}', 'Senhora dos Remédios', '${state.id}'),
            ('${uuidV4()}', 'Sericita', '${state.id}'),
            ('${uuidV4()}', 'Seritinga', '${state.id}'),
            ('${uuidV4()}', 'Serra Azul de Minas', '${state.id}'),
            ('${uuidV4()}', 'Serra da Saudade', '${state.id}'),
            ('${uuidV4()}', 'Serra do Salitre', '${state.id}'),
            ('${uuidV4()}', 'Serra dos Aimorés', '${state.id}'),
            ('${uuidV4()}', 'Serrania', '${state.id}'),
            ('${uuidV4()}', 'Serranópolis de Minas', '${state.id}'),
            ('${uuidV4()}', 'Serranos', '${state.id}'),
            ('${uuidV4()}', 'Serro', '${state.id}'),
            ('${uuidV4()}', 'Couto de Magalhães de Minas', '${state.id}'),
            ('${uuidV4()}', 'Crisólita', '${state.id}'),
            ('${uuidV4()}', 'Cristais', '${state.id}'),
            ('${uuidV4()}', 'Cristália', '${state.id}'),
            ('${uuidV4()}', 'Cristiano Otoni', '${state.id}'),
            ('${uuidV4()}', 'Cristina', '${state.id}'),
            ('${uuidV4()}', 'Crucilândia', '${state.id}'),
            ('${uuidV4()}', 'Cruzeiro da Fortaleza', '${state.id}'),
            ('${uuidV4()}', 'Cruzília', '${state.id}'),
            ('${uuidV4()}', 'Cuparaque', '${state.id}'),
            ('${uuidV4()}', 'Curral de Dentro', '${state.id}'),
            ('${uuidV4()}', 'Orizânia', '${state.id}'),
            ('${uuidV4()}', 'Ouro Branco', '${state.id}'),
            ('${uuidV4()}', 'Ouro Fino', '${state.id}'),
            ('${uuidV4()}', 'Ouro Preto', '${state.id}'),
            ('${uuidV4()}', 'Ouro Verde de Minas', '${state.id}'),
            ('${uuidV4()}', 'Padre Carvalho', '${state.id}'),
            ('${uuidV4()}', 'Olhos-d´Água', '${state.id}'),
            ('${uuidV4()}', 'Olímpio Noronha', '${state.id}'),
            ('${uuidV4()}', 'Oliveira', '${state.id}'),
            ('${uuidV4()}', 'Matipó', '${state.id}'),
            ('${uuidV4()}', 'Mato Verde', '${state.id}'),
            ('${uuidV4()}', 'Matozinhos', '${state.id}'),
            ('${uuidV4()}', 'Matutina', '${state.id}'),
            ('${uuidV4()}', 'Medeiros', '${state.id}'),
            ('${uuidV4()}', 'Medina', '${state.id}'),
            ('${uuidV4()}', 'Mendes Pimentel', '${state.id}'),
            ('${uuidV4()}', 'Mercês', '${state.id}'),
            ('${uuidV4()}', 'Mesquita', '${state.id}'),
            ('${uuidV4()}', 'Minas Novas', '${state.id}'),
            ('${uuidV4()}', 'Minduri', '${state.id}'),
            ('${uuidV4()}', 'Mirabela', '${state.id}'),
            ('${uuidV4()}', 'Miradouro', '${state.id}'),
            ('${uuidV4()}', 'Miraí', '${state.id}'),
            ('${uuidV4()}', 'Miravânia', '${state.id}'),
            ('${uuidV4()}', 'Moeda', '${state.id}'),
            ('${uuidV4()}', 'Moema', '${state.id}'),
            ('${uuidV4()}', 'Monjolos', '${state.id}'),
            ('${uuidV4()}', 'Monsenhor Paulo', '${state.id}'),
            ('${uuidV4()}', 'Montalvânia', '${state.id}')
            ;
          `,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const state = await queryRunner.manager.findOne(State, { acronym });

    await queryRunner.query(
      `DELETE FROM "city" WHERE state_id = '${state.id}'`,
    );
  }
}
